#' SIRSd2_risk
#' 
#' @description A SIRSd model with 3 compartments. Processes are infection, recovery, births deaths and waning immunity.
#' 
#' @details The model includes susceptible, infected, and recovered compartments. The processes which are modeled are infection, recovery, natural births and deaths and waning immunity.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of ordinary differential equations using the deSolve package. 
#' The following R packages need to be loaded for the function to work: deSolve. 
#' 
#' Starting conditions for model variables 
#' @param Sh : starting value for Susceptible high risk : numeric
#' @param Sl : starting value for Susceptible low risk : numeric
#' @param Ih : starting value for Infected high risk : numeric
#' @param Il : starting value for Infected low risk : numeric
#' @param Rh : starting value for Recovered high risk : numeric
#' @param Rl : starting value for Recovered low risk : numeric
#' Values for model parameters : numeric 
#' @param b_Sh_Ih : infection rate: to susceptible high risk from infected high risk : numeric
#' @param b_Sh_Il : infection rate: to susceptible high risk from infected low risk : numeric
#' @param w_Rh : waning immunity rate: recovered high risk : numeric
#' @param n : birth rate : numeric
#' @param mS_Sh : death rate of S: susceptible high risk : numeric
#' @param b_Sl_Ih : infection rate: to susceptible low risk from infected high risk : numeric
#' @param b_Sl_Il : infection rate: to susceptible low risk from infected low risk : numeric
#' @param w_Rl : waning immunity rate: recovered low risk : numeric
#' @param mS_Sl : death rate of S: susceptible low risk : numeric
#' @param g_Ih : recovery rate: infected high risk : numeric
#' @param mI_Ih : death rate of I: infected high risk : numeric
#' @param g_Il : recovery rate: infected low risk : numeric
#' @param mI_Il : death rate of I: infected low risk : numeric
#' @param mR_Rh : death rate of R: recovered high risk : numeric
#' @param mR_Rl : death rate of R: recovered low risk : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_SIRSd2_risk_ode() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_SIRSd2_risk_ode(Sh = 2000,Sl = 2000,Ih = 2,Il = 2,Rh = 0,Rl = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'Sh'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of Sh: ',max(result$ts[,'Sh']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 18535
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-09-30
#' @export 
 
simulate_SIRSd2_risk_ode <- function(Sh = 1000, Sl = 1000, Ih = 1, Il = 1, Rh = 0, Rl = 0, b_Sh_Ih = 0.002, b_Sh_Il = 0.002, w_Rh = 1, n = 0, mS_Sh = 0, b_Sl_Ih = 0.002, b_Sl_Il = 0.002, w_Rl = 1, mS_Sl = 0, g_Ih = 1, mI_Ih = 0, g_Il = 1, mI_Il = 0, mR_Rh = 0, mR_Rl = 0, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  ############################## 
  #Block of ODE equations for deSolve 
  ############################## 
  SIRSd2_risk_ode_fct <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible high risk : infection, high risk : infection, high risk : waning immunity, high risk : waning immunity, high risk : births, high risk : births, high risk : natural deaths of S, high risk : natural deaths of S, high risk :
    dSh_mb = -b_Sh_Ih*Sh*Ih -b_Sh_Il*Sh*Il +w_Rh*Rh +n -mS_Sh*Sh
    #Susceptible low risk : infection, low risk : infection, low risk : waning immunity, low risk : waning immunity, low risk : births, low risk : births, low risk : natural deaths of S, low risk : natural deaths of S, low risk :
    dSl_mb = -b_Sl_Ih*Sl*Ih -b_Sl_Il*Sl*Il +w_Rl*Rl +n -mS_Sl*Sl
    #Infected high risk : infection, high risk : infection, high risk : recovery, high risk : recovery, high risk : natural deaths of I, high risk : natural deaths of I, high risk :
    dIh_mb = +b_Sh_Ih*Sh*Ih +b_Sh_Il*Sh*Il -g_Ih*Ih -mI_Ih*Ih
    #Infected low risk : infection, low risk : infection, low risk : recovery, low risk : recovery, low risk : natural deaths of I, low risk : natural deaths of I, low risk :
    dIl_mb = +b_Sl_Ih*Sl*Ih +b_Sl_Il*Sl*Il -g_Il*Il -mI_Il*Il
    #Recovered high risk : recovery, high risk : recovery, high risk : waning immunity, high risk : waning immunity, high risk : natural deaths of R, high risk : natural deaths of R, high risk :
    dRh_mb = +g_Ih*Ih -w_Rh*Rh -mR_Rh*Rh
    #Recovered low risk : recovery, low risk : recovery, low risk : waning immunity, low risk : waning immunity, low risk : natural deaths of R, low risk : natural deaths of R, low risk :
    dRl_mb = +g_Il*Il -w_Rl*Rl -mR_Rl*Rl
    #EndODES
    list(c(dSh_mb,dSl_mb,dIh_mb,dIl_mb,dRh_mb,dRl_mb)) 
  } ) } #close with statement, end ODE code block 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec_mb = c(Sh = Sh, Sl = Sl, Ih = Ih, Il = Il, Rh = Rh, Rl = Rl) 
  parvec_mb = c(b_Sh_Ih = b_Sh_Ih, b_Sh_Il = b_Sh_Il, w_Rh = w_Rh, n = n, mS_Sh = mS_Sh, b_Sl_Ih = b_Sl_Ih, b_Sl_Il = b_Sl_Il, w_Rl = w_Rl, mS_Sl = mS_Sl, g_Ih = g_Ih, mI_Ih = mI_Ih, g_Il = g_Il, mI_Il = mI_Il, mR_Rh = mR_Rh, mR_Rl = mR_Rl) 
  timevec_mb = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout = deSolve::ode(y = varvec_mb, parms = parvec_mb, times = timevec_mb,  func = SIRSd2_risk_ode_fct, rtol = 1e-12, atol = 1e-12) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
} 
