#' SEIRSd_model_stratified
#' 
#' @description A SEIRS model with 4 compartments
#' 
#' @details The model includes susceptible, exposed/asymptomatic, infected/symptomatic, and recovered compartments. The processes that are modeled are infection, progression to infectiousness, recovery and waning immunity. Demographics through natural births and deaths are also included.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of ordinary differential equations using the deSolve package. 
#' The following R packages need to be loaded for the function to work: deSolve. 
#' 
#' Starting conditions for model variables 
#' @param S_h : starting value for Susceptible high risk : numeric
#' @param E_h : starting value for Exposed high risk : numeric
#' @param I_h : starting value for Infected and Symptomatic high risk : numeric
#' @param R_h : starting value for Recovered high risk : numeric
#' @param S_l : starting value for Susceptible low risk : numeric
#' @param E_l : starting value for Exposed low risk : numeric
#' @param I_l : starting value for Infected and Symptomatic low risk : numeric
#' @param R_l : starting value for Recovered low risk : numeric
#' Values for model parameters : numeric 
#' @param bE_h : infection by exposed, high risk : numeric
#' @param bI_h : infection by symptomatic, high risk : numeric
#' @param gE_h : progression rate, high risk : numeric
#' @param gI_h : recovery rate, high risk : numeric
#' @param w_h : waning immunity, high risk : numeric
#' @param n_h : births, high risk : numeric
#' @param m_h : deaths, high risk : numeric
#' @param bE_l : infection by exposed, low risk : numeric
#' @param bI_l : infection by symptomatic, low risk : numeric
#' @param gE_l : progression rate, low risk : numeric
#' @param gI_l : recovery rate, low risk : numeric
#' @param w_l : waning immunity, low risk : numeric
#' @param n_l : births, low risk : numeric
#' @param m_l : deaths, low risk : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_SEIRSd_model_stratified_ode() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_SEIRSd_model_stratified_ode(S_h = 2000,E_h = 2,I_h = 2,R_h = 0,S_l = 2000,E_l = 2,I_l = 2,R_l = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S_h'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S_h: ',max(result$ts[,'S_h']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 18452
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-09-17
#' @export 
 
simulate_SEIRSd_model_stratified_ode <- function(S_h = 1000, E_h = 1, I_h = 1, R_h = 0, S_l = 1000, E_l = 1, I_l = 1, R_l = 0, bE_h = 0, bI_h = 0.001, gE_h = 1, gI_h = 1, w_h = 1, n_h = 0, m_h = 0, bE_l = 0, bI_l = 0.001, gE_l = 1, gI_l = 1, w_l = 1, n_l = 0, m_l = 0, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  ############################## 
  #Block of ODE equations for deSolve 
  ############################## 
  SEIRSd_model_stratified_ode_fct <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible high risk : infection by exposed, high risk : infection by symptomatic, high risk : waning immunity, high risk : births, high risk : natural deaths, high risk :
    dS_h_mb = -bE_h*S_h*E_h-bE_l*S_h*E_l -bI_h*S_h*I_h-bI_l*S_h*I_l +w_h*R_h +n_h -m_h*S_h
    #Exposed high risk : infection by exposed, high risk : infection by symptomatic, high risk : progression to symptoms, high risk : natural deaths, high risk :
    dE_h_mb = +bE_h*S_h*E_h+bE_h*S_l*E_h +bI_h*S_h*I_h+bI_h*S_l*I_l -gE_h*E_h -m_h*E_h
    #Infected and Symptomatic high risk : progression to symptoms, high risk : recovery, high risk : natural deaths, high risk :
    dI_h_mb = +gE_h*E_h -gI_h*I_h -m_h*I_h
    #Recovered high risk : recovery, high risk : waning immunity, high risk : natural death, high risk :
    dR_h_mb = +gI_h*I_h -w_h*R_h -m_h*R_h
    #Susceptible low risk : infection by exposed, low risk : infection by symptomatic, low risk : waning immunity, low risk : births, low risk : natural deaths, low risk :
    dS_l_mb = -bE_h*S_l*E_h-bE_l*S_l*E_l -bI_h*S_l*I_h-bI_l*S_l*I_l +w_l*R_l +n_l -m_l*S_l
    #Exposed low risk : infection by exposed, low risk : infection by symptomatic, low risk : progression to symptoms, low risk : natural deaths, low risk :
    dE_l_mb = +bE_l*S_h*E_l+bE_l*S_l*E_l +bI_l*S_h*I_h+bI_l*S_l*I_l -gE_l*E_l -m_l*E_l
    #Infected and Symptomatic low risk : progression to symptoms, low risk : recovery, low risk : natural deaths, low risk :
    dI_l_mb = +gE_l*E_l -gI_l*I_l -m_l*I_l
    #Recovered low risk : recovery, low risk : waning immunity, low risk : natural death, low risk :
    dR_l_mb = +gI_l*I_l -w_l*R_l -m_l*R_l
    #EndODES
    list(c(dS_h_mb,dE_h_mb,dI_h_mb,dR_h_mb,dS_l_mb,dE_l_mb,dI_l_mb,dR_l_mb)) 
  } ) } #close with statement, end ODE code block 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec_mb = c(S_h = S_h, E_h = E_h, I_h = I_h, R_h = R_h, S_l = S_l, E_l = E_l, I_l = I_l, R_l = R_l) 
  parvec_mb = c(bE_h = bE_h, bI_h = bI_h, gE_h = gE_h, gI_h = gI_h, w_h = w_h, n_h = n_h, m_h = m_h, bE_l = bE_l, bI_l = bI_l, gE_l = gE_l, gI_l = gI_l, w_l = w_l, n_l = n_l, m_l = m_l) 
  timevec_mb = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout = deSolve::ode(y = varvec_mb, parms = parvec_mb, times = timevec_mb,  func = SEIRSd_model_stratified_ode_fct, rtol = 1e-12, atol = 1e-12) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
} 
