#' Bacteria
#' 
#' 
#' 
#' @details 
#' @param B starting value for bac
#' } 
#' @param pars vector of values for model parameters: 
#' \itemize{ 
#' @param g growth rate
#' } 
#' @param times vector of values for model times: 
#' \itemize{ 
#' @param tstart Start time of simulation
#' @param tfinal Final time of simulation
#' @param dt Time step
#' } 
#' @param rngseed random number seed for simulator 
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element 
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Bacteria_stochastic() 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: 
#' @section Model creation date: 2019-01-23
#' @section Code Author: generated by the \code{generate_stochastic} function 
#' @section Code creation date: 2019-01-23
#' @export 
 
simulate_Bacteria_stochastic <- function(vars = c(B = 1), pars = c(g = 1), times = c(tstart = 0, tfinal = 100, dt = 0.1) , rngseed = 123) 
 { 
  #Block of ODE equations for adaptivetau 
  Bacteria_ode <- function(y, parms, t) 
  {
    with(as.list(c(y,parms)),   
     { 
       #specify each rate/transition/reaction that can happen in the system 
     rates = c(g*B)
     return(rates) 
      }
	 	)   
   } # end function specifying rates used by adaptive tau 

   #specify for each reaction/rate/transition how the different variables change 
  #needs to be in exactly the same order as the rates listed in the rate function 
   transitions = list(c(B = +1))

 set.seed(rngseed) #set random number seed for reproducibility 
  #this line runs the simulation using the SSA algorithm in the adaptivetau package 
  odeout = adaptivetau::ssa.adaptivetau(init.values = vars, transitions = transitions,
                	 	 	 rateFunc = Bacteria_ode, params = pars, tf = times[2]) 
  result <- list() 
 
  result$ts <- as.data.frame(odeout) 
 
  return(result) 
 
} 
