#' Coronavirus_vaccine_model_v2_risk
#' 
#' @description A model with 7 compartments
#' 
#' @details The model includes susceptible, presymptomatic, asymptomatic, infected/symptomatic/ill, recovered, hospitalized, and deceased compartments. The processes that are modeled are infection, progression to infectiousness, recovery, and progression to hospitalization and death. Immunity is permanent. Demographics through natural births and deaths are not included.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of ordinary differential equations using the deSolve package. 
#' The following R packages need to be loaded for the function to work: deSolve. 
#' 
#' Starting conditions for model variables 
#' @param Sh : starting value for Susceptible high risk : numeric
#' @param Sl : starting value for Susceptible low risk : numeric
#' @param Ph : starting value for Presymptomatic high risk : numeric
#' @param Pl : starting value for Presymptomatic low risk : numeric
#' @param Ah : starting value for Asymptomatic high risk : numeric
#' @param Al : starting value for Asymptomatic low risk : numeric
#' @param Ih : starting value for Ill high risk : numeric
#' @param Il : starting value for Ill low risk : numeric
#' @param Hh : starting value for Hospitalized high risk : numeric
#' @param Hl : starting value for Hospitalized low risk : numeric
#' @param Rh : starting value for Recovered high risk : numeric
#' @param Rl : starting value for Recovered low risk : numeric
#' @param Dh : starting value for Deceased high risk : numeric
#' @param Dl : starting value for Deceased low risk : numeric
#' Values for model parameters : numeric 
#' @param nu_Sh_Ph : fraction symptomatic: to susceptible high risk from presymptomatic high risk : numeric
#' @param bP_Sh_Ph : transmission by presymptomatis: to susceptible high risk from presymptomatic high risk : numeric
#' @param nu_Sh_Pl : fraction symptomatic: to susceptible high risk from presymptomatic low risk : numeric
#' @param bP_Sh_Pl : transmission by presymptomatis: to susceptible high risk from presymptomatic low risk : numeric
#' @param nu_Sh_Ah : fraction symptomatic: to susceptible high risk from asymptomatic high risk : numeric
#' @param bA_Sh_Ah : transmission by asymptomatic: to susceptible high risk from asymptomatic high risk : numeric
#' @param nu_Sh_Al : fraction symptomatic: to susceptible high risk from asymptomatic low risk : numeric
#' @param bA_Sh_Al : transmission by asymptomatic: to susceptible high risk from asymptomatic low risk : numeric
#' @param nu_Sh_Ih : fraction symptomatic: to susceptible high risk from ill high risk : numeric
#' @param bI_Sh_Ih : transmission by ill: to susceptible high risk from ill high risk : numeric
#' @param nu_Sh_Il : fraction symptomatic: to susceptible high risk from ill low risk : numeric
#' @param bI_Sh_Il : transmission by ill: to susceptible high risk from ill low risk : numeric
#' @param nu_Sl_Ph : fraction symptomatic: to susceptible low risk from presymptomatic high risk : numeric
#' @param bP_Sl_Ph : transmission by presymptomatis: to susceptible low risk from presymptomatic high risk : numeric
#' @param nu_Sl_Pl : fraction symptomatic: to susceptible low risk from presymptomatic low risk : numeric
#' @param bP_Sl_Pl : transmission by presymptomatis: to susceptible low risk from presymptomatic low risk : numeric
#' @param nu_Sl_Ah : fraction symptomatic: to susceptible low risk from asymptomatic high risk : numeric
#' @param bA_Sl_Ah : transmission by asymptomatic: to susceptible low risk from asymptomatic high risk : numeric
#' @param nu_Sl_Al : fraction symptomatic: to susceptible low risk from asymptomatic low risk : numeric
#' @param bA_Sl_Al : transmission by asymptomatic: to susceptible low risk from asymptomatic low risk : numeric
#' @param nu_Sl_Ih : fraction symptomatic: to susceptible low risk from ill high risk : numeric
#' @param bI_Sl_Ih : transmission by ill: to susceptible low risk from ill high risk : numeric
#' @param nu_Sl_Il : fraction symptomatic: to susceptible low risk from ill low risk : numeric
#' @param bI_Sl_Il : transmission by ill: to susceptible low risk from ill low risk : numeric
#' @param sigma_Ph : progression to symptomatic: presymptomatic high risk : numeric
#' @param sigma_Pl : progression to symptomatic: presymptomatic low risk : numeric
#' @param gammaA_Ah : recovery of asymptomatic: asymptomatic high risk : numeric
#' @param gammaA_Al : recovery of asymptomatic: asymptomatic low risk : numeric
#' @param phi_Ih : fraction of symptomatics hospitalized: ill high risk : numeric
#' @param gammaI_Ih : leaving the symptomatic class: ill high risk : numeric
#' @param phi_Il : fraction of symptomatics hospitalized: ill low risk : numeric
#' @param gammaI_Il : leaving the symptomatic class: ill low risk : numeric
#' @param rho_Hh : fraction of hospitalized deceased: hospitalized high risk : numeric
#' @param gammaH_Hh : leaving the hospitalized class: hospitalized high risk : numeric
#' @param rho_Hl : fraction of hospitalized deceased: hospitalized low risk : numeric
#' @param gammaH_Hl : leaving the hospitalized class: hospitalized low risk : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Coronavirus_vaccine_model_v2_risk_ode() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Coronavirus_vaccine_model_v2_risk_ode(Sh = 2000,Sl = 2000,Ph = 2,Pl = 2,Ah = 2,Al = 2,Ih = 2,Il = 2,Hh = 0,Hl = 0,Rh = 0,Rl = 0,Dh = 0,Dl = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'Sh'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of Sh: ',max(result$ts[,'Sh']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: COVAMOD consortium
#' @section Model creation date: 18534
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-09-30
#' @export 
 
simulate_Coronavirus_vaccine_model_v2_risk_ode <- function(Sh = 1000, Sl = 1000, Ph = 1, Pl = 1, Ah = 1, Al = 1, Ih = 1, Il = 1, Hh = 0, Hl = 0, Rh = 0, Rl = 0, Dh = 0, Dl = 0, nu_Sh_Ph = 0.3, bP_Sh_Ph = 0.001, nu_Sh_Pl = 0.3, bP_Sh_Pl = 0.001, nu_Sh_Ah = 0.3, bA_Sh_Ah = 5e-04, nu_Sh_Al = 0.3, bA_Sh_Al = 5e-04, nu_Sh_Ih = 0.3, bI_Sh_Ih = 0.001, nu_Sh_Il = 0.3, bI_Sh_Il = 0.001, nu_Sl_Ph = 0.3, bP_Sl_Ph = 0.001, nu_Sl_Pl = 0.3, bP_Sl_Pl = 0.001, nu_Sl_Ah = 0.3, bA_Sl_Ah = 5e-04, nu_Sl_Al = 0.3, bA_Sl_Al = 5e-04, nu_Sl_Ih = 0.3, bI_Sl_Ih = 0.001, nu_Sl_Il = 0.3, bI_Sl_Il = 0.001, sigma_Ph = 0.2, sigma_Pl = 0.2, gammaA_Ah = 0.125, gammaA_Al = 0.125, phi_Ih = 0.05, gammaI_Ih = 0.1, phi_Il = 0.05, gammaI_Il = 0.1, rho_Hh = 0.01, gammaH_Hh = 0.2, rho_Hl = 0.01, gammaH_Hl = 0.2, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  ############################## 
  #Block of ODE equations for deSolve 
  ############################## 
  Coronavirus_vaccine_model_v2_risk_ode_fct <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible high risk : infection by presymptomatic leading to symptomatic infections, high risk : infection by presymptomatic leading to symptomatic infections, high risk : infection by presymptomatic leading to asymptomatic infections, high risk : infection by presymptomatic leading to asymptomatic infections, high risk : infection by asymptomatic leading to symptomatic infections, high risk : infection by asymptomatic leading to symptomatic infections, high risk : infection by asymptomatic leading to asymptomatic infections, high risk : infection by asymptomatic leading to asymptomatic infections, high risk : infection by symptomatic leading to symptomatic infections, high risk : infection by symptomatic leading to symptomatic infections, high risk : infection by symptomatic leading to asymptomatic infections, high risk : infection by symptomatic leading to asymptomatic infections, high risk :
    dSh_mb = -nu_Sh_Ph*bP_Sh_Ph*Sh*Ph -nu_Sh_Pl*bP_Sh_Pl*Sh*Pl -(1-nu_Sh_Ph)*bP_Sh_Ph*Sh*Ph -(1-nu_Sh_Pl)*bP_Sh_Pl*Sh*Pl -nu_Sh_Ah*bA_Sh_Ah*Sh*Ah -nu_Sh_Al*bA_Sh_Al*Sh*Al -(1-nu_Sh_Ah)*bA_Sh_Ah*Sh*Ah -(1-nu_Sh_Al)*bA_Sh_Al*Sh*Al -nu_Sh_Ih*bI_Sh_Ih*Sh*Ih -nu_Sh_Il*bI_Sh_Il*Sh*Il -(1-nu_Sh_Ih)*bI_Sh_Ih*Sh*Ih -(1-nu_Sh_Il)*bI_Sh_Il*Sh*Il
    #Susceptible low risk : infection by presymptomatic leading to symptomatic infections, low risk : infection by presymptomatic leading to symptomatic infections, low risk : infection by presymptomatic leading to asymptomatic infections, low risk : infection by presymptomatic leading to asymptomatic infections, low risk : infection by asymptomatic leading to symptomatic infections, low risk : infection by asymptomatic leading to symptomatic infections, low risk : infection by asymptomatic leading to asymptomatic infections, low risk : infection by asymptomatic leading to asymptomatic infections, low risk : infection by symptomatic leading to symptomatic infections, low risk : infection by symptomatic leading to symptomatic infections, low risk : infection by symptomatic leading to asymptomatic infections, low risk : infection by symptomatic leading to asymptomatic infections, low risk :
    dSl_mb = -nu_Sl_Ph*bP_Sl_Ph*Sl*Ph -nu_Sl_Pl*bP_Sl_Pl*Sl*Pl -(1-nu_Sl_Ph)*bP_Sl_Ph*Sl*Ph -(1-nu_Sl_Pl)*bP_Sl_Pl*Sl*Pl -nu_Sl_Ah*bA_Sl_Ah*Sl*Ah -nu_Sl_Al*bA_Sl_Al*Sl*Al -(1-nu_Sl_Ah)*bA_Sl_Ah*Sl*Ah -(1-nu_Sl_Al)*bA_Sl_Al*Sl*Al -nu_Sl_Ih*bI_Sl_Ih*Sl*Ih -nu_Sl_Il*bI_Sl_Il*Sl*Il -(1-nu_Sl_Ih)*bI_Sl_Ih*Sl*Ih -(1-nu_Sl_Il)*bI_Sl_Il*Sl*Il
    #Presymptomatic high risk : infection by presymptomatic, high risk : infection by presymptomatic, high risk : infection by ill, high risk : infection by ill, high risk : infection by asymptomatic, high risk : infection by asymptomatic, high risk : progression to symptoms, high risk : progression to symptoms, high risk :
    dPh_mb = +nu_Sh_Ph*bP_Sh_Ph*Sh*Ph +nu_Sh_Pl*bP_Sh_Pl*Sh*Pl +nu_Sh_Ah*bA_Sh_Ah*Sh*Ah +nu_Sh_Al*bA_Sh_Al*Sh*Al +nu_Sh_Ih*bI_Sh_Ih*Sh*Ih +nu_Sh_Il*bI_Sh_Il*Sh*Il -sigma_Ph*Ph
    #Presymptomatic low risk : infection by presymptomatic, low risk : infection by presymptomatic, low risk : infection by ill, low risk : infection by ill, low risk : infection by asymptomatic, low risk : infection by asymptomatic, low risk : progression to symptoms, low risk : progression to symptoms, low risk :
    dPl_mb = +nu_Sl_Ph*bP_Sl_Ph*Sl*Ph +nu_Sl_Pl*bP_Sl_Pl*Sl*Pl +nu_Sl_Ah*bA_Sl_Ah*Sl*Ah +nu_Sl_Al*bA_Sl_Al*Sl*Al +nu_Sl_Ih*bI_Sl_Ih*Sl*Ih +nu_Sl_Il*bI_Sl_Il*Sl*Il -sigma_Pl*Pl
    #Asymptomatic high risk : infection by presymptomatic, high risk : infection by presymptomatic, high risk : infection by ill, high risk : infection by ill, high risk : infection by asymptomatic, high risk : infection by asymptomatic, high risk : recovery, high risk : recovery, high risk :
    dAh_mb = +(1-nu_Sh_Ph)*bP_Sh_Ph*Sh*Ph +(1-nu_Sh_Pl)*bP_Sh_Pl*Sh*Pl +(1-nu_Sh_Ah)*bA_Sh_Ah*Sh*Ah +(1-nu_Sh_Al)*bA_Sh_Al*Sh*Al +(1-nu_Sh_Ih)*bI_Sh_Ih*Sh*Ih +(1-nu_Sh_Il)*bI_Sh_Il*Sh*Il -gammaA_Ah*Ah
    #Asymptomatic low risk : infection by presymptomatic, low risk : infection by presymptomatic, low risk : infection by ill, low risk : infection by ill, low risk : infection by asymptomatic, low risk : infection by asymptomatic, low risk : recovery, low risk : recovery, low risk :
    dAl_mb = +(1-nu_Sl_Ph)*bP_Sl_Ph*Sl*Ph +(1-nu_Sl_Pl)*bP_Sl_Pl*Sl*Pl +(1-nu_Sl_Ah)*bA_Sl_Ah*Sl*Ah +(1-nu_Sl_Al)*bA_Sl_Al*Sl*Al +(1-nu_Sl_Ih)*bI_Sl_Ih*Sl*Ih +(1-nu_Sl_Il)*bI_Sl_Il*Sl*Il -gammaA_Al*Al
    #Ill high risk : progression to symptoms, high risk : progression to symptoms, high risk : progression to hospitalization, high risk : progression to hospitalization, high risk : progression to recovery, high risk : progression to recovery, high risk :
    dIh_mb = +sigma_Ph*Ph -phi_Ih*gammaI_Ih*Ih -(1-phi_Ih)*gammaI_Ih*Ih
    #Ill low risk : progression to symptoms, low risk : progression to symptoms, low risk : progression to hospitalization, low risk : progression to hospitalization, low risk : progression to recovery, low risk : progression to recovery, low risk :
    dIl_mb = +sigma_Pl*Pl -phi_Il*gammaI_Il*Il -(1-phi_Il)*gammaI_Il*Il
    #Hospitalized high risk : progression to hospitalization, high risk : progression to hospitalization, high risk : progression to death, high risk : progression to death, high risk : progression to recovery, high risk : progression to recovery, high risk :
    dHh_mb = +phi_Ih*gammaI_Ih*Ih -rho_Hh*gammaH_Hh*Hh -(1-rho_Hh)*gammaH_Hh*Hh
    #Hospitalized low risk : progression to hospitalization, low risk : progression to hospitalization, low risk : progression to death, low risk : progression to death, low risk : progression to recovery, low risk : progression to recovery, low risk :
    dHl_mb = +phi_Il*gammaI_Il*Il -rho_Hl*gammaH_Hl*Hl -(1-rho_Hl)*gammaH_Hl*Hl
    #Recovered high risk : recovery of asymptomatics, high risk : recovery of asymptomatics, high risk : recovery of ill, high risk : recovery of ill, high risk : recovery of hospitalized, high risk : recovery of hospitalized, high risk :
    dRh_mb = +gammaA_Ah*Ah +(1-phi_Ih)*gammaI_Ih*Ih +(1-rho_Hh)*gammaH_Hh*Hh
    #Recovered low risk : recovery of asymptomatics, low risk : recovery of asymptomatics, low risk : recovery of ill, low risk : recovery of ill, low risk : recovery of hospitalized, low risk : recovery of hospitalized, low risk :
    dRl_mb = +gammaA_Al*Al +(1-phi_Il)*gammaI_Il*Il +(1-rho_Hl)*gammaH_Hl*Hl
    #Deceased high risk : death, high risk : death, high risk :
    dDh_mb = +rho_Hh*gammaH_Hh*Hh
    #Deceased low risk : death, low risk : death, low risk :
    dDl_mb = +rho_Hl*gammaH_Hl*Hl
    #EndODES
    list(c(dSh_mb,dSl_mb,dPh_mb,dPl_mb,dAh_mb,dAl_mb,dIh_mb,dIl_mb,dHh_mb,dHl_mb,dRh_mb,dRl_mb,dDh_mb,dDl_mb)) 
  } ) } #close with statement, end ODE code block 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec_mb = c(Sh = Sh, Sl = Sl, Ph = Ph, Pl = Pl, Ah = Ah, Al = Al, Ih = Ih, Il = Il, Hh = Hh, Hl = Hl, Rh = Rh, Rl = Rl, Dh = Dh, Dl = Dl) 
  parvec_mb = c(nu_Sh_Ph = nu_Sh_Ph, bP_Sh_Ph = bP_Sh_Ph, nu_Sh_Pl = nu_Sh_Pl, bP_Sh_Pl = bP_Sh_Pl, nu_Sh_Ah = nu_Sh_Ah, bA_Sh_Ah = bA_Sh_Ah, nu_Sh_Al = nu_Sh_Al, bA_Sh_Al = bA_Sh_Al, nu_Sh_Ih = nu_Sh_Ih, bI_Sh_Ih = bI_Sh_Ih, nu_Sh_Il = nu_Sh_Il, bI_Sh_Il = bI_Sh_Il, nu_Sl_Ph = nu_Sl_Ph, bP_Sl_Ph = bP_Sl_Ph, nu_Sl_Pl = nu_Sl_Pl, bP_Sl_Pl = bP_Sl_Pl, nu_Sl_Ah = nu_Sl_Ah, bA_Sl_Ah = bA_Sl_Ah, nu_Sl_Al = nu_Sl_Al, bA_Sl_Al = bA_Sl_Al, nu_Sl_Ih = nu_Sl_Ih, bI_Sl_Ih = bI_Sl_Ih, nu_Sl_Il = nu_Sl_Il, bI_Sl_Il = bI_Sl_Il, sigma_Ph = sigma_Ph, sigma_Pl = sigma_Pl, gammaA_Ah = gammaA_Ah, gammaA_Al = gammaA_Al, phi_Ih = phi_Ih, gammaI_Ih = gammaI_Ih, phi_Il = phi_Il, gammaI_Il = gammaI_Il, rho_Hh = rho_Hh, gammaH_Hh = gammaH_Hh, rho_Hl = rho_Hl, gammaH_Hl = gammaH_Hl) 
  timevec_mb = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout = deSolve::ode(y = varvec_mb, parms = parvec_mb, times = timevec_mb,  func = Coronavirus_vaccine_model_v2_risk_ode_fct, rtol = 1e-12, atol = 1e-12) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
} 
