#' SIR model
#' 
#' A basic SIR model with 3 compartments and infection and recovery processes
#' 
#' @details The model includes susceptible, infected, and recovered compartments. The two processes that are modeled are infection and recovery.
#' @param S starting value for Susceptible
#' @param I starting value for Infected
#' @param R starting value for Recovered
#' } 
#' @param pars vector of values for model parameters: 
#' \itemize{ 
#' @param b infection rate
#' @param g recovery rate
#' } 
#' @param times vector of values for model times: 
#' \itemize{ 
#' @param tstart Start time of simulation
#' @param tfinal Final time of simulation
#' @param dt Time step
#' } 
#' @param rngseed random number seed for simulator 
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element 
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_SIR_model_stochastic() 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2018-12-03
#' @section Code Author: generated by the \code{generate_stochastic} function 
#' @section Code creation date: 2019-01-14
#' @export 
 
simulate_SIR_model_stochastic <- function(vars = c(S = 1000, I = 1, R = 0), pars = c(b = 0.002, g = 1), times = c(tstart = 0, tfinal = 100, dt = 0.1) , rngseed = 123) 
 { 
  #Block of ODE equations for adaptivetau 
  SIR_model_ode <- function(y, parms, t) 
  {
    with(as.list(c(y,parms)),   
     { 
       #specify each rate/transition/reaction that can happen in the system 
     rates = c(b*S*I, g*I)
     return(rates) 
      }
	 	)   
   } # end function specifying rates used by adaptive tau 

   #specify for each reaction/rate/transition how the different variables change 
  #needs to be in exactly the same order as the rates listed in the rate function 
   transitions = list(c(S = -1,I = +1), 
 	 	 				c(R = +1,I = -1))

 set.seed(rngseed) #set random number seed for reproducibility 
  #this line runs the simulation using the SSA algorithm in the adaptivetau package 
  odeout = adaptivetau::ssa.adaptivetau(init.values = vars, transitions = transitions,
                	 	 	 rateFunc = SIR_model_ode, params = pars, tf = times[2]) 
  result <- list() 
 
  result$ts <- as.data.frame(odeout) 
 
  return(result) 
 
} 
