#' Drug Resistance Evolution
#' 
#' @description An SIR-type model that includes drug treatment and resistance.
#' 
#' @details The model includes susceptible, infected untreated, treated and resistant, and recovered compartments. The processes which are modeled are infection, treatment, resistance generation and recovery.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of discrete time equations using a for loop. 
 
#' The following R packages need to be loaded for the function to work: none 
#' 
#' @param S : starting value for Susceptible : numeric
#' @param Iu : starting value for Infected Untreated : numeric
#' @param It : starting value for Infected Treated : numeric
#' @param Ir : starting value for Infected Resistant : numeric
#' @param R : starting value for Recovered : numeric
#' @param bu : untreated infection rate : numeric
#' @param bt : treated infection rate : numeric
#' @param br : resistant infection rate : numeric
#' @param gu : untreated recovery rate : numeric
#' @param gt : treated recovery rate : numeric
#' @param gr : resistant recovery rate : numeric
#' @param f : fraction treated : numeric
#' @param cu : resistance emergence untreated : numeric
#' @param ct : resistance emergence treated : numeric
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Drug_Resistance_Evolution_discrete() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Drug_Resistance_Evolution_discrete(S = 2000,Iu = 2,It = 2,Ir = 2,R = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2020-10-05
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2021-07-19
#' @export 
 
simulate_Drug_Resistance_Evolution_discrete <- function(S = 1000, Iu = 1, It = 1, Ir = 1, R = 0, bu = 0.002, bt = 0.002, br = 0.002, gu = 1, gt = 1, gr = 1, f = 0, cu = 0, ct = 0, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  #Function that encodes simulation loop 
  Drug_Resistance_Evolution_fct <- function(vars, pars, times) 
  {
    with( as.list(c(vars,pars)), {  
      ts = data.frame(cbind(times, matrix(0,nrow=length(times),ncol=length(vars)))) 
      colnames(ts) = c('time','S','Iu','It','Ir','R') 
      ct=1 #a counter to index array 
      for (t in times) 
      {
        ts[ct,] = c(t,S,Iu,It,Ir,R) 
        Sp = S + dt*(-S*(1-f)*bu*(1-cu)*Iu -S*(1-f)*bt*(1-ct)*It -S*f*bu*(1-cu)*Iu -S*f*bt*(1-ct)*It -S*bu*cu*Iu -S*bt*ct*It -S*br*Ir) 
        Iup = Iu + dt*(+S*(1-f)*bu*(1-cu)*Iu +S*(1-f)*bt*(1-ct)*It -gu*Iu) 
        Itp = It + dt*(+S*f*bu*(1-cu)*Iu +S*f*bt*(1-ct)*It -gt*It) 
        Irp = Ir + dt*(+S*bu*cu*Iu +S*bt*ct*It +S*br*Ir -gr*Ir) 
        Rp = R + dt*(+gu*Iu +gt*It +gr*Ir) 
        S = Sp 
        Iu = Iup 
        It = Itp 
        Ir = Irp 
        R = Rp 
        ct = ct + 1 
      } #finish loop 
      return(ts) 
    }) #close with statement 
 } #end function encoding loop 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec = c(S = S, Iu = Iu, It = It, Ir = Ir, R = R) 
  parvec = c(bu = bu, bt = bt, br = br, gu = gu, gt = gt, gr = gr, f = f, cu = cu, ct = ct) 
  timevec = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout <- Drug_Resistance_Evolution_fct(vars = varvec, pars = parvec, times = timevec) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- simout 
  return(result) 
} 
