#' Cholera model
#' 
#' A Cholera model based on Codeco 2001 BMC ID
#' 
#' @description USER CAN ADD MORE DETAILS HERE 
#' @param S starting value for Susceptible
#' @param I starting value for Infected
#' @param B starting value for Baceria
#' @param h population size
#' @param n birth rate
#' @param a infection rate
#' @param k 50% infection rate
#' @param r recovery rate
#' @param nbmb effective bacteria growth rate
#' @param e bacteria shedding rate
#' @param tstart Start time of simulation
#' @param tfinal Final time of simulation
#' @param dt Time step
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element ts. 
#' The ts dataframe has one column per compartment/variable. The first column is time.   
#' @details USER CAN ADD MORE DETAILS HERE  
#' @examples  
#' # To run the simulation with default parameters just call the function:  
#' result <- Cholera_model_desolve() 
#' @modelauthor Andreas Handel
#' @modeldate 2018-09-05
#' @functionauthor generated by convert_to_desolve function 
#' @fuctiondate 2018-09-05
#' @export 
 
Cholera_model_desolve <- function(vars = c(S = 10000, I = 1, B = 0), pars = c(h = 10000, n = 1e-04, a = 1, k = 1e+06, r = 0.2, nbmb = -0.33, e = 10), time = c(tstart = 0, tfinal = 500, dt = 0.1) ) 
{ 
  #Block of ODE equations for deSolve 
  Cholera_model_ode <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible : births : deaths : infection of susceptibles :
    dS = +n*h -n*S -a*B/(k+B)*S
    #Infected : infection of susceptibles : recovery of infected :
    dI = +a*B/(k+B)*S -r*I
    #Baceria : bacteria growth : bacteria decay : bacteria shedding :
    dB = +B*nbmb +e*I
    #EndODES
    list(c(dS,dI,dB)) 
  } ) } #close with statement, end ODE code block 
 
  #Main function code block 
  times=seq(time[1],time[2],by=time[3]) 
  odeout = deSolve::ode(y = vars, parms= pars, times = times,  func = Cholera_model_ode) 
  result <- list() 
  result$ts <- as.data.frame(odeout) 
  return(result) 
} 
