#' Coronavirus vaccine model
#' 
#' @description A model with 7 compartments
#' 
#' @details The model includes susceptible, presymptomatic, asymptomatic, infected/symptomatic/ill, recovered, hospitalized, and deceased compartments. The processes that are modeled are infection, progression to infectiousness, recovery, and progression to hospitalization and death. Immunity is permanent. Demographics through natural births and deaths are not included.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of ordinary differential equations using the deSolve package. 
#' The following R packages need to be loaded for the function to work: deSolve. 
#' 
#' Starting conditions for model variables 
#' @param S : starting value for Susceptible : numeric
#' @param P : starting value for Presymptomatic : numeric
#' @param A : starting value for Asymptomatic : numeric
#' @param I : starting value for Ill : numeric
#' @param R : starting value for Recovered : numeric
#' @param H : starting value for Hospitalized : numeric
#' @param D : starting value for Deceased : numeric
#' Values for model parameters : numeric 
#' @param thetaP : infectiousness of presymptomatics : numeric
#' @param thetaI : infectiousness of ill : numeric
#' @param thetaA : infectiousness by asymptomatic : numeric
#' @param nu : fraction symptomatic : numeric
#' @param sigma : progression to symptomatic : numeric
#' @param gammaA : recovery of asymptomatic : numeric
#' @param gammaI : leaving the symptomatic class : numeric
#' @param gammaH : leaving the hospitalized class : numeric
#' @param phi : fraction of symptomatics hospitalized : numeric
#' @param rho : fraction of hospitalized deceased : numeric
#' @param n : population size : numeric
#' @param nuInverse : fraction asymptomatic : numeric
#' @param phiInverse : fraction of symptomatics NOT hospitalized : numeric
#' @param rhoInverse : fraction of hospitalized NOT deceased : numeric
#' @param c : contact matrix : numeric
#' @param alpha : susceptibility of susceptibles : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Coronavirus_vaccine_model_ode() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Coronavirus_vaccine_model_ode(S = 2000,P = 2,A = 2,I = 2,R = 0,H = 0,D = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: COVAMOD consortium
#' @section Model creation date: 2020-09-14
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-09-14
#' @export 
 
simulate_Coronavirus_vaccine_model_ode <- function(S = 1000, P = 1, A = 1, I = 1, R = 0, H = 0, D = 0, thetaP = 0.001, thetaI = 0.001, thetaA = 5e-04, nu = 0.3, sigma = 0.2, gammaA = 0.125, gammaI = 0.1, gammaH = 0.2, phi = 0.05, rho = 0.01, n = 1003, nuInverse = 0.7, phiInverse = 0.95, rhoInverse = 0.99, c = 1, alpha = 1, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  ############################## 
  #Block of ODE equations for deSolve 
  ############################## 
  Coronavirus_vaccine_model_ode_fct <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible : infection by presymptomatic : infection by ill : infection by asymptomatic :
    dS_mb = -(S/n)*c*alpha*thetaP*P -(S/n)*c*alpha*thetaI*I -(S/n)*c*alpha*thetaA*A
    #Presymptomatic : infection by presymptomatic : infection by ill : infection by asymptomatic : progression to symptoms :
    dP_mb = +nu*(S/n)*c*alpha*thetaP*P +nu*(S/n)*c*alpha*thetaI*I +nu*(S/n)*c*alpha*thetaA*A -sigma*P
    #Asymptomatic : infection by presymptomatic : infection by ill : infection by asymptomatic : recovery :
    dA_mb = +nuInverse*(S/n)*c*alpha*thetaP*P +nuInverse*(S/n)*c*alpha*thetaI*I +nuInverse*(S/n)*c*alpha*thetaA*A -gammaA*A
    #Ill : progression to symptoms : progression to recovery or hospitalization :
    dI_mb = +sigma*P -gammaI*I
    #Recovered : recovery of asymptomatics : recovery of ill : recovery of hospitalized :
    dR_mb = +gammaA*A +phiInverse*gammaI*I +rhoInverse*gammaH*H
    #Hospitalized : progression to hospitalization : progression to recovery or death :
    dH_mb = +phi*gammaI*I -gammaH*H
    #Deceased : death :
    dD_mb = +rho*gammaH*H
    #EndODES
    list(c(dS_mb,dP_mb,dA_mb,dI_mb,dR_mb,dH_mb,dD_mb)) 
  } ) } #close with statement, end ODE code block 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec_mb = c(S = S, P = P, A = A, I = I, R = R, H = H, D = D) 
  parvec_mb = c(thetaP = thetaP, thetaI = thetaI, thetaA = thetaA, nu = nu, sigma = sigma, gammaA = gammaA, gammaI = gammaI, gammaH = gammaH, phi = phi, rho = rho, n = n, nuInverse = nuInverse, phiInverse = phiInverse, rhoInverse = rhoInverse, c = c, alpha = alpha) 
  timevec_mb = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout = deSolve::ode(y = varvec_mb, parms = parvec_mb, times = timevec_mb,  func = Coronavirus_vaccine_model_ode_fct, rtol = 1e-12, atol = 1e-12) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
} 
