#' Complex ID Control Scenarios
#' 
#' @description The basic SIR model is expanded to include vectors.
#' 
#' @details The model includes susceptible, infected, asymptomatic, presymptomactic, pathogens, susceptible vectors, infected vectors, recovered and death compartments. The processes that are modeled are infection, recovery, birth, death, and immunity.
#' 
#' This code is was generated by the modelbuilder package R.  
#' The model is implemented as a set of stochastic equations using the adaptivetau package. 
 
#' The following R packages need to be loaded for the function to work: adpativetau 
#' 
#' Starting conditions for model variables 
#' @param S : starting value for Susceptible Host : numeric
#' @param P : starting value for Infected, Presymptomatic : numeric
#' @param A : starting value for Infected, Asymptomatic : numeric
#' @param I : starting value for Infected, Symptomatic : numeric
#' @param R : starting value for Recovered : numeric
#' @param D : starting value for Deaths : numeric
#' @param E : starting value for Pathogen in the environment : numeric
#' @param SV : starting value for Susceptible Vectors : numeric
#' @param IV : starting value for Infectious Vectors : numeric
#' Values for model parameters : numeric 
#' @param bP : Presymptomatic infection rate : numeric
#' @param bA : Asymptomatic infection rate : numeric
#' @param bI : Symptomatic infection rate : numeric
#' @param bE : Pathogen infection rate : numeric
#' @param bV : Vector infection rate : numeric
#' @param bh : Host natural infection rate : numeric
#' @param nV : Vector natural death rate : numeric
#' @param nh : Host death rate : numeric
#' @param gP : Presymptomatic recovery rate : numeric
#' @param gA : Asymptomatic recovery rate : numeric
#' @param gI : Symptomatic recovery rate : numeric
#' @param pI : Symptomatic host pathogen shed rate : numeric
#' @param pA : Asymptomatic host pathogen shed rate : numeric
#' @param c : pathogen decay rate  : numeric
#' @param eV : Susceptible vector enter system rate : numeric
#' @param eh : Susceptible host enter system rate : numeric
#' @param f : presymptomatic hosts move into the asymptomatic rate : numeric
#' @param d : host death rate due to infection : numeric
#' @param w : Loss of immunity rate : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @param rngseed : set random number seed for reproducibility : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Complex_ID_Control_Scenarios_stochastic() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Complex_ID_Control_Scenarios_stochastic(S = 2000,P = 2,A = 2,I = 2,R = 0,D = 0,E = 0,SV = 200,IV = 2) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author:  Alexis Vittengl
#' @section Model creation date: 2020-09-01
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-09-01
#' @export 
 
simulate_Complex_ID_Control_Scenarios_stochastic <- function(S = 1000, P = 1, A = 1, I = 1, R = 0, D = 0, E = 0, SV = 100, IV = 1, bP = 0.002, bA = 0.002, bI = 0.002, bE = 0.002, bV = 0.002, bh = 0.002, nV = 0.02, nh = 0.02, gP = 0.05, gA = 0.05, gI = 0.05, pI = 0.01, pA = 0.01, c = 0.03, eV = 0.2, eh = 0.2, f = 0.4, d = 0.08, w = 0.005, tstart = 0, tfinal = 100, dt = 0.1, rngseed = 123) 
{ 
  #Block of ODE equations for adaptivetau 
  Complex_ID_Control_Scenarios_fct <- function(y, parms, t) 
  {
    with(as.list(c(y,parms)),   
     { 
       #specify each rate/transition/reaction that can happen in the system 
     rates = c(bA*A*S, bE*E*S, bh*I*SV, bI*I*S, bP*P*S, d*gI*I, f*gP*P, gA*A, gI*I, gP*P, w*R, bV*IV*S, c*E, eh, eV, nh*A, nh*I, nh*P, nh*R, nh*S, nV*IV, nV*SV, pA*A, pI*I)
     return(rates) 
      }
	 	)   
  } # end function specifying rates used by adaptive tau 

   #specify for each reaction/rate/transition how the different variables change 
  #needs to be in exactly the same order as the rates listed in the rate function 
  transitions = list(c(P = +1,S = -1), 
 	 	 				c(P = +1,S = -1), 
 	 	 				c(IV = +1,SV = -1), 
 	 	 				c(P = +1,S = -1), 
 	 	 				c(P = +1,S = -1), 
 	 	 				c(D = +1,R = -1), 
 	 	 				c(A = +1,I = -1), 
 	 	 				c(R = +1,A = -1), 
 	 	 				c(R = +1,I = -1), 
 	 	 				c(I = +1,P = -1), 
 	 	 				c(R = -1,S = +1), 
 	 	 				c(P = +1), 
 	 	 				c(E = -1), 
 	 	 				c(S = +1), 
 	 	 				c(SV = +1), 
 	 	 				c(A = -1), 
 	 	 				c(I = -1), 
 	 	 				c(P = -1), 
 	 	 				c(R = -1), 
 	 	 				c(S = -1), 
 	 	 				c(IV = -1), 
 	 	 				c(SV = -1), 
 	 	 				c(E = +1), 
 	 	 				c(E = +1)) 
 
  ############################## 
  #Main function code block 
  ############################## 
  set.seed(rngseed) #set random number seed for reproducibility 
  #Creating named vectors 
  varvec = c(S = S, P = P, A = A, I = I, R = R, D = D, E = E, SV = SV, IV = IV) 
  parvec = c(bP = bP, bA = bA, bI = bI, bE = bE, bV = bV, bh = bh, nV = nV, nh = nh, gP = gP, gA = gA, gI = gI, pI = pI, pA = pA, c = c, eV = eV, eh = eh, f = f, d = d, w = w) 
  #Running the model 
  simout = adaptivetau::ssa.adaptivetau(init.values = varvec, transitions = transitions,
                  	 	 	 rateFunc = Complex_ID_Control_Scenarios_fct, params = parvec, tf = tfinal) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
 }