#' Basics of ID Control
#' 
#' @description A reproductive number model built from expanding the basic SIR model. 
#' 
#' @details The model includes susceptible, infected, and recovered compartments. The processes that are modeled are infection, recovery, birth, death, vaccine and immunity.
#' 
#' This code is was generated by the modelbuilder package R.  
#' The model is implemented as a set of ordinary differential equations using the deSolve package. 
#' The following R packages need to be loaded for the function to work: deSolve. 
#' 
#' Starting conditions for model variables 
#' @param S : starting value for Susceptible : numeric
#' @param I : starting value for Infected : numeric
#' @param R : starting value for Recovered : numeric
#' @param Sv : starting value for susceptible population left after vaccinating : numeric
#' @param R0 : starting value for Vaccinated and Protected : numeric
#' Values for model parameters : numeric 
#' @param b : infection rate : numeric
#' @param g : recovery rate : numeric
#' @param m : birth rate : numeric
#' @param n : death rate : numeric
#' @param w : lose immunity : numeric
#' @param e : vaccine efficacy : numeric
#' @param f : fraction vaccinated : numeric
#' @param s : Initial Susceptible  : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Basics_of_ID_Control_ode() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Basics_of_ID_Control_ode(S = 2000,I = 2,R = 0,Sv = 200,R0 = 200) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Alexis Vittengl 
#' @section Model creation date: 2020-06-26
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-06-26
#' @export 
 
simulate_Basics_of_ID_Control_ode <- function(S = 1000, I = 1, R = 0, Sv = 100, R0 = 100, b = 0.002, g = 1, m = 1.2, n = 0.05, w = 0.02, e = 0.68, f = 0.8, s = 1000, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  ############################## 
  #Block of ODE equations for deSolve 
  ############################## 
  Basics_of_ID_Control_ode_fct <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible : infection of susceptibles : births : deaths of susceptibles : loss of immunity of recovered :
    dS_mb = -b*S*I +m -n*S +w*R
    #Infected : infection of susceptibles : recovery of infected : deaths of infected :
    dI_mb = +b*S*I -g*I -n*I
    #Recovered : recovery of infected : deaths of recovered : loss of immunity of recovered :
    dR_mb = +g*I -n*R -w*R
    #susceptible population left after vaccinating : initial susceptibles : Initial removed individuals :
    dSv_mb = +s -e*f*s
    #Vaccinated and Protected : Initial removed individuals :
    dR0_mb = +e*f*s
    #EndODES
    list(c(dS_mb,dI_mb,dR_mb,dSv_mb,dR0_mb)) 
  } ) } #close with statement, end ODE code block 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec_mb = c(S = S, I = I, R = R, Sv = Sv, R0 = R0) 
  parvec_mb = c(b = b, g = g, m = m, n = n, w = w, e = e, f = f, s = s) 
  timevec_mb = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout = deSolve::ode(y = varvec_mb, parms = parvec_mb, times = timevec_mb,  func = Basics_of_ID_Control_ode_fct, rtol = 1e-12, atol = 1e-12) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
} 
