#' SEIRSd model
#' 
#' @description A SEIRS model with 4 compartments
#' 
#' @details The model includes susceptible, exposed/asymptomatic, infected/symptomatic, and recovered compartments. The processes that are modeled are infection, progression to infectiousness, recovery and waning immunity. Demographics through natural births and deaths are also included.
#' 
#' This code is was generated by the modelbuilder package R.  
#' The model is implemented as a set of discrete time equations using a for loop. 
 
#' The following R packages need to be loaded for the function to work: none 
#' 
#' Starting conditions for model variables 
#' @param S : starting value for Susceptible : numeric
#' @param E : starting value for Exposed : numeric
#' @param I : starting value for Infected and Symptomatic : numeric
#' @param R : starting value for Recovered : numeric
#' Values for model parameters : numeric 
#' @param bE : infection by exposed : numeric
#' @param bI : infection by symptomatic : numeric
#' @param gE : progression rate : numeric
#' @param gI : recovery rate : numeric
#' @param w : waning immunity : numeric
#' @param n : births : numeric
#' @param m : deaths : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_SEIRSd_model_discrete() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_SEIRSd_model_discrete(S = 2000,E = 2,I = 2,R = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2020-06-26
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-06-26
#' @export 
 
simulate_SEIRSd_model_discrete <- function(S = 1000, E = 1, I = 1, R = 0, bE = 0, bI = 0.001, gE = 1, gI = 1, w = 1, n = 0, m = 0, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  #Function that encodes simulation loop 
  SEIRSd_model_fct <- function(vars, pars, times) 
  {
    with( as.list(c(vars,pars)), {  
      ts = data.frame(cbind(times, matrix(0,nrow=length(times),ncol=length(vars)))) 
      colnames(ts) = c('time','S','E','I','R') 
      ct=1 #a counter to index array 
      for (t in times) 
      {
        ts[ct,] = c(t,S,E,I,R) 
        Sp = S + dt*(-bE*S*E -bI*S*I +w*R +n -m*S) 
        Ep = E + dt*(+bE*S*E +bI*S*I -gE*E -m*E) 
        Ip = I + dt*(+gE*E -gI*I -m*I) 
        Rp = R + dt*(+gI*I -w*R -m*R) 
        S = Sp 
        E = Ep 
        I = Ip 
        R = Rp 
        ct = ct + 1 
      } #finish loop 
      return(ts) 
    }) #close with statement 
 } #end function encoding loop 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec = c(S = S, E = E, I = I, R = R) 
  parvec = c(bE = bE, bI = bI, gE = gE, gI = gI, w = w, n = n, m = m) 
  timevec = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout <- SEIRSd_model_fct(vars = varvec, pars = parvec, times = timevec) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- simout 
  return(result) 
} 
