#' Coronavirus vaccine model v2
#' 
#' @description A model with 7 compartments
#' 
#' @details The model includes susceptible, presymptomatic, asymptomatic, infected/symptomatic/ill, recovered, hospitalized, and deceased compartments. The processes that are modeled are infection, progression to infectiousness, recovery, and progression to hospitalization and death. Immunity is permanent. Demographics through natural births and deaths are not included.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of stochastic equations using the adaptivetau package. 
 
#' The following R packages need to be loaded for the function to work: adpativetau 
#' 
#' Starting conditions for model variables 
#' @param S : starting value for Susceptible : numeric
#' @param P : starting value for Presymptomatic : numeric
#' @param A : starting value for Asymptomatic : numeric
#' @param I : starting value for Ill : numeric
#' @param H : starting value for Hospitalized : numeric
#' @param R : starting value for Recovered : numeric
#' @param D : starting value for Deceased : numeric
#' Values for model parameters : numeric 
#' @param bP : transmission by presymptomatis : numeric
#' @param bA : transmission by asymptomatic : numeric
#' @param bI : transmission by ill : numeric
#' @param nu : fraction symptomatic : numeric
#' @param sigma : progression to symptomatic : numeric
#' @param gammaA : recovery of asymptomatic : numeric
#' @param gammaI : leaving the symptomatic class : numeric
#' @param gammaH : leaving the hospitalized class : numeric
#' @param phi : fraction of symptomatics hospitalized : numeric
#' @param rho : fraction of hospitalized deceased : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @param rngseed : set random number seed for reproducibility : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Coronavirus_vaccine_model_v2_stochastic() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Coronavirus_vaccine_model_v2_stochastic(S = 2000,P = 2,A = 2,I = 2,H = 0,R = 0,D = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: COVAMOD consortium
#' @section Model creation date: 2020-09-21
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-09-21
#' @export 
 
simulate_Coronavirus_vaccine_model_v2_stochastic <- function(S = 1000, P = 1, A = 1, I = 1, H = 0, R = 0, D = 0, bP = 0.001, bA = 5e-04, bI = 0.001, nu = 0.3, sigma = 0.2, gammaA = 0.125, gammaI = 0.1, gammaH = 0.2, phi = 0.05, rho = 0.01, tstart = 0, tfinal = 100, dt = 0.1, rngseed = 123) 
{ 
  #Block of ODE equations for adaptivetau 
  Coronavirus_vaccine_model_v2_fct <- function(y, parms, t) 
  {
    with(as.list(c(y,parms)),   
     { 
       #specify each rate/transition/reaction that can happen in the system 
     rates = c((1-nu)*bA*S*A, (1-nu)*bI*S*I, (1-nu)*bP*S*P, (1-phi)*gammaI*I, (1-rho)*gammaH*H, gammaA*A, nu*bA*S*A, nu*bI*S*I, nu*bP*S*P, phi*gammaI*I, rho*gammaH*H, sigma*P)
     return(rates) 
      }
	 	)   
  } # end function specifying rates used by adaptive tau 

   #specify for each reaction/rate/transition how the different variables change 
  #needs to be in exactly the same order as the rates listed in the rate function 
  transitions = list(c(A = +1,S = -1), 
 	 	 				c(A = +1,S = -1), 
 	 	 				c(A = +1,S = -1), 
 	 	 				c(R = +1,I = -1), 
 	 	 				c(H = -1,R = +1), 
 	 	 				c(R = +1,A = -1), 
 	 	 				c(P = +1,S = -1), 
 	 	 				c(P = +1,S = -1), 
 	 	 				c(S = -1,P = +1), 
 	 	 				c(H = +1,I = -1), 
 	 	 				c(D = +1,H = -1), 
 	 	 				c(I = +1,P = -1)) 
 
  ############################## 
  #Main function code block 
  ############################## 
  set.seed(rngseed) #set random number seed for reproducibility 
  #Creating named vectors 
  varvec = c(S = S, P = P, A = A, I = I, H = H, R = R, D = D) 
  parvec = c(bP = bP, bA = bA, bI = bI, nu = nu, sigma = sigma, gammaA = gammaA, gammaI = gammaI, gammaH = gammaH, phi = phi, rho = rho) 
  #Running the model 
  simout = adaptivetau::ssa.adaptivetau(init.values = varvec, transitions = transitions,
                  	 	 	 rateFunc = Coronavirus_vaccine_model_v2_fct, params = parvec, tf = tfinal) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
 }