#' Control of different populations
#' 
#' @description This model expands the basic SIR model to include control measures.
#' 
#' @details This model includes parameters and variables such as deaths and control measures. The model includes susceptible, infected, recovered, and dead compartments. The processes that are modeled are infection, recovery, birth, death, control measures and immunity.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of stochastic equations using the adaptivetau package. 
 
#' The following R packages need to be loaded for the function to work: adpativetau 
#' 
#' @param Sc : starting value for Susceptible Children : numeric
#' @param Ic : starting value for Infected Children : numeric
#' @param Rc : starting value for Recovered Children : numeric
#' @param Dc : starting value for Dead Children : numeric
#' @param Sa : starting value for Susceptible Adults : numeric
#' @param Ia : starting value for Infected Adults : numeric
#' @param Ra : starting value for Recovered Adults : numeric
#' @param Da : starting value for Dead Adults : numeric
#' @param Se : starting value for Susceptible Elderly : numeric
#' @param Ie : starting value for Infected Elderly : numeric
#' @param Re : starting value for Recovered Elderly : numeric
#' @param De : starting value for Dead Elderly : numeric
#' @param bcc : Child to Child infection rate : numeric
#' @param bac : Adult to Child infection rate : numeric
#' @param bec : Elderly to Child infection rate : numeric
#' @param wc : Child loss of immunity rate : numeric
#' @param gc : Child recovery rate : numeric
#' @param mc : Child death rate : numeric
#' @param f1 : Child control measure : numeric
#' @param bca : Child to Adult infection rate : numeric
#' @param baa : Adult to Adult infection rate : numeric
#' @param bea : Elderly to Adult infection Rate : numeric
#' @param wa : Adult loss of immunity : numeric
#' @param ga : Adult recovery rate : numeric
#' @param ma : Adult death rate : numeric
#' @param f2 : Adult control measure : numeric
#' @param bce : Child to Elderly infection rate : numeric
#' @param bae : Adult to Elderly infection rate : numeric
#' @param bee : Elderly to Elderly infection rate : numeric
#' @param we : Elderly loss of immunity : numeric
#' @param ge : Elderly recovery rate : numeric
#' @param me : Elderly death rate : numeric
#' @param f3 : Elderly control measure : numeric
#' @param rngseed : set random number seed for reproducibility : numeric
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Control_of_different_populations_stochastic() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Control_of_different_populations_stochastic(Sc = 200,Ic = 2,Rc = 0,Dc = 0,Sa = 200,Ia = 2,Ra = 0,Da = 0,Se = 200,Ie = 2,Re = 0,De = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'Sc'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of Sc: ',max(result$ts[,'Sc']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Alexis Vittengl
#' @section Model creation date: 2020-09-01
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2021-02-16
#' @export 
 
simulate_Control_of_different_populations_stochastic <- function(Sc = 100, Ic = 1, Rc = 0, Dc = 0, Sa = 100, Ia = 1, Ra = 0, Da = 0, Se = 100, Ie = 1, Re = 0, De = 0, bcc = 0.001, bac = 0.001, bec = 0.001, wc = 0.01, gc = 0.06, mc = 0.2, f1 = 0.1, bca = 0.001, baa = 0.001, bea = 0.001, wa = 0.01, ga = 0.06, ma = 0.2, f2 = 0.1, bce = 0.001, bae = 0.001, bee = 0.001, we = 0.2, ge = 0.06, me = 0.02, f3 = 0.1, tstart = 0, tfinal = 100, dt = 0.1, rngseed = 123) 
{ 
  #Block of ODE equations for adaptivetau 
  Control_of_different_populations_fct <- function(y, parms, t) 
  {
    with(as.list(c(y,parms)),   
     { 
       #specify each rate/transition/reaction that can happen in the system 
     rates = c(ma*ga*Ia, ga*Ia, wa*Ra, baa*Ia*Sa*f2, bac*Ia*Sc, bac*Ia*Sc*f1, bae*Ia*Se, bae*Ia*Se*f3, bca*Ic*Sa, bca*Ic*Sa*f2, bcc*Ic*Sc, bcc*Ic*Sc*f1, bce*Ic*Se, bce*Ic*Se*f3, bea*Ie*Sa, bea*Ie*Sa*f2, bec*Ie*Sc, bec*Ie*Sc*f1, bee*Ie*Se, bee*Ie*Se*f3, gc*Ic, mc*gc*Ic, wc*Rc, baa*Ia*Sa, baa*Ia*Sa*, ge*Ie, we*Re)
     return(rates) 
      }
	 	)   
  } # end function specifying rates used by adaptive tau 

   #specify for each reaction/rate/transition how the different variables change 
  #needs to be in exactly the same order as the rates listed in the rate function 
  transitions = list(c(Da = +1,De = +1), 
 	 	 				c(Ra = -1,Re = -1), 
 	 	 				c(Ra = +1,Re = +1), 
 	 	 				c(Ia = -1,Ra = -1), 
 	 	 				c(Re = -1,Sa = +1), 
 	 	 				c(Sa = +1,Ia = -1), 
 	 	 				c(Sc = -1,Ic = +1), 
 	 	 				c(Sc = +1,Ic = -1), 
 	 	 				c(Se = -1,Ie = +1), 
 	 	 				c(Se = +1,Ie = -1), 
 	 	 				c(Sa = -1,Ia = +1), 
 	 	 				c(Sa = +1,Ia = -1), 
 	 	 				c(Sc = -1,Ic = +1), 
 	 	 				c(Sc = +1,Ic = -1), 
 	 	 				c(Se = -1,Ie = +1), 
 	 	 				c(Se = +1,Ie = -1), 
 	 	 				c(Sa = -1,Ia = +1), 
 	 	 				c(Sa = +1,Ia = -1), 
 	 	 				c(Sc = -1,Ic = +1), 
 	 	 				c(Sc = +1,Ic = -1), 
 	 	 				c(Se = -1,Ie = +1), 
 	 	 				c(Se = +1,Ie = -1), 
 	 	 				c(Rc = +1,Ic = -1), 
 	 	 				c(Sa = -1), 
 	 	 				c(Ia = +1), 
 	 	 				c(Ie = -1), 
 	 	 				c(Se = +1)) 
 
  ############################## 
  #Main function code block 
  ############################## 
  set.seed(rngseed) #set random number seed for reproducibility 
  #Creating named vectors 
  varvec = c(Sc = Sc, Ic = Ic, Rc = Rc, Dc = Dc, Sa = Sa, Ia = Ia, Ra = Ra, Da = Da, Se = Se, Ie = Ie, Re = Re, De = De) 
  parvec = c(bcc = bcc, bac = bac, bec = bec, wc = wc, gc = gc, mc = mc, f1 = f1, bca = bca, baa = baa, bea = bea, wa = wa, ga = ga, ma = ma, f2 = f2, bce = bce, bae = bae, bee = bee, we = we, ge = ge, me = me, f3 = f3) 
  #Running the model 
  simout = adaptivetau::ssa.adaptivetau(init.values = varvec, transitions = transitions,
                  	 	 	 rateFunc = Control_of_different_populations_fct, params = parvec, tf = tfinal) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
 }