#' Influenza Antibody Model
#' 
#' @description Influenza Antibody Model
#' 
#' @details Model based on Zarnitsyna et al 2016 PLoS Pathogens
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of stochastic equations using the adaptivetau package. 
 
#' The following R packages need to be loaded for the function to work: adpativetau 
#' 
#' @param Hf : starting value for free antigen : numeric
#' @param Hb : starting value for bound antigen : numeric
#' @param B : starting value for B cells : numeric
#' @param A : starting value for antibodies : numeric
#' @param k : binding rate : numeric
#' @param df : free antigen decay rate : numeric
#' @param db : bound antigen decay rate : numeric
#' @param s : B cell generation rate : numeric
#' @param del : bound antibody strength : numeric
#' @param p : saturation level : numeric
#' @param a : FIM impact  : numeric
#' @param g : antibody production rate : numeric
#' @param dA : antibody decay rate : numeric
#' @param rngseed : set random number seed for reproducibility : numeric
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Influenza_Antibody_Model_stochastic() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Influenza_Antibody_Model_stochastic(Hf = 20000,Hb = 0,B = 2,A = 2) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'Hf'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of Hf: ',max(result$ts[,'Hf']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2020-12-04
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2021-02-16
#' @export 
 
simulate_Influenza_Antibody_Model_stochastic <- function(Hf = 10000, Hb = 0, B = 1, A = 1, k = 0.01, df = 0.5, db = 0.5, s = 1, del = 0, p = 0, a = 0, g = 0.1, dA = 0.1, tstart = 0, tfinal = 100, dt = 0.1, rngseed = 123) 
{ 
  #Block of ODE equations for adaptivetau 
  Influenza_Antibody_Model_fct <- function(y, parms, t) 
  {
    with(as.list(c(y,parms)),   
     { 
       #specify each rate/transition/reaction that can happen in the system 
     rates = c(k*A*Hf, dA*A, db*Hb, df*Hf, g*B, s*B*(Hf+del*Hb)/(p+Hf+del*Hb)*(1/(1+a*Hb)))
     return(rates) 
      }
	 	)   
  } # end function specifying rates used by adaptive tau 

   #specify for each reaction/rate/transition how the different variables change 
  #needs to be in exactly the same order as the rates listed in the rate function 
  transitions = list(c(Hf = -1,Hb = +1), 
 	 	 				c(A = -1), 
 	 	 				c(Hb = -1), 
 	 	 				c(Hf = -1), 
 	 	 				c(A = +1), 
 	 	 				c(B = +1)) 
 
  ############################## 
  #Main function code block 
  ############################## 
  set.seed(rngseed) #set random number seed for reproducibility 
  #Creating named vectors 
  varvec = c(Hf = Hf, Hb = Hb, B = B, A = A) 
  parvec = c(k = k, df = df, db = db, s = s, del = del, p = p, a = a, g = g, dA = dA) 
  #Running the model 
  simout = adaptivetau::ssa.adaptivetau(init.values = varvec, transitions = transitions,
                  	 	 	 rateFunc = Influenza_Antibody_Model_fct, params = parvec, tf = tfinal) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
 }