#' Vector transmission model
#' 
#' @description A basic model with several compartments to model vector-borne transmission
#' 
#' @details The model tracks the dynamics of susceptible, infected, and recovered hosts, and susceptible and infected vectors. Infection, recovery, and waning immunity processes are implemented for hosts. Births and deaths and infection processes are implemented for vectors.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of stochastic equations using the adaptivetau package. 
 
#' The following R packages need to be loaded for the function to work: adpativetau 
#' 
#' @param Sh : starting value for Susceptible hosts : numeric
#' @param Ih : starting value for Infected hosts : numeric
#' @param Rh : starting value for Recovered hosts : numeric
#' @param Sv : starting value for Susceptible Vectors : numeric
#' @param Iv : starting value for Infected Vectors : numeric
#' @param b1 : rate at which susceptible hosts are infected by vectors : numeric
#' @param b2 : rate at which susceptible vectors are infected by hosts : numeric
#' @param g : recovery rate of hosts : numeric
#' @param w : wanning immunity rate : numeric
#' @param n : vector birth rate : numeric
#' @param m : vector death rate : numeric
#' @param rngseed : set random number seed for reproducibility : numeric
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Vector_transmission_model_stochastic() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Vector_transmission_model_stochastic(Sh = 2000,Ih = 2,Rh = 0,Sv = 2000,Iv = 2) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'Sh'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of Sh: ',max(result$ts[,'Sh']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2020-09-01
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2021-02-16
#' @export 
 
simulate_Vector_transmission_model_stochastic <- function(Sh = 1000, Ih = 1, Rh = 0, Sv = 1000, Iv = 1, b1 = 0.003, b2 = 0.003, g = 2, w = 0, n = 200, m = 0.1, tstart = 0, tfinal = 100, dt = 0.1, rngseed = 123) 
{ 
  #Block of ODE equations for adaptivetau 
  Vector_transmission_model_fct <- function(y, parms, t) 
  {
    with(as.list(c(y,parms)),   
     { 
       #specify each rate/transition/reaction that can happen in the system 
     rates = c(b1*Sh*Iv, b2*Sv*Ih, g*Ih, w*Rh, m*Iv, m*Sv, n)
     return(rates) 
      }
	 	)   
  } # end function specifying rates used by adaptive tau 

   #specify for each reaction/rate/transition how the different variables change 
  #needs to be in exactly the same order as the rates listed in the rate function 
  transitions = list(c(Sh = -1,Ih = +1), 
 	 	 				c(Iv = +1,Sv = -1), 
 	 	 				c(Rh = +1,Ih = -1), 
 	 	 				c(Sh = +1,Rh = -1), 
 	 	 				c(Iv = -1), 
 	 	 				c(Sv = -1), 
 	 	 				c(Sv = +1)) 
 
  ############################## 
  #Main function code block 
  ############################## 
  set.seed(rngseed) #set random number seed for reproducibility 
  #Creating named vectors 
  varvec = c(Sh = Sh, Ih = Ih, Rh = Rh, Sv = Sv, Iv = Iv) 
  parvec = c(b1 = b1, b2 = b2, g = g, w = w, n = n, m = m) 
  #Running the model 
  simout = adaptivetau::ssa.adaptivetau(init.values = varvec, transitions = transitions,
                  	 	 	 rateFunc = Vector_transmission_model_fct, params = parvec, tf = tfinal) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
 }