#' Drug Resistance Evolution
#' 
#' @description An SIR-type model that includes drug treatment and resistance.
#' 
#' @details The model includes susceptible, infected untreated, treated and resistant, and recovered compartments. The processes which are modeled are infection, treatment, resistance generation and recovery.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of ordinary differential equations using the deSolve package. 
#' The following R packages need to be loaded for the function to work: deSolve. 
#' 
#' @param S : starting value for Susceptible : numeric
#' @param Iu : starting value for Infected Untreated : numeric
#' @param It : starting value for Infected Treated : numeric
#' @param Ir : starting value for Infected Resistant : numeric
#' @param R : starting value for Recovered : numeric
#' @param bu : untreated infection rate : numeric
#' @param bt : treated infection rate : numeric
#' @param br : resistant infection rate : numeric
#' @param gu : untreated recovery rate : numeric
#' @param gt : treated recovery rate : numeric
#' @param gr : resistant recovery rate : numeric
#' @param f : fraction treated : numeric
#' @param cu : resistance emergence untreated : numeric
#' @param ct : resistance emergence treated : numeric
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Drug_Resistance_Evolution_ode() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Drug_Resistance_Evolution_ode(S = 2000,Iu = 2,It = 2,Ir = 2,R = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2020-10-05
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2021-02-16
#' @export 
 
simulate_Drug_Resistance_Evolution_ode <- function(S = 1000, Iu = 1, It = 1, Ir = 1, R = 0, bu = 0.002, bt = 0.002, br = 0.002, gu = 1, gt = 1, gr = 1, f = 0, cu = 0, ct = 0, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  ############################## 
  #Block of ODE equations for deSolve 
  ############################## 
  Drug_Resistance_Evolution_ode_fct <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible : untreated individuals infected by untreated infected : untreated individuals infected by treated infected : treated individuals infected by untreated infected : treated individuals infected by treated infected : resistance emergence in untreated : resistance emergence in treated : infection by resistant :
    dS_mb = -S*(1-f)*bu*(1-cu)*Iu -S*(1-f)*bt*(1-ct)*It -S*f*bu*(1-cu)*Iu -S*f*bt*(1-ct)*It -S*bu*cu*Iu -S*bt*ct*It -S*br*Ir
    #Infected Untreated : untreated individuals infected by untreated infected : untreated individuals infected by treated infected : untreated recovery :
    dIu_mb = +S*(1-f)*bu*(1-cu)*Iu +S*(1-f)*bt*(1-ct)*It -gu*Iu
    #Infected Treated : treated individuals who got infected by untreated infected : treated individuals who got infected by treated infected : treated recovery :
    dIt_mb = +S*f*bu*(1-cu)*Iu +S*f*bt*(1-ct)*It -gt*It
    #Infected Resistant : resistance emergence in untreated : resistance emergence in treated : infection by resistant : resistant recovery :
    dIr_mb = +S*bu*cu*Iu +S*bt*ct*It +S*br*Ir -gr*Ir
    #Recovered : untreated recovery : treated recovery : resistant recovery :
    dR_mb = +gu*Iu +gt*It +gr*Ir
    #EndODES
    list(c(dS_mb,dIu_mb,dIt_mb,dIr_mb,dR_mb)) 
  } ) } #close with statement, end ODE code block 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec_mb = c(S = S, Iu = Iu, It = It, Ir = Ir, R = R) 
  parvec_mb = c(bu = bu, bt = bt, br = br, gu = gu, gt = gt, gr = gr, f = f, cu = cu, ct = ct) 
  timevec_mb = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout = deSolve::ode(y = varvec_mb, parms = parvec_mb, times = timevec_mb,  func = Drug_Resistance_Evolution_ode_fct, rtol = 1e-12, atol = 1e-12) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
} 
