#' SIR seasonal model
#' 
#' @description A basic seasonal SIR model with 3 compartments and infection and recovery processes
#' 
#' @details Add details.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of ordinary differential equations using the deSolve package. 
#' The following R packages need to be loaded for the function to work: deSolve. 
#' 
#' @param S : starting value for Susceptible population : numeric
#' @param I : starting value for Infected population : numeric
#' @param R : starting value for Recovered population : numeric
#' @param mu : birth and death rate : numeric
#' @param beta0 : baseline transmission rate : numeric
#' @param beta1 : seasonal transmission adjustment : numeric
#' @param omega : periodicity : numeric
#' @param gamma : recovery rate : numeric
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_SIR_seasonal_model_ode() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_SIR_seasonal_model_ode(S = 199998,I = 2,R = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel and Andrew Tredennick
#' @section Model creation date: 2020-08-20
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2021-02-16
#' @export 
 
simulate_SIR_seasonal_model_ode <- function(S = 99999, I = 1, R = 0, mu = 2e-04, beta0 = 0.03, beta1 = 0.05, omega = 0.02, gamma = 0.01, tstart = 0, tfinal = 10000, dt = 1) 
{ 
  ############################## 
  #Block of ODE equations for deSolve 
  ############################## 
  SIR_seasonal_model_ode_fct <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible population : all births : infections of susceptibles : Death of susceptibles :
    dS_mb = +mu*(S+I+R) -beta0*(1+beta1*sin(omega*t))*S*I/(S+I+R) -mu*S
    #Infected population : Infections from susceptibles : Recoveries : Deaths of infected population :
    dI_mb = +beta0*(1+beta1*sin(omega*t))*S*I/(S+I+R) -gamma*I -mu*I
    #Recovered population : Recoveries from infected class : Deaths from recovered population :
    dR_mb = +gamma*I -mu*R
    #EndODES
    list(c(dS_mb,dI_mb,dR_mb)) 
  } ) } #close with statement, end ODE code block 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec_mb = c(S = S, I = I, R = R) 
  parvec_mb = c(mu = mu, beta0 = beta0, beta1 = beta1, omega = omega, gamma = gamma) 
  timevec_mb = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout = deSolve::ode(y = varvec_mb, parms = parvec_mb, times = timevec_mb,  func = SIR_seasonal_model_ode_fct, rtol = 1e-12, atol = 1e-12) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
} 
