#' Host Heterogeneity Model
#' 
#' @description An SIR type model stratified for two different types of hosts.
#' 
#' @details This model tracks susceptibles, infected and recovered of 2 different types. Think of those types as e.g. males/females, children/adults, etc. The model includes infection, recovery and waning immunity processes for both hosts.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of discrete time equations using a for loop. 
 
#' The following R packages need to be loaded for the function to work: none 
#' 
#' @param S1 : starting value for Susceptible type 1 hosts : numeric
#' @param I1 : starting value for Infected type 1 hosts : numeric
#' @param R1 : starting value for Recovered type 1 hosts : numeric
#' @param S2 : starting value for Susceptible type 2 hosts : numeric
#' @param I2 : starting value for Infected type 2 hosts : numeric
#' @param R2 : starting value for Recovered type 2 hosts : numeric
#' @param b11 : rate of transmission to susceptible type 1 host from infected type 1 host : numeric
#' @param b12 : rate of transmission to susceptible type 1 host from infected type 2 host : numeric
#' @param b21 : rate of transmission to susceptible type 2 host from infected type 1 host : numeric
#' @param b22 : rate of transmission to susceptible type 2 host from infected type 2 host : numeric
#' @param g1 : the rate at which infected type 1 hosts recover : numeric
#' @param g2 : the rate at which infected type 2 hosts recover : numeric
#' @param w1 : the rate at which type 1 host immunity wanes : numeric
#' @param w2 : the rate at which type 2 host immunity wanes : numeric
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Host_Heterogeneity_Model_discrete() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Host_Heterogeneity_Model_discrete(S1 = 2000,I1 = 2,R1 = 0,S2 = 400,I2 = 2,R2 = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S1'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S1: ',max(result$ts[,'S1']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel, Alexis Vittengl
#' @section Model creation date: 2020-10-05
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2021-02-16
#' @export 
 
simulate_Host_Heterogeneity_Model_discrete <- function(S1 = 1000, I1 = 1, R1 = 0, S2 = 200, I2 = 1, R2 = 0, b11 = 0.002, b12 = 0, b21 = 0, b22 = 0.01, g1 = 1, g2 = 1, w1 = 0, w2 = 0, tstart = 0, tfinal = 60, dt = 0.1) 
{ 
  #Function that encodes simulation loop 
  Host_Heterogeneity_Model_fct <- function(vars, pars, times) 
  {
    with( as.list(c(vars,pars)), {  
      ts = data.frame(cbind(times, matrix(0,nrow=length(times),ncol=length(vars)))) 
      colnames(ts) = c('time','S1','I1','R1','S2','I2','R2') 
      ct=1 #a counter to index array 
      for (t in times) 
      {
        ts[ct,] = c(t,S1,I1,R1,S2,I2,R2) 
        S1p = S1 + dt*(-b11*S1*I1 -b12*S1*I2 +w1*R1) 
        I1p = I1 + dt*(+b11*S1*I1 +b12*S1*I2 -g1*I1) 
        R1p = R1 + dt*(+g1*I1 -w1*R1) 
        S2p = S2 + dt*(-b21*S2*I1 -b22*S2*I2 +w2*R2) 
        I2p = I2 + dt*(+b21*S2*I1 +b22*S2*I2 -g2*I2) 
        R2p = R2 + dt*(+g2*I2 -w2*R2) 
        S1 = S1p 
        I1 = I1p 
        R1 = R1p 
        S2 = S2p 
        I2 = I2p 
        R2 = R2p 
        ct = ct + 1 
      } #finish loop 
      return(ts) 
    }) #close with statement 
 } #end function encoding loop 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec = c(S1 = S1, I1 = I1, R1 = R1, S2 = S2, I2 = I2, R2 = R2) 
  parvec = c(b11 = b11, b12 = b12, b21 = b21, b22 = b22, g1 = g1, g2 = g2, w1 = w1, w2 = w2) 
  timevec = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout <- Host_Heterogeneity_Model_fct(vars = varvec, pars = parvec, times = timevec) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- simout 
  return(result) 
} 
