#' Vector transmission model
#' 
#' @description A basic model with several compartments to model vector-borne transmission
#' 
#' @details The model tracks the dynamics of susceptible, infected, and recovered hosts, and susceptible and infected vectors. Infection, recovery, and waning immunity processes are implemented for hosts. Births and deaths and infection processes are implemented for vectors.
#' 
#' This code is was generated by the modelbuilder package R.  
#' The model is implemented as a set of discrete time equations using a for loop. 
 
#' The following R packages need to be loaded for the function to work: none 
#' 
#' Starting conditions for model variables 
#' @param Sh : starting value for Susceptible hosts : numeric
#' @param Ih : starting value for Infected hosts : numeric
#' @param Rh : starting value for Recovered hosts : numeric
#' @param Sv : starting value for Susceptible Vectors : numeric
#' @param Iv : starting value for Infected Vectors : numeric
#' Values for model parameters : numeric 
#' @param b1 : infection rate of hosts : numeric
#' @param b2 : infection rate of vectors : numeric
#' @param g : recovery rate of hosts : numeric
#' @param w : wanning immunity rate : numeric
#' @param n : vector birth rate : numeric
#' @param m : vector death rate : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Vector_transmission_model_discrete() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Vector_transmission_model_discrete(Sh = 2000,Ih = 2,Rh = 0,Sv = 2000,Iv = 2) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'Sh'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of Sh: ',max(result$ts[,'Sh']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2020-06-24
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-06-24
#' @export 
 
simulate_Vector_transmission_model_discrete <- function(Sh = 1000, Ih = 1, Rh = 0, Sv = 1000, Iv = 1, b1 = 0.002, b2 = 0.002, g = 1, w = 0.1, n = 100, m = 0.1, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  #Function that encodes simulation loop 
  Vector_transmission_model_fct <- function(vars, pars, times) 
  {
    with( as.list(c(vars,pars)), {  
      ts = data.frame(cbind(times, matrix(0,nrow=length(times),ncol=length(vars)))) 
      colnames(ts) = c('time','Sh','Ih','Rh','Sv','Iv') 
      ct=1 #a counter to index array 
      for (t in times) 
      {
        ts[ct,] = c(t,Sh,Ih,Rh,Sv,Iv) 
        Shp = Sh + dt*(-b1*Sh*Iv +w*Rh) 
        Ihp = Ih + dt*(+b1*Sh*Iv -g*Ih) 
        Rhp = Rh + dt*(+g*Ih -w*Rh) 
        Svp = Sv + dt*(+n -b2*Sv*Ih -m*Sv) 
        Ivp = Iv + dt*(+b2*Sv*Ih -m*Iv) 
        Sh = Shp 
        Ih = Ihp 
        Rh = Rhp 
        Sv = Svp 
        Iv = Ivp 
        ct = ct + 1 
      } #finish loop 
      return(ts) 
    }) #close with statement 
 } #end function encoding loop 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec = c(Sh = Sh, Ih = Ih, Rh = Rh, Sv = Sv, Iv = Iv) 
  parvec = c(b1 = b1, b2 = b2, g = g, w = w, n = n, m = m) 
  timevec = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout <- Vector_transmission_model_fct(vars = varvec, pars = parvec, times = timevec) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- simout 
  return(result) 
} 
