#' Reproductive Number 2
#' 
#' @description A reproductive number model built from expanding the basic SIR model. 
#' 
#' @details The model includes susceptible, infected, and recovered compartments. The processes that are modeled are infection, recovery, birth, death, and immunity.
#' 
#' This code is was generated by the modelbuilder package R.  
#' The model is implemented as a set of stochastic equations using the adaptivetau package. 
 
#' The following R packages need to be loaded for the function to work: adpativetau 
#' 
#' Starting conditions for model variables 
#' @param S : starting value for Susceptible : numeric
#' @param I : starting value for Infected : numeric
#' @param R : starting value for Recovered : numeric
#' Values for model parameters : numeric 
#' @param b : infection rate : numeric
#' @param g : recovery rate : numeric
#' @param m : birth rate : numeric
#' @param n : death rate : numeric
#' @param w : lose immunity : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @param rngseed : set random number seed for reproducibility : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Reproductive_Number_2_stochastic() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Reproductive_Number_2_stochastic(S = 2000,I = 2,R = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Alexis Vittengl 
#' @section Model creation date: 2020-07-09
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-07-09
#' @export 
 
simulate_Reproductive_Number_2_stochastic <- function(S = 1000, I = 1, R = 0, b = 0.002, g = 0.1, m = 1.2, n = 0.05, w = 0.02, tstart = 0, tfinal = 100, dt = 0.1, rngseed = 123) 
{ 
  #Block of ODE equations for adaptivetau 
  Reproductive_Number_2_fct <- function(y, parms, t) 
  {
    with(as.list(c(y,parms)),   
     { 
       #specify each rate/transition/reaction that can happen in the system 
     rates = c(b*S*I, g*I, w*R, m, n*I, n*R, n*S)
     return(rates) 
      }
	 	)   
  } # end function specifying rates used by adaptive tau 

   #specify for each reaction/rate/transition how the different variables change 
  #needs to be in exactly the same order as the rates listed in the rate function 
  transitions = list(c(S = -1,I = +1), 
 	 	 				c(R = +1,I = -1), 
 	 	 				c(R = -1,S = +1), 
 	 	 				c(S = +1), 
 	 	 				c(I = -1), 
 	 	 				c(R = -1), 
 	 	 				c(S = -1)) 
 
  ############################## 
  #Main function code block 
  ############################## 
  set.seed(rngseed) #set random number seed for reproducibility 
  #Creating named vectors 
  varvec = c(S = S, I = I, R = R) 
  parvec = c(b = b, g = g, m = m, n = n, w = w) 
  #Running the model 
  simout = adaptivetau::ssa.adaptivetau(init.values = varvec, transitions = transitions,
                  	 	 	 rateFunc = Reproductive_Number_2_fct, params = parvec, tf = tfinal) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
 }