#' Cholera model
#' 
#' @description A Cholera model based on Codeco 2001 BMC ID
#' 
#' @details The model includes susceptible, infected, and environmental compartments. See reference for more details.
#' 
#' This code is was generated by the modelbuilder package R.  
#' The model is implemented as a set of stochastic equations using the adaptivetau package. 
 
#' The following R packages need to be loaded for the function to work: adpativetau 
#' 
#' Starting conditions for model variables 
#' @param S : starting value for Susceptible : numeric
#' @param I : starting value for Infected : numeric
#' @param B : starting value for Bacteria : numeric
#' Values for model parameters : numeric 
#' @param h : population size : numeric
#' @param n : birth rate : numeric
#' @param a : infection rate : numeric
#' @param k : 50% infection rate : numeric
#' @param r : recovery rate : numeric
#' @param nb : bacteria growth rate : numeric
#' @param mb : bacteria death rate : numeric
#' @param e : bacteria shedding rate : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @param rngseed : set random number seed for reproducibility : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Cholera_model_stochastic() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Cholera_model_stochastic(S = 20000,I = 2,B = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2020-06-26
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-06-26
#' @export 
 
simulate_Cholera_model_stochastic <- function(S = 10000, I = 1, B = 0, h = 10000, n = 1e-04, a = 1, k = 1e+06, r = 0.2, nb = 1, mb = 1.33, e = 10, tstart = 0, tfinal = 500, dt = 0.1, rngseed = 123) 
{ 
  #Block of ODE equations for adaptivetau 
  Cholera_model_fct <- function(y, parms, t) 
  {
    with(as.list(c(y,parms)),   
     { 
       #specify each rate/transition/reaction that can happen in the system 
     rates = c(a*B/(k+B)*S, e*I, mb*B, n*h, n*S, nb*B, r*I)
     return(rates) 
      }
	 	)   
  } # end function specifying rates used by adaptive tau 

   #specify for each reaction/rate/transition how the different variables change 
  #needs to be in exactly the same order as the rates listed in the rate function 
  transitions = list(c(I = +1,S = -1), 
 	 	 				c(B = +1), 
 	 	 				c(B = -1), 
 	 	 				c(S = +1), 
 	 	 				c(S = -1), 
 	 	 				c(B = +1), 
 	 	 				c(I = -1)) 
 
  ############################## 
  #Main function code block 
  ############################## 
  set.seed(rngseed) #set random number seed for reproducibility 
  #Creating named vectors 
  varvec = c(S = S, I = I, B = B) 
  parvec = c(h = h, n = n, a = a, k = k, r = r, nb = nb, mb = mb, e = e) 
  #Running the model 
  simout = adaptivetau::ssa.adaptivetau(init.values = varvec, transitions = transitions,
                  	 	 	 rateFunc = Cholera_model_fct, params = parvec, tf = tfinal) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
 }