#' Environmental Transmission model
#' 
#' @description An SIR model including environmental transmission
#' 
#' @details The model includes susceptible, infected, recovered and environmental pathogen compartments. Infection can occur through direct contact with infected or through contact with pathogen in the environment. Infected individuals shed into the environment, pathogen decays there.
#' 
#' This code is was generated by the modelbuilder package R.  
#' The model is implemented as a set of stochastic equations using the adaptivetau package. 
 
#' The following R packages need to be loaded for the function to work: adpativetau 
#' 
#' Starting conditions for model variables 
#' @param S : starting value for Susceptible : numeric
#' @param I : starting value for Infected : numeric
#' @param R : starting value for Recovered : numeric
#' @param P : starting value for Pathogen in environment : numeric
#' Values for model parameters : numeric 
#' @param bI : direct transmission rate : numeric
#' @param bP : environmental transmission rate : numeric
#' @param n : birth rate : numeric
#' @param m : natural death rate : numeric
#' @param g : recovery rate : numeric
#' @param q : rate at which infected hosts shed pathogen into the environment : numeric
#' @param c : rate at which pathogen in the environment decays : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @param rngseed : set random number seed for reproducibility : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Environmental_Transmission_model_stochastic() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Environmental_Transmission_model_stochastic(S = 20000,I = 2,R = 0,P = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2020-06-24
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-06-24
#' @export 
 
simulate_Environmental_Transmission_model_stochastic <- function(S = 10000, I = 1, R = 0, P = 0, bI = 1e-04, bP = 0, n = 0, m = 0, g = 0.2, q = 0, c = 10, tstart = 0, tfinal = 500, dt = 0.1, rngseed = 123) 
{ 
  #Block of ODE equations for adaptivetau 
  Environmental_Transmission_model_fct <- function(y, parms, t) 
  {
    with(as.list(c(y,parms)),   
     { 
       #specify each rate/transition/reaction that can happen in the system 
     rates = c(bI*I*S, bP*P*S, g*I, m*I, c*P, m*S, n, q*I)
     return(rates) 
      }
	 	)   
  } # end function specifying rates used by adaptive tau 

   #specify for each reaction/rate/transition how the different variables change 
  #needs to be in exactly the same order as the rates listed in the rate function 
  transitions = list(c(I = +1,S = -1), 
 	 	 				c(I = +1,S = -1), 
 	 	 				c(R = +1,I = -1), 
 	 	 				c(R = -1,I = -1), 
 	 	 				c(P = -1), 
 	 	 				c(S = -1), 
 	 	 				c(S = +1), 
 	 	 				c(P = +1)) 
 
  ############################## 
  #Main function code block 
  ############################## 
  set.seed(rngseed) #set random number seed for reproducibility 
  #Creating named vectors 
  varvec = c(S = S, I = I, R = R, P = P) 
  parvec = c(bI = bI, bP = bP, n = n, m = m, g = g, q = q, c = c) 
  #Running the model 
  simout = adaptivetau::ssa.adaptivetau(init.values = varvec, transitions = transitions,
                  	 	 	 rateFunc = Environmental_Transmission_model_fct, params = parvec, tf = tfinal) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
 }