#' Complex ID Control Scenarios
#' 
#' @description The basic SIR model is expanded to include vectors.
#' 
#' @details The model includes susceptible, infected, asymptomatic, presymptomactic, pathogens, susceptible vectors, infected vectors, recovered and death compartments. The processes that are modeled are infection, recovery, birth, death, and immunity.
#' 
#' This code is was generated by the modelbuilder package R.  
#' The model is implemented as a set of discrete time equations using a for loop. 
 
#' The following R packages need to be loaded for the function to work: none 
#' 
#' Starting conditions for model variables 
#' @param S : starting value for Susceptible Host : numeric
#' @param P : starting value for Infected, Presymptomatic : numeric
#' @param A : starting value for Infected, Asymptomatic : numeric
#' @param I : starting value for Infected, Symptomatic : numeric
#' @param R : starting value for Recovered : numeric
#' @param D : starting value for Deaths : numeric
#' @param E : starting value for Pathogen in the environment : numeric
#' @param SV : starting value for Susceptible Vectors : numeric
#' @param IV : starting value for Infectious Vectors : numeric
#' Values for model parameters : numeric 
#' @param bP : Presymptomatic infection rate : numeric
#' @param bA : Asymptomatic infection rate : numeric
#' @param bI : Symptomatic infection rate : numeric
#' @param bE : Pathogen infection rate : numeric
#' @param bV : Vector infection rate : numeric
#' @param bh : Host natural infection rate : numeric
#' @param nV : Vector natural death rate : numeric
#' @param nh : Host death rate : numeric
#' @param gP : Presymptomatic recovery rate : numeric
#' @param gA : Asymptomatic recovery rate : numeric
#' @param gI : Symptomatic recovery rate : numeric
#' @param pI : Symptomatic host pathogen shed rate : numeric
#' @param pA : Asymptomatic host pathogen shed rate : numeric
#' @param c : pathogen decay rate  : numeric
#' @param eV : Susceptible vector enter system rate : numeric
#' @param eh : Susceptible host enter system rate : numeric
#' @param f : presymptomatic hosts move into the asymptomatic rate : numeric
#' @param d : host death rate due to infection : numeric
#' @param w : Loss of immunity rate : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Complex_ID_Control_Scenarios_discrete() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Complex_ID_Control_Scenarios_discrete(S = 2000,P = 2,A = 2,I = 2,R = 0,D = 0,E = 0,SV = 200,IV = 2) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author:  Alexis Vittengl
#' @section Model creation date: 2020-09-01
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-09-01
#' @export 
 
simulate_Complex_ID_Control_Scenarios_discrete <- function(S = 1000, P = 1, A = 1, I = 1, R = 0, D = 0, E = 0, SV = 100, IV = 1, bP = 0.002, bA = 0.002, bI = 0.002, bE = 0.002, bV = 0.002, bh = 0.002, nV = 0.02, nh = 0.02, gP = 0.05, gA = 0.05, gI = 0.05, pI = 0.01, pA = 0.01, c = 0.03, eV = 0.2, eh = 0.2, f = 0.4, d = 0.08, w = 0.005, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  #Function that encodes simulation loop 
  Complex_ID_Control_Scenarios_fct <- function(vars, pars, times) 
  {
    with( as.list(c(vars,pars)), {  
      ts = data.frame(cbind(times, matrix(0,nrow=length(times),ncol=length(vars)))) 
      colnames(ts) = c('time','S','P','A','I','R','D','E','SV','IV') 
      ct=1 #a counter to index array 
      for (t in times) 
      {
        ts[ct,] = c(t,S,P,A,I,R,D,E,SV,IV) 
        Sp = S + dt*(+eh -bP*P*S -bA*A*S -bI*I*S -bE*E*S +w*R -nh*S) 
        Pp = P + dt*(+bP*P*S +bA*A*S +bI*I*S +bE*E*S +bV*IV*S -gP*P -nh*P) 
        Ap = A + dt*(+f*gP*P -gA*A -nh*A) 
        Ip = I + dt*(+gP*P -f*gP*P -gI*I -nh*I) 
        Rp = R + dt*(+gA*A +gI*I -d*gI*I -w*R -nh*R) 
        Dp = D + dt*(+d*gI*I) 
        Ep = E + dt*(+pI*I +pA*A -c*E) 
        SVp = SV + dt*(+eV -bh*I*SV -nV*SV) 
        IVp = IV + dt*(+bh*I*SV -nV*IV) 
        S = Sp 
        P = Pp 
        A = Ap 
        I = Ip 
        R = Rp 
        D = Dp 
        E = Ep 
        SV = SVp 
        IV = IVp 
        ct = ct + 1 
      } #finish loop 
      return(ts) 
    }) #close with statement 
 } #end function encoding loop 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec = c(S = S, P = P, A = A, I = I, R = R, D = D, E = E, SV = SV, IV = IV) 
  parvec = c(bP = bP, bA = bA, bI = bI, bE = bE, bV = bV, bh = bh, nV = nV, nh = nh, gP = gP, gA = gA, gI = gI, pI = pI, pA = pA, c = c, eV = eV, eh = eh, f = f, d = d, w = w) 
  timevec = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout <- Complex_ID_Control_Scenarios_fct(vars = varvec, pars = parvec, times = timevec) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- simout 
  return(result) 
} 
