#' Environmental Transmission model
#' 
#' @description An SIR model including environmental transmission
#' 
#' @details The model includes susceptible, infected, recovered and environmental pathogen compartments. Infection can occur through direct contact with infected or through contact with pathogen in the environment. Infected individuals shed into the environment, pathogen decays there.
#' 
#' This code is was generated by the modelbuilder package R.  
#' The model is implemented as a set of discrete time equations using a for loop. 
 
#' The following R packages need to be loaded for the function to work: none 
#' 
#' Starting conditions for model variables 
#' @param S : starting value for Susceptible : numeric
#' @param I : starting value for Infected : numeric
#' @param R : starting value for Recovered : numeric
#' @param P : starting value for Pathogen in environment : numeric
#' Values for model parameters : numeric 
#' @param bI : direct transmission rate : numeric
#' @param bP : environmental transmission rate : numeric
#' @param n : birth rate : numeric
#' @param m : natural death rate : numeric
#' @param g : recovery rate : numeric
#' @param q : rate at which infected hosts shed pathogen into the environment : numeric
#' @param c : rate at which pathogen in the environment decays : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Environmental_Transmission_model_discrete() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Environmental_Transmission_model_discrete(S = 20000,I = 2,R = 0,P = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2020-07-09
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-07-09
#' @export 
 
simulate_Environmental_Transmission_model_discrete <- function(S = 10000, I = 1, R = 0, P = 0, bI = 1e-04, bP = 0, n = 0, m = 0, g = 0.2, q = 0, c = 10, tstart = 0, tfinal = 500, dt = 0.1) 
{ 
  #Function that encodes simulation loop 
  Environmental_Transmission_model_fct <- function(vars, pars, times) 
  {
    with( as.list(c(vars,pars)), {  
      ts = data.frame(cbind(times, matrix(0,nrow=length(times),ncol=length(vars)))) 
      colnames(ts) = c('time','S','I','R','P') 
      ct=1 #a counter to index array 
      for (t in times) 
      {
        ts[ct,] = c(t,S,I,R,P) 
        Sp = S + dt*(+n -m*S -bI*I*S -bP*P*S) 
        Ip = I + dt*(+bI*I*S +bP*P*S -m*I -g*I) 
        Rp = R + dt*(+g*I -m*I) 
        Pp = P + dt*(+q*I -c*P) 
        S = Sp 
        I = Ip 
        R = Rp 
        P = Pp 
        ct = ct + 1 
      } #finish loop 
      return(ts) 
    }) #close with statement 
 } #end function encoding loop 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec = c(S = S, I = I, R = R, P = P) 
  parvec = c(bI = bI, bP = bP, n = n, m = m, g = g, q = q, c = c) 
  timevec = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout <- Environmental_Transmission_model_fct(vars = varvec, pars = parvec, times = timevec) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- simout 
  return(result) 
} 
