#' Basic Bacteria Model
#' 
#' @description A basic bacteria infection model with 2 compartments
#' 
#' @details The model includes bacteria and an immune response. The processes are bacteria growth, death and killing, and immune response activation and decay. This is a predator-prey type model.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of discrete time equations using a for loop. 
 
#' The following R packages need to be loaded for the function to work: none 
#' 
#' @param B : starting value for Bacteria : numeric
#' @param I : starting value for Immune Response : numeric
#' @param g : maximum rate of bacteria growth : numeric
#' @param maxB : bacteria carrying capacity : numeric
#' @param dB : bacteria death rate : numeric
#' @param k : bacteria kill rate : numeric
#' @param r : immune response growth rate : numeric
#' @param dI : immune response decay rate : numeric
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Basic_Bacteria_Model_discrete() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Basic_Bacteria_Model_discrete(B = 20,I = 2) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'B'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of B: ',max(result$ts[,'B']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2022-05-09
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2022-05-09
#' @export 
 
simulate_Basic_Bacteria_Model_discrete <- function(B = 10, I = 1, g = 1, maxB = 1e+06, dB = 0.1, k = 1e-07, r = 0.001, dI = 1, tstart = 0, tfinal = 30, dt = 0.01) 
{ 
  #Function that encodes simulation loop 
  Basic_Bacteria_Model_fct <- function(vars, pars, times) 
  {
    with( as.list(c(vars,pars)), {  
      ts = data.frame(cbind(times, matrix(0,nrow=length(times),ncol=length(vars)))) 
      colnames(ts) = c('time','B','I') 
      ct=1 #a counter to index array 
      for (t in times) 
      {
        ts[ct,] = c(t,B,I) 
        Bp = B + dt*(+g*B*(1-B/maxB) -dB*B -k*B*I) 
        Ip = I + dt*(+r*B*I -dI*I) 
        B = Bp 
        I = Ip 
        ct = ct + 1 
      } #finish loop 
      return(ts) 
    }) #close with statement 
 } #end function encoding loop 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec = c(B = B, I = I) 
  parvec = c(g = g, maxB = maxB, dB = dB, k = k, r = r, dI = dI) 
  timevec = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout <- Basic_Bacteria_Model_fct(vars = varvec, pars = parvec, times = timevec) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- simout 
  return(result) 
} 
