#' SIRSd2_vaccine_age
#' 
#' @description A SIRSd model with 3 compartments. Processes are infection, recovery, births deaths and waning immunity.
#' 
#' @details The model includes susceptible, infected, and recovered compartments. The processes which are modeled are infection, recovery, natural births and deaths and waning immunity.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of ordinary differential equations using the deSolve package. 
#' The following R packages need to be loaded for the function to work: deSolve. 
#' 
#' Starting conditions for model variables 
#' @param Suvc : starting value for Susceptible unvaccinated children : numeric
#' @param Suva : starting value for Susceptible unvaccinated adults : numeric
#' @param Suve : starting value for Susceptible unvaccinated elderly : numeric
#' @param Svc : starting value for Susceptible vaccinated children : numeric
#' @param Sva : starting value for Susceptible vaccinated adults : numeric
#' @param Sve : starting value for Susceptible vaccinated elderly : numeric
#' @param Iuvc : starting value for Infected unvaccinated children : numeric
#' @param Iuva : starting value for Infected unvaccinated adults : numeric
#' @param Iuve : starting value for Infected unvaccinated elderly : numeric
#' @param Ivc : starting value for Infected vaccinated children : numeric
#' @param Iva : starting value for Infected vaccinated adults : numeric
#' @param Ive : starting value for Infected vaccinated elderly : numeric
#' @param Ruvc : starting value for Recovered unvaccinated children : numeric
#' @param Ruva : starting value for Recovered unvaccinated adults : numeric
#' @param Ruve : starting value for Recovered unvaccinated elderly : numeric
#' @param Rvc : starting value for Recovered vaccinated children : numeric
#' @param Rva : starting value for Recovered vaccinated adults : numeric
#' @param Rve : starting value for Recovered vaccinated elderly : numeric
#' Values for model parameters : numeric 
#' @param b_Suvc_Iuvc : infection rate: to susceptible unvaccinated children from infected unvaccinated children : numeric
#' @param b_Suvc_Iuva : infection rate: to susceptible unvaccinated children from infected unvaccinated adults : numeric
#' @param b_Suvc_Iuve : infection rate: to susceptible unvaccinated children from infected unvaccinated elderly : numeric
#' @param b_Suvc_Ivc : infection rate: to susceptible unvaccinated children from infected vaccinated children : numeric
#' @param b_Suvc_Iva : infection rate: to susceptible unvaccinated children from infected vaccinated adults : numeric
#' @param b_Suvc_Ive : infection rate: to susceptible unvaccinated children from infected vaccinated elderly : numeric
#' @param w_Ruvc : waning immunity rate: recovered unvaccinated children : numeric
#' @param n : birth rate : numeric
#' @param mS_Suvc : death rate of S: susceptible unvaccinated children : numeric
#' @param b_Suva_Iuvc : infection rate: to susceptible unvaccinated adults from infected unvaccinated children : numeric
#' @param b_Suva_Iuva : infection rate: to susceptible unvaccinated adults from infected unvaccinated adults : numeric
#' @param b_Suva_Iuve : infection rate: to susceptible unvaccinated adults from infected unvaccinated elderly : numeric
#' @param b_Suva_Ivc : infection rate: to susceptible unvaccinated adults from infected vaccinated children : numeric
#' @param b_Suva_Iva : infection rate: to susceptible unvaccinated adults from infected vaccinated adults : numeric
#' @param b_Suva_Ive : infection rate: to susceptible unvaccinated adults from infected vaccinated elderly : numeric
#' @param w_Ruva : waning immunity rate: recovered unvaccinated adults : numeric
#' @param mS_Suva : death rate of S: susceptible unvaccinated adults : numeric
#' @param b_Suve_Iuvc : infection rate: to susceptible unvaccinated elderly from infected unvaccinated children : numeric
#' @param b_Suve_Iuva : infection rate: to susceptible unvaccinated elderly from infected unvaccinated adults : numeric
#' @param b_Suve_Iuve : infection rate: to susceptible unvaccinated elderly from infected unvaccinated elderly : numeric
#' @param b_Suve_Ivc : infection rate: to susceptible unvaccinated elderly from infected vaccinated children : numeric
#' @param b_Suve_Iva : infection rate: to susceptible unvaccinated elderly from infected vaccinated adults : numeric
#' @param b_Suve_Ive : infection rate: to susceptible unvaccinated elderly from infected vaccinated elderly : numeric
#' @param w_Ruve : waning immunity rate: recovered unvaccinated elderly : numeric
#' @param mS_Suve : death rate of S: susceptible unvaccinated elderly : numeric
#' @param b_Svc_Iuvc : infection rate: to susceptible vaccinated children from infected unvaccinated children : numeric
#' @param b_Svc_Iuva : infection rate: to susceptible vaccinated children from infected unvaccinated adults : numeric
#' @param b_Svc_Iuve : infection rate: to susceptible vaccinated children from infected unvaccinated elderly : numeric
#' @param b_Svc_Ivc : infection rate: to susceptible vaccinated children from infected vaccinated children : numeric
#' @param b_Svc_Iva : infection rate: to susceptible vaccinated children from infected vaccinated adults : numeric
#' @param b_Svc_Ive : infection rate: to susceptible vaccinated children from infected vaccinated elderly : numeric
#' @param w_Rvc : waning immunity rate: recovered vaccinated children : numeric
#' @param mS_Svc : death rate of S: susceptible vaccinated children : numeric
#' @param b_Sva_Iuvc : infection rate: to susceptible vaccinated adults from infected unvaccinated children : numeric
#' @param b_Sva_Iuva : infection rate: to susceptible vaccinated adults from infected unvaccinated adults : numeric
#' @param b_Sva_Iuve : infection rate: to susceptible vaccinated adults from infected unvaccinated elderly : numeric
#' @param b_Sva_Ivc : infection rate: to susceptible vaccinated adults from infected vaccinated children : numeric
#' @param b_Sva_Iva : infection rate: to susceptible vaccinated adults from infected vaccinated adults : numeric
#' @param b_Sva_Ive : infection rate: to susceptible vaccinated adults from infected vaccinated elderly : numeric
#' @param w_Rva : waning immunity rate: recovered vaccinated adults : numeric
#' @param mS_Sva : death rate of S: susceptible vaccinated adults : numeric
#' @param b_Sve_Iuvc : infection rate: to susceptible vaccinated elderly from infected unvaccinated children : numeric
#' @param b_Sve_Iuva : infection rate: to susceptible vaccinated elderly from infected unvaccinated adults : numeric
#' @param b_Sve_Iuve : infection rate: to susceptible vaccinated elderly from infected unvaccinated elderly : numeric
#' @param b_Sve_Ivc : infection rate: to susceptible vaccinated elderly from infected vaccinated children : numeric
#' @param b_Sve_Iva : infection rate: to susceptible vaccinated elderly from infected vaccinated adults : numeric
#' @param b_Sve_Ive : infection rate: to susceptible vaccinated elderly from infected vaccinated elderly : numeric
#' @param w_Rve : waning immunity rate: recovered vaccinated elderly : numeric
#' @param mS_Sve : death rate of S: susceptible vaccinated elderly : numeric
#' @param g_Iuvc : recovery rate: infected unvaccinated children : numeric
#' @param mI_Iuvc : death rate of I: infected unvaccinated children : numeric
#' @param g_Iuva : recovery rate: infected unvaccinated adults : numeric
#' @param mI_Iuva : death rate of I: infected unvaccinated adults : numeric
#' @param g_Iuve : recovery rate: infected unvaccinated elderly : numeric
#' @param mI_Iuve : death rate of I: infected unvaccinated elderly : numeric
#' @param g_Ivc : recovery rate: infected vaccinated children : numeric
#' @param mI_Ivc : death rate of I: infected vaccinated children : numeric
#' @param g_Iva : recovery rate: infected vaccinated adults : numeric
#' @param mI_Iva : death rate of I: infected vaccinated adults : numeric
#' @param g_Ive : recovery rate: infected vaccinated elderly : numeric
#' @param mI_Ive : death rate of I: infected vaccinated elderly : numeric
#' @param mR_Ruvc : death rate of R: recovered unvaccinated children : numeric
#' @param mR_Ruva : death rate of R: recovered unvaccinated adults : numeric
#' @param mR_Ruve : death rate of R: recovered unvaccinated elderly : numeric
#' @param mR_Rvc : death rate of R: recovered vaccinated children : numeric
#' @param mR_Rva : death rate of R: recovered vaccinated adults : numeric
#' @param mR_Rve : death rate of R: recovered vaccinated elderly : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_SIRSd2_vaccine_age_ode() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_SIRSd2_vaccine_age_ode(Suvc = 2000,Suva = 2000,Suve = 2000,Svc = 2000,Sva = 2000,Sve = 2000,Iuvc = 2,Iuva = 2,Iuve = 2,Ivc = 2,Iva = 2,Ive = 2,Ruvc = 0,Ruva = 0,Ruve = 0,Rvc = 0,Rva = 0,Rve = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'Suvc'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of Suvc: ',max(result$ts[,'Suvc']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 18535
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-10-01
#' @export 
 
simulate_SIRSd2_vaccine_age_ode <- function(Suvc = 1000, Suva = 1000, Suve = 1000, Svc = 1000, Sva = 1000, Sve = 1000, Iuvc = 1, Iuva = 1, Iuve = 1, Ivc = 1, Iva = 1, Ive = 1, Ruvc = 0, Ruva = 0, Ruve = 0, Rvc = 0, Rva = 0, Rve = 0, b_Suvc_Iuvc = 0.002, b_Suvc_Iuva = 0.002, b_Suvc_Iuve = 0.002, b_Suvc_Ivc = 0.002, b_Suvc_Iva = 0.002, b_Suvc_Ive = 0.002, w_Ruvc = 1, n = 0, mS_Suvc = 0, b_Suva_Iuvc = 0.002, b_Suva_Iuva = 0.002, b_Suva_Iuve = 0.002, b_Suva_Ivc = 0.002, b_Suva_Iva = 0.002, b_Suva_Ive = 0.002, w_Ruva = 1, mS_Suva = 0, b_Suve_Iuvc = 0.002, b_Suve_Iuva = 0.002, b_Suve_Iuve = 0.002, b_Suve_Ivc = 0.002, b_Suve_Iva = 0.002, b_Suve_Ive = 0.002, w_Ruve = 1, mS_Suve = 0, b_Svc_Iuvc = 0.002, b_Svc_Iuva = 0.002, b_Svc_Iuve = 0.002, b_Svc_Ivc = 0.002, b_Svc_Iva = 0.002, b_Svc_Ive = 0.002, w_Rvc = 1, mS_Svc = 0, b_Sva_Iuvc = 0.002, b_Sva_Iuva = 0.002, b_Sva_Iuve = 0.002, b_Sva_Ivc = 0.002, b_Sva_Iva = 0.002, b_Sva_Ive = 0.002, w_Rva = 1, mS_Sva = 0, b_Sve_Iuvc = 0.002, b_Sve_Iuva = 0.002, b_Sve_Iuve = 0.002, b_Sve_Ivc = 0.002, b_Sve_Iva = 0.002, b_Sve_Ive = 0.002, w_Rve = 1, mS_Sve = 0, g_Iuvc = 1, mI_Iuvc = 0, g_Iuva = 1, mI_Iuva = 0, g_Iuve = 1, mI_Iuve = 0, g_Ivc = 1, mI_Ivc = 0, g_Iva = 1, mI_Iva = 0, g_Ive = 1, mI_Ive = 0, mR_Ruvc = 0, mR_Ruva = 0, mR_Ruve = 0, mR_Rvc = 0, mR_Rva = 0, mR_Rve = 0, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  ############################## 
  #Block of ODE equations for deSolve 
  ############################## 
  SIRSd2_vaccine_age_ode_fct <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible unvaccinated children : infection, unvaccinated, children : infection, unvaccinated, children : infection, unvaccinated, children : infection, unvaccinated, children : infection, unvaccinated, children : infection, unvaccinated, children : waning immunity, unvaccinated, children : waning immunity, unvaccinated, children : waning immunity, unvaccinated, children : waning immunity, unvaccinated, children : waning immunity, unvaccinated, children : waning immunity, unvaccinated, children : births, unvaccinated, children : births, unvaccinated, children : births, unvaccinated, children : births, unvaccinated, children : births, unvaccinated, children : births, unvaccinated, children : natural deaths of S, unvaccinated, children : natural deaths of S, unvaccinated, children : natural deaths of S, unvaccinated, children : natural deaths of S, unvaccinated, children : natural deaths of S, unvaccinated, children : natural deaths of S, unvaccinated, children :
    dSuvc_mb = -b_Suvc_Iuvc*Suvc*Iuvc -b_Suvc_Iuva*Suvc*Iuva -b_Suvc_Iuve*Suvc*Iuve -b_Suvc_Ivc*Suvc*Ivc -b_Suvc_Iva*Suvc*Iva -b_Suvc_Ive*Suvc*Ive +w_Ruvc*Ruvc +n -mS_Suvc*Suvc
    #Susceptible unvaccinated adults : infection, unvaccinated, adults : infection, unvaccinated, adults : infection, unvaccinated, adults : infection, unvaccinated, adults : infection, unvaccinated, adults : infection, unvaccinated, adults : waning immunity, unvaccinated, adults : waning immunity, unvaccinated, adults : waning immunity, unvaccinated, adults : waning immunity, unvaccinated, adults : waning immunity, unvaccinated, adults : waning immunity, unvaccinated, adults : births, unvaccinated, adults : births, unvaccinated, adults : births, unvaccinated, adults : births, unvaccinated, adults : births, unvaccinated, adults : births, unvaccinated, adults : natural deaths of S, unvaccinated, adults : natural deaths of S, unvaccinated, adults : natural deaths of S, unvaccinated, adults : natural deaths of S, unvaccinated, adults : natural deaths of S, unvaccinated, adults : natural deaths of S, unvaccinated, adults :
    dSuva_mb = -b_Suva_Iuvc*Suva*Iuvc -b_Suva_Iuva*Suva*Iuva -b_Suva_Iuve*Suva*Iuve -b_Suva_Ivc*Suva*Ivc -b_Suva_Iva*Suva*Iva -b_Suva_Ive*Suva*Ive +w_Ruva*Ruva +n -mS_Suva*Suva
    #Susceptible unvaccinated elderly : infection, unvaccinated, elderly : infection, unvaccinated, elderly : infection, unvaccinated, elderly : infection, unvaccinated, elderly : infection, unvaccinated, elderly : infection, unvaccinated, elderly : waning immunity, unvaccinated, elderly : waning immunity, unvaccinated, elderly : waning immunity, unvaccinated, elderly : waning immunity, unvaccinated, elderly : waning immunity, unvaccinated, elderly : waning immunity, unvaccinated, elderly : births, unvaccinated, elderly : births, unvaccinated, elderly : births, unvaccinated, elderly : births, unvaccinated, elderly : births, unvaccinated, elderly : births, unvaccinated, elderly : natural deaths of S, unvaccinated, elderly : natural deaths of S, unvaccinated, elderly : natural deaths of S, unvaccinated, elderly : natural deaths of S, unvaccinated, elderly : natural deaths of S, unvaccinated, elderly : natural deaths of S, unvaccinated, elderly :
    dSuve_mb = -b_Suve_Iuvc*Suve*Iuvc -b_Suve_Iuva*Suve*Iuva -b_Suve_Iuve*Suve*Iuve -b_Suve_Ivc*Suve*Ivc -b_Suve_Iva*Suve*Iva -b_Suve_Ive*Suve*Ive +w_Ruve*Ruve +n -mS_Suve*Suve
    #Susceptible vaccinated children : infection, vaccinated, children : infection, vaccinated, children : infection, vaccinated, children : infection, vaccinated, children : infection, vaccinated, children : infection, vaccinated, children : waning immunity, vaccinated, children : waning immunity, vaccinated, children : waning immunity, vaccinated, children : waning immunity, vaccinated, children : waning immunity, vaccinated, children : waning immunity, vaccinated, children : births, vaccinated, children : births, vaccinated, children : births, vaccinated, children : births, vaccinated, children : births, vaccinated, children : births, vaccinated, children : natural deaths of S, vaccinated, children : natural deaths of S, vaccinated, children : natural deaths of S, vaccinated, children : natural deaths of S, vaccinated, children : natural deaths of S, vaccinated, children : natural deaths of S, vaccinated, children :
    dSvc_mb = -b_Svc_Iuvc*Svc*Iuvc -b_Svc_Iuva*Svc*Iuva -b_Svc_Iuve*Svc*Iuve -b_Svc_Ivc*Svc*Ivc -b_Svc_Iva*Svc*Iva -b_Svc_Ive*Svc*Ive +w_Rvc*Rvc +n -mS_Svc*Svc
    #Susceptible vaccinated adults : infection, vaccinated, adults : infection, vaccinated, adults : infection, vaccinated, adults : infection, vaccinated, adults : infection, vaccinated, adults : infection, vaccinated, adults : waning immunity, vaccinated, adults : waning immunity, vaccinated, adults : waning immunity, vaccinated, adults : waning immunity, vaccinated, adults : waning immunity, vaccinated, adults : waning immunity, vaccinated, adults : births, vaccinated, adults : births, vaccinated, adults : births, vaccinated, adults : births, vaccinated, adults : births, vaccinated, adults : births, vaccinated, adults : natural deaths of S, vaccinated, adults : natural deaths of S, vaccinated, adults : natural deaths of S, vaccinated, adults : natural deaths of S, vaccinated, adults : natural deaths of S, vaccinated, adults : natural deaths of S, vaccinated, adults :
    dSva_mb = -b_Sva_Iuvc*Sva*Iuvc -b_Sva_Iuva*Sva*Iuva -b_Sva_Iuve*Sva*Iuve -b_Sva_Ivc*Sva*Ivc -b_Sva_Iva*Sva*Iva -b_Sva_Ive*Sva*Ive +w_Rva*Rva +n -mS_Sva*Sva
    #Susceptible vaccinated elderly : infection, vaccinated, elderly : infection, vaccinated, elderly : infection, vaccinated, elderly : infection, vaccinated, elderly : infection, vaccinated, elderly : infection, vaccinated, elderly : waning immunity, vaccinated, elderly : waning immunity, vaccinated, elderly : waning immunity, vaccinated, elderly : waning immunity, vaccinated, elderly : waning immunity, vaccinated, elderly : waning immunity, vaccinated, elderly : births, vaccinated, elderly : births, vaccinated, elderly : births, vaccinated, elderly : births, vaccinated, elderly : births, vaccinated, elderly : births, vaccinated, elderly : natural deaths of S, vaccinated, elderly : natural deaths of S, vaccinated, elderly : natural deaths of S, vaccinated, elderly : natural deaths of S, vaccinated, elderly : natural deaths of S, vaccinated, elderly : natural deaths of S, vaccinated, elderly :
    dSve_mb = -b_Sve_Iuvc*Sve*Iuvc -b_Sve_Iuva*Sve*Iuva -b_Sve_Iuve*Sve*Iuve -b_Sve_Ivc*Sve*Ivc -b_Sve_Iva*Sve*Iva -b_Sve_Ive*Sve*Ive +w_Rve*Rve +n -mS_Sve*Sve
    #Infected unvaccinated children : infection, unvaccinated, children : infection, unvaccinated, children : infection, unvaccinated, children : infection, unvaccinated, children : infection, unvaccinated, children : infection, unvaccinated, children : recovery, unvaccinated, children : recovery, unvaccinated, children : recovery, unvaccinated, children : recovery, unvaccinated, children : recovery, unvaccinated, children : recovery, unvaccinated, children : natural deaths of I, unvaccinated, children : natural deaths of I, unvaccinated, children : natural deaths of I, unvaccinated, children : natural deaths of I, unvaccinated, children : natural deaths of I, unvaccinated, children : natural deaths of I, unvaccinated, children :
    dIuvc_mb = +b_Suvc_Iuvc*Suvc*Iuvc +b_Suvc_Iuva*Suvc*Iuva +b_Suvc_Iuve*Suvc*Iuve +b_Suvc_Ivc*Suvc*Ivc +b_Suvc_Iva*Suvc*Iva +b_Suvc_Ive*Suvc*Ive -g_Iuvc*Iuvc -mI_Iuvc*Iuvc
    #Infected unvaccinated adults : infection, unvaccinated, adults : infection, unvaccinated, adults : infection, unvaccinated, adults : infection, unvaccinated, adults : infection, unvaccinated, adults : infection, unvaccinated, adults : recovery, unvaccinated, adults : recovery, unvaccinated, adults : recovery, unvaccinated, adults : recovery, unvaccinated, adults : recovery, unvaccinated, adults : recovery, unvaccinated, adults : natural deaths of I, unvaccinated, adults : natural deaths of I, unvaccinated, adults : natural deaths of I, unvaccinated, adults : natural deaths of I, unvaccinated, adults : natural deaths of I, unvaccinated, adults : natural deaths of I, unvaccinated, adults :
    dIuva_mb = +b_Suva_Iuvc*Suva*Iuvc +b_Suva_Iuva*Suva*Iuva +b_Suva_Iuve*Suva*Iuve +b_Suva_Ivc*Suva*Ivc +b_Suva_Iva*Suva*Iva +b_Suva_Ive*Suva*Ive -g_Iuva*Iuva -mI_Iuva*Iuva
    #Infected unvaccinated elderly : infection, unvaccinated, elderly : infection, unvaccinated, elderly : infection, unvaccinated, elderly : infection, unvaccinated, elderly : infection, unvaccinated, elderly : infection, unvaccinated, elderly : recovery, unvaccinated, elderly : recovery, unvaccinated, elderly : recovery, unvaccinated, elderly : recovery, unvaccinated, elderly : recovery, unvaccinated, elderly : recovery, unvaccinated, elderly : natural deaths of I, unvaccinated, elderly : natural deaths of I, unvaccinated, elderly : natural deaths of I, unvaccinated, elderly : natural deaths of I, unvaccinated, elderly : natural deaths of I, unvaccinated, elderly : natural deaths of I, unvaccinated, elderly :
    dIuve_mb = +b_Suve_Iuvc*Suve*Iuvc +b_Suve_Iuva*Suve*Iuva +b_Suve_Iuve*Suve*Iuve +b_Suve_Ivc*Suve*Ivc +b_Suve_Iva*Suve*Iva +b_Suve_Ive*Suve*Ive -g_Iuve*Iuve -mI_Iuve*Iuve
    #Infected vaccinated children : infection, vaccinated, children : infection, vaccinated, children : infection, vaccinated, children : infection, vaccinated, children : infection, vaccinated, children : infection, vaccinated, children : recovery, vaccinated, children : recovery, vaccinated, children : recovery, vaccinated, children : recovery, vaccinated, children : recovery, vaccinated, children : recovery, vaccinated, children : natural deaths of I, vaccinated, children : natural deaths of I, vaccinated, children : natural deaths of I, vaccinated, children : natural deaths of I, vaccinated, children : natural deaths of I, vaccinated, children : natural deaths of I, vaccinated, children :
    dIvc_mb = +b_Svc_Iuvc*Svc*Iuvc +b_Svc_Iuva*Svc*Iuva +b_Svc_Iuve*Svc*Iuve +b_Svc_Ivc*Svc*Ivc +b_Svc_Iva*Svc*Iva +b_Svc_Ive*Svc*Ive -g_Ivc*Ivc -mI_Ivc*Ivc
    #Infected vaccinated adults : infection, vaccinated, adults : infection, vaccinated, adults : infection, vaccinated, adults : infection, vaccinated, adults : infection, vaccinated, adults : infection, vaccinated, adults : recovery, vaccinated, adults : recovery, vaccinated, adults : recovery, vaccinated, adults : recovery, vaccinated, adults : recovery, vaccinated, adults : recovery, vaccinated, adults : natural deaths of I, vaccinated, adults : natural deaths of I, vaccinated, adults : natural deaths of I, vaccinated, adults : natural deaths of I, vaccinated, adults : natural deaths of I, vaccinated, adults : natural deaths of I, vaccinated, adults :
    dIva_mb = +b_Sva_Iuvc*Sva*Iuvc +b_Sva_Iuva*Sva*Iuva +b_Sva_Iuve*Sva*Iuve +b_Sva_Ivc*Sva*Ivc +b_Sva_Iva*Sva*Iva +b_Sva_Ive*Sva*Ive -g_Iva*Iva -mI_Iva*Iva
    #Infected vaccinated elderly : infection, vaccinated, elderly : infection, vaccinated, elderly : infection, vaccinated, elderly : infection, vaccinated, elderly : infection, vaccinated, elderly : infection, vaccinated, elderly : recovery, vaccinated, elderly : recovery, vaccinated, elderly : recovery, vaccinated, elderly : recovery, vaccinated, elderly : recovery, vaccinated, elderly : recovery, vaccinated, elderly : natural deaths of I, vaccinated, elderly : natural deaths of I, vaccinated, elderly : natural deaths of I, vaccinated, elderly : natural deaths of I, vaccinated, elderly : natural deaths of I, vaccinated, elderly : natural deaths of I, vaccinated, elderly :
    dIve_mb = +b_Sve_Iuvc*Sve*Iuvc +b_Sve_Iuva*Sve*Iuva +b_Sve_Iuve*Sve*Iuve +b_Sve_Ivc*Sve*Ivc +b_Sve_Iva*Sve*Iva +b_Sve_Ive*Sve*Ive -g_Ive*Ive -mI_Ive*Ive
    #Recovered unvaccinated children : recovery, unvaccinated, children : recovery, unvaccinated, children : recovery, unvaccinated, children : recovery, unvaccinated, children : recovery, unvaccinated, children : recovery, unvaccinated, children : waning immunity, unvaccinated, children : waning immunity, unvaccinated, children : waning immunity, unvaccinated, children : waning immunity, unvaccinated, children : waning immunity, unvaccinated, children : waning immunity, unvaccinated, children : natural deaths of R, unvaccinated, children : natural deaths of R, unvaccinated, children : natural deaths of R, unvaccinated, children : natural deaths of R, unvaccinated, children : natural deaths of R, unvaccinated, children : natural deaths of R, unvaccinated, children :
    dRuvc_mb = +g_Iuvc*Iuvc -w_Ruvc*Ruvc -mR_Ruvc*Ruvc
    #Recovered unvaccinated adults : recovery, unvaccinated, adults : recovery, unvaccinated, adults : recovery, unvaccinated, adults : recovery, unvaccinated, adults : recovery, unvaccinated, adults : recovery, unvaccinated, adults : waning immunity, unvaccinated, adults : waning immunity, unvaccinated, adults : waning immunity, unvaccinated, adults : waning immunity, unvaccinated, adults : waning immunity, unvaccinated, adults : waning immunity, unvaccinated, adults : natural deaths of R, unvaccinated, adults : natural deaths of R, unvaccinated, adults : natural deaths of R, unvaccinated, adults : natural deaths of R, unvaccinated, adults : natural deaths of R, unvaccinated, adults : natural deaths of R, unvaccinated, adults :
    dRuva_mb = +g_Iuva*Iuva -w_Ruva*Ruva -mR_Ruva*Ruva
    #Recovered unvaccinated elderly : recovery, unvaccinated, elderly : recovery, unvaccinated, elderly : recovery, unvaccinated, elderly : recovery, unvaccinated, elderly : recovery, unvaccinated, elderly : recovery, unvaccinated, elderly : waning immunity, unvaccinated, elderly : waning immunity, unvaccinated, elderly : waning immunity, unvaccinated, elderly : waning immunity, unvaccinated, elderly : waning immunity, unvaccinated, elderly : waning immunity, unvaccinated, elderly : natural deaths of R, unvaccinated, elderly : natural deaths of R, unvaccinated, elderly : natural deaths of R, unvaccinated, elderly : natural deaths of R, unvaccinated, elderly : natural deaths of R, unvaccinated, elderly : natural deaths of R, unvaccinated, elderly :
    dRuve_mb = +g_Iuve*Iuve -w_Ruve*Ruve -mR_Ruve*Ruve
    #Recovered vaccinated children : recovery, vaccinated, children : recovery, vaccinated, children : recovery, vaccinated, children : recovery, vaccinated, children : recovery, vaccinated, children : recovery, vaccinated, children : waning immunity, vaccinated, children : waning immunity, vaccinated, children : waning immunity, vaccinated, children : waning immunity, vaccinated, children : waning immunity, vaccinated, children : waning immunity, vaccinated, children : natural deaths of R, vaccinated, children : natural deaths of R, vaccinated, children : natural deaths of R, vaccinated, children : natural deaths of R, vaccinated, children : natural deaths of R, vaccinated, children : natural deaths of R, vaccinated, children :
    dRvc_mb = +g_Ivc*Ivc -w_Rvc*Rvc -mR_Rvc*Rvc
    #Recovered vaccinated adults : recovery, vaccinated, adults : recovery, vaccinated, adults : recovery, vaccinated, adults : recovery, vaccinated, adults : recovery, vaccinated, adults : recovery, vaccinated, adults : waning immunity, vaccinated, adults : waning immunity, vaccinated, adults : waning immunity, vaccinated, adults : waning immunity, vaccinated, adults : waning immunity, vaccinated, adults : waning immunity, vaccinated, adults : natural deaths of R, vaccinated, adults : natural deaths of R, vaccinated, adults : natural deaths of R, vaccinated, adults : natural deaths of R, vaccinated, adults : natural deaths of R, vaccinated, adults : natural deaths of R, vaccinated, adults :
    dRva_mb = +g_Iva*Iva -w_Rva*Rva -mR_Rva*Rva
    #Recovered vaccinated elderly : recovery, vaccinated, elderly : recovery, vaccinated, elderly : recovery, vaccinated, elderly : recovery, vaccinated, elderly : recovery, vaccinated, elderly : recovery, vaccinated, elderly : waning immunity, vaccinated, elderly : waning immunity, vaccinated, elderly : waning immunity, vaccinated, elderly : waning immunity, vaccinated, elderly : waning immunity, vaccinated, elderly : waning immunity, vaccinated, elderly : natural deaths of R, vaccinated, elderly : natural deaths of R, vaccinated, elderly : natural deaths of R, vaccinated, elderly : natural deaths of R, vaccinated, elderly : natural deaths of R, vaccinated, elderly : natural deaths of R, vaccinated, elderly :
    dRve_mb = +g_Ive*Ive -w_Rve*Rve -mR_Rve*Rve
    #EndODES
    list(c(dSuvc_mb,dSuva_mb,dSuve_mb,dSvc_mb,dSva_mb,dSve_mb,dIuvc_mb,dIuva_mb,dIuve_mb,dIvc_mb,dIva_mb,dIve_mb,dRuvc_mb,dRuva_mb,dRuve_mb,dRvc_mb,dRva_mb,dRve_mb)) 
  } ) } #close with statement, end ODE code block 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec_mb = c(Suvc = Suvc, Suva = Suva, Suve = Suve, Svc = Svc, Sva = Sva, Sve = Sve, Iuvc = Iuvc, Iuva = Iuva, Iuve = Iuve, Ivc = Ivc, Iva = Iva, Ive = Ive, Ruvc = Ruvc, Ruva = Ruva, Ruve = Ruve, Rvc = Rvc, Rva = Rva, Rve = Rve) 
  parvec_mb = c(b_Suvc_Iuvc = b_Suvc_Iuvc, b_Suvc_Iuva = b_Suvc_Iuva, b_Suvc_Iuve = b_Suvc_Iuve, b_Suvc_Ivc = b_Suvc_Ivc, b_Suvc_Iva = b_Suvc_Iva, b_Suvc_Ive = b_Suvc_Ive, w_Ruvc = w_Ruvc, n = n, mS_Suvc = mS_Suvc, b_Suva_Iuvc = b_Suva_Iuvc, b_Suva_Iuva = b_Suva_Iuva, b_Suva_Iuve = b_Suva_Iuve, b_Suva_Ivc = b_Suva_Ivc, b_Suva_Iva = b_Suva_Iva, b_Suva_Ive = b_Suva_Ive, w_Ruva = w_Ruva, mS_Suva = mS_Suva, b_Suve_Iuvc = b_Suve_Iuvc, b_Suve_Iuva = b_Suve_Iuva, b_Suve_Iuve = b_Suve_Iuve, b_Suve_Ivc = b_Suve_Ivc, b_Suve_Iva = b_Suve_Iva, b_Suve_Ive = b_Suve_Ive, w_Ruve = w_Ruve, mS_Suve = mS_Suve, b_Svc_Iuvc = b_Svc_Iuvc, b_Svc_Iuva = b_Svc_Iuva, b_Svc_Iuve = b_Svc_Iuve, b_Svc_Ivc = b_Svc_Ivc, b_Svc_Iva = b_Svc_Iva, b_Svc_Ive = b_Svc_Ive, w_Rvc = w_Rvc, mS_Svc = mS_Svc, b_Sva_Iuvc = b_Sva_Iuvc, b_Sva_Iuva = b_Sva_Iuva, b_Sva_Iuve = b_Sva_Iuve, b_Sva_Ivc = b_Sva_Ivc, b_Sva_Iva = b_Sva_Iva, b_Sva_Ive = b_Sva_Ive, w_Rva = w_Rva, mS_Sva = mS_Sva, b_Sve_Iuvc = b_Sve_Iuvc, b_Sve_Iuva = b_Sve_Iuva, b_Sve_Iuve = b_Sve_Iuve, b_Sve_Ivc = b_Sve_Ivc, b_Sve_Iva = b_Sve_Iva, b_Sve_Ive = b_Sve_Ive, w_Rve = w_Rve, mS_Sve = mS_Sve, g_Iuvc = g_Iuvc, mI_Iuvc = mI_Iuvc, g_Iuva = g_Iuva, mI_Iuva = mI_Iuva, g_Iuve = g_Iuve, mI_Iuve = mI_Iuve, g_Ivc = g_Ivc, mI_Ivc = mI_Ivc, g_Iva = g_Iva, mI_Iva = mI_Iva, g_Ive = g_Ive, mI_Ive = mI_Ive, mR_Ruvc = mR_Ruvc, mR_Ruva = mR_Ruva, mR_Ruve = mR_Ruve, mR_Rvc = mR_Rvc, mR_Rva = mR_Rva, mR_Rve = mR_Rve) 
  timevec_mb = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout = deSolve::ode(y = varvec_mb, parms = parvec_mb, times = timevec_mb,  func = SIRSd2_vaccine_age_ode_fct, rtol = 1e-12, atol = 1e-12) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
} 
