#' Coronavirus_vaccine_model_v2_stratified
#' 
#' @description A model with 7 compartments
#' 
#' @details The model includes susceptible, presymptomatic, asymptomatic, infected/symptomatic/ill, recovered, hospitalized, and deceased compartments. The processes that are modeled are infection, progression to infectiousness, recovery, and progression to hospitalization and death. Immunity is permanent. Demographics through natural births and deaths are not included.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of ordinary differential equations using the deSolve package. 
#' The following R packages need to be loaded for the function to work: deSolve. 
#' 
#' Starting conditions for model variables 
#' @param S_c_h : starting value for Susceptible children high risk : numeric
#' @param P_c_h : starting value for Presymptomatic children high risk : numeric
#' @param A_c_h : starting value for Asymptomatic children high risk : numeric
#' @param I_c_h : starting value for Ill children high risk : numeric
#' @param H_c_h : starting value for Hospitalized children high risk : numeric
#' @param R_c_h : starting value for Recovered children high risk : numeric
#' @param D_c_h : starting value for Deceased children high risk : numeric
#' @param S_a_h : starting value for Susceptible adults high risk : numeric
#' @param P_a_h : starting value for Presymptomatic adults high risk : numeric
#' @param A_a_h : starting value for Asymptomatic adults high risk : numeric
#' @param I_a_h : starting value for Ill adults high risk : numeric
#' @param H_a_h : starting value for Hospitalized adults high risk : numeric
#' @param R_a_h : starting value for Recovered adults high risk : numeric
#' @param D_a_h : starting value for Deceased adults high risk : numeric
#' @param S_e_h : starting value for Susceptible elderly high risk : numeric
#' @param P_e_h : starting value for Presymptomatic elderly high risk : numeric
#' @param A_e_h : starting value for Asymptomatic elderly high risk : numeric
#' @param I_e_h : starting value for Ill elderly high risk : numeric
#' @param H_e_h : starting value for Hospitalized elderly high risk : numeric
#' @param R_e_h : starting value for Recovered elderly high risk : numeric
#' @param D_e_h : starting value for Deceased elderly high risk : numeric
#' @param S_c_l : starting value for Susceptible children low risk : numeric
#' @param P_c_l : starting value for Presymptomatic children low risk : numeric
#' @param A_c_l : starting value for Asymptomatic children low risk : numeric
#' @param I_c_l : starting value for Ill children low risk : numeric
#' @param H_c_l : starting value for Hospitalized children low risk : numeric
#' @param R_c_l : starting value for Recovered children low risk : numeric
#' @param D_c_l : starting value for Deceased children low risk : numeric
#' @param S_a_l : starting value for Susceptible adults low risk : numeric
#' @param P_a_l : starting value for Presymptomatic adults low risk : numeric
#' @param A_a_l : starting value for Asymptomatic adults low risk : numeric
#' @param I_a_l : starting value for Ill adults low risk : numeric
#' @param H_a_l : starting value for Hospitalized adults low risk : numeric
#' @param R_a_l : starting value for Recovered adults low risk : numeric
#' @param D_a_l : starting value for Deceased adults low risk : numeric
#' @param S_e_l : starting value for Susceptible elderly low risk : numeric
#' @param P_e_l : starting value for Presymptomatic elderly low risk : numeric
#' @param A_e_l : starting value for Asymptomatic elderly low risk : numeric
#' @param I_e_l : starting value for Ill elderly low risk : numeric
#' @param H_e_l : starting value for Hospitalized elderly low risk : numeric
#' @param R_e_l : starting value for Recovered elderly low risk : numeric
#' @param D_e_l : starting value for Deceased elderly low risk : numeric
#' Values for model parameters : numeric 
#' @param bP_c_h : transmission by presymptomatis, children, high risk : numeric
#' @param bA_c_h : transmission by asymptomatic, children, high risk : numeric
#' @param bI_c_h : transmission by ill, children, high risk : numeric
#' @param nu_c_h : fraction symptomatic, children, high risk : numeric
#' @param sigma_c_h : progression to symptomatic, children, high risk : numeric
#' @param gammaA_c_h : recovery of asymptomatic, children, high risk : numeric
#' @param gammaI_c_h : leaving the symptomatic class, children, high risk : numeric
#' @param gammaH_c_h : leaving the hospitalized class, children, high risk : numeric
#' @param phi_c_h : fraction of symptomatics hospitalized, children, high risk : numeric
#' @param rho_c_h : fraction of hospitalized deceased, children, high risk : numeric
#' @param bP_a_h : transmission by presymptomatis, adults, high risk : numeric
#' @param bA_a_h : transmission by asymptomatic, adults, high risk : numeric
#' @param bI_a_h : transmission by ill, adults, high risk : numeric
#' @param nu_a_h : fraction symptomatic, adults, high risk : numeric
#' @param sigma_a_h : progression to symptomatic, adults, high risk : numeric
#' @param gammaA_a_h : recovery of asymptomatic, adults, high risk : numeric
#' @param gammaI_a_h : leaving the symptomatic class, adults, high risk : numeric
#' @param gammaH_a_h : leaving the hospitalized class, adults, high risk : numeric
#' @param phi_a_h : fraction of symptomatics hospitalized, adults, high risk : numeric
#' @param rho_a_h : fraction of hospitalized deceased, adults, high risk : numeric
#' @param bP_e_h : transmission by presymptomatis, elderly, high risk : numeric
#' @param bA_e_h : transmission by asymptomatic, elderly, high risk : numeric
#' @param bI_e_h : transmission by ill, elderly, high risk : numeric
#' @param nu_e_h : fraction symptomatic, elderly, high risk : numeric
#' @param sigma_e_h : progression to symptomatic, elderly, high risk : numeric
#' @param gammaA_e_h : recovery of asymptomatic, elderly, high risk : numeric
#' @param gammaI_e_h : leaving the symptomatic class, elderly, high risk : numeric
#' @param gammaH_e_h : leaving the hospitalized class, elderly, high risk : numeric
#' @param phi_e_h : fraction of symptomatics hospitalized, elderly, high risk : numeric
#' @param rho_e_h : fraction of hospitalized deceased, elderly, high risk : numeric
#' @param bP_c_l : transmission by presymptomatis, children, low risk : numeric
#' @param bA_c_l : transmission by asymptomatic, children, low risk : numeric
#' @param bI_c_l : transmission by ill, children, low risk : numeric
#' @param nu_c_l : fraction symptomatic, children, low risk : numeric
#' @param sigma_c_l : progression to symptomatic, children, low risk : numeric
#' @param gammaA_c_l : recovery of asymptomatic, children, low risk : numeric
#' @param gammaI_c_l : leaving the symptomatic class, children, low risk : numeric
#' @param gammaH_c_l : leaving the hospitalized class, children, low risk : numeric
#' @param phi_c_l : fraction of symptomatics hospitalized, children, low risk : numeric
#' @param rho_c_l : fraction of hospitalized deceased, children, low risk : numeric
#' @param bP_a_l : transmission by presymptomatis, adults, low risk : numeric
#' @param bA_a_l : transmission by asymptomatic, adults, low risk : numeric
#' @param bI_a_l : transmission by ill, adults, low risk : numeric
#' @param nu_a_l : fraction symptomatic, adults, low risk : numeric
#' @param sigma_a_l : progression to symptomatic, adults, low risk : numeric
#' @param gammaA_a_l : recovery of asymptomatic, adults, low risk : numeric
#' @param gammaI_a_l : leaving the symptomatic class, adults, low risk : numeric
#' @param gammaH_a_l : leaving the hospitalized class, adults, low risk : numeric
#' @param phi_a_l : fraction of symptomatics hospitalized, adults, low risk : numeric
#' @param rho_a_l : fraction of hospitalized deceased, adults, low risk : numeric
#' @param bP_e_l : transmission by presymptomatis, elderly, low risk : numeric
#' @param bA_e_l : transmission by asymptomatic, elderly, low risk : numeric
#' @param bI_e_l : transmission by ill, elderly, low risk : numeric
#' @param nu_e_l : fraction symptomatic, elderly, low risk : numeric
#' @param sigma_e_l : progression to symptomatic, elderly, low risk : numeric
#' @param gammaA_e_l : recovery of asymptomatic, elderly, low risk : numeric
#' @param gammaI_e_l : leaving the symptomatic class, elderly, low risk : numeric
#' @param gammaH_e_l : leaving the hospitalized class, elderly, low risk : numeric
#' @param phi_e_l : fraction of symptomatics hospitalized, elderly, low risk : numeric
#' @param rho_e_l : fraction of hospitalized deceased, elderly, low risk : numeric
#' Values for model times : numeric 
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Coronavirus_vaccine_model_v2_stratified_ode() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Coronavirus_vaccine_model_v2_stratified_ode(S_c_h = 2000,P_c_h = 2,A_c_h = 2,I_c_h = 2,H_c_h = 0,R_c_h = 0,D_c_h = 0,S_a_h = 2000,P_a_h = 2,A_a_h = 2,I_a_h = 2,H_a_h = 0,R_a_h = 0,D_a_h = 0,S_e_h = 2000,P_e_h = 2,A_e_h = 2,I_e_h = 2,H_e_h = 0,R_e_h = 0,D_e_h = 0,S_c_l = 2000,P_c_l = 2,A_c_l = 2,I_c_l = 2,H_c_l = 0,R_c_l = 0,D_c_l = 0,S_a_l = 2000,P_a_l = 2,A_a_l = 2,I_a_l = 2,H_a_l = 0,R_a_l = 0,D_a_l = 0,S_e_l = 2000,P_e_l = 2,A_e_l = 2,I_e_l = 2,H_e_l = 0,R_e_l = 0,D_e_l = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S_c_h'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S_c_h: ',max(result$ts[,'S_c_h']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: COVAMOD consortium
#' @section Model creation date: 18526
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2020-09-22
#' @export 
 
simulate_Coronavirus_vaccine_model_v2_stratified_ode <- function(S_c_h = 1000, P_c_h = 1, A_c_h = 1, I_c_h = 1, H_c_h = 0, R_c_h = 0, D_c_h = 0, S_a_h = 1000, P_a_h = 1, A_a_h = 1, I_a_h = 1, H_a_h = 0, R_a_h = 0, D_a_h = 0, S_e_h = 1000, P_e_h = 1, A_e_h = 1, I_e_h = 1, H_e_h = 0, R_e_h = 0, D_e_h = 0, S_c_l = 1000, P_c_l = 1, A_c_l = 1, I_c_l = 1, H_c_l = 0, R_c_l = 0, D_c_l = 0, S_a_l = 1000, P_a_l = 1, A_a_l = 1, I_a_l = 1, H_a_l = 0, R_a_l = 0, D_a_l = 0, S_e_l = 1000, P_e_l = 1, A_e_l = 1, I_e_l = 1, H_e_l = 0, R_e_l = 0, D_e_l = 0, bP_c_h = 0.001, bA_c_h = 5e-04, bI_c_h = 0.001, nu_c_h = 0.3, sigma_c_h = 0.2, gammaA_c_h = 0.125, gammaI_c_h = 0.1, gammaH_c_h = 0.2, phi_c_h = 0.05, rho_c_h = 0.01, bP_a_h = 0.001, bA_a_h = 5e-04, bI_a_h = 0.001, nu_a_h = 0.3, sigma_a_h = 0.2, gammaA_a_h = 0.125, gammaI_a_h = 0.1, gammaH_a_h = 0.2, phi_a_h = 0.05, rho_a_h = 0.01, bP_e_h = 0.001, bA_e_h = 5e-04, bI_e_h = 0.001, nu_e_h = 0.3, sigma_e_h = 0.2, gammaA_e_h = 0.125, gammaI_e_h = 0.1, gammaH_e_h = 0.2, phi_e_h = 0.05, rho_e_h = 0.01, bP_c_l = 0.001, bA_c_l = 5e-04, bI_c_l = 0.001, nu_c_l = 0.3, sigma_c_l = 0.2, gammaA_c_l = 0.125, gammaI_c_l = 0.1, gammaH_c_l = 0.2, phi_c_l = 0.05, rho_c_l = 0.01, bP_a_l = 0.001, bA_a_l = 5e-04, bI_a_l = 0.001, nu_a_l = 0.3, sigma_a_l = 0.2, gammaA_a_l = 0.125, gammaI_a_l = 0.1, gammaH_a_l = 0.2, phi_a_l = 0.05, rho_a_l = 0.01, bP_e_l = 0.001, bA_e_l = 5e-04, bI_e_l = 0.001, nu_e_l = 0.3, sigma_e_l = 0.2, gammaA_e_l = 0.125, gammaI_e_l = 0.1, gammaH_e_l = 0.2, phi_e_l = 0.05, rho_e_l = 0.01, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  ############################## 
  #Block of ODE equations for deSolve 
  ############################## 
  Coronavirus_vaccine_model_v2_stratified_ode_fct <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible children high risk : infection by presymptomatic leading to symptomatic infections, children, high risk : infection by presymptomatic leading to asymptomatic infections, children, high risk : infection by asymptomatic leading to symptomatic infections, children, high risk : infection by asymptomatic leading to asymptomatic infections, children, high risk : infection by symptomatic leading to symptomatic infections, children, high risk : infection by symptomatic leading to asymptomatic infections, children, high risk :
    dS_c_h_mb = -nu_c_h*bP_c_h*S_c_h*P_c_h-nu_a_h*bP_a_h*S_c_h*P_a_h-nu_e_h*bP_e_h*S_c_h*P_e_h-nu_c_l*bP_c_l*S_c_h*P_c_l-nu_a_l*bP_a_l*S_c_h*P_a_l-nu_e_l*bP_e_l*S_c_h*P_e_l -(1-nu_c_h)*bP_c_h*S_c_h*P_c_h-(1-nu_a_h)*bP_a_h*S_c_h*P_a_h-(1-nu_e_h)*bP_e_h*S_c_h*P_e_h-(1-nu_c_l)*bP_c_l*S_c_h*P_c_l-(1-nu_a_l)*bP_a_l*S_c_h*P_a_l-(1-nu_e_l)*bP_e_l*S_c_h*P_e_l -nu_c_h*bA_c_h*S_c_h*A_c_h-nu_a_h*bA_a_h*S_c_h*A_a_h-nu_e_h*bA_e_h*S_c_h*A_e_h-nu_c_l*bA_c_l*S_c_h*A_c_l-nu_a_l*bA_a_l*S_c_h*A_a_l-nu_e_l*bA_e_l*S_c_h*A_e_l -(1-nu_c_h)*bA_c_h*S_c_h*A_c_h-(1-nu_a_h)*bA_a_h*S_c_h*A_a_h-(1-nu_e_h)*bA_e_h*S_c_h*A_e_h-(1-nu_c_l)*bA_c_l*S_c_h*A_c_l-(1-nu_a_l)*bA_a_l*S_c_h*A_a_l-(1-nu_e_l)*bA_e_l*S_c_h*A_e_l -nu_c_h*bI_c_h*S_c_h*I_c_h-nu_a_h*bI_a_h*S_c_h*I_a_h-nu_e_h*bI_e_h*S_c_h*I_e_h-nu_c_l*bI_c_l*S_c_h*I_c_l-nu_a_l*bI_a_l*S_c_h*I_a_l-nu_e_l*bI_e_l*S_c_h*I_e_l -(1-nu_c_h)*bI_c_h*S_c_h*I_c_h-(1-nu_a_h)*bI_a_h*S_c_h*I_a_h-(1-nu_e_h)*bI_e_h*S_c_h*I_e_h-(1-nu_c_l)*bI_c_l*S_c_h*I_c_l-(1-nu_a_l)*bI_a_l*S_c_h*I_a_l-(1-nu_e_l)*bI_e_l*S_c_h*I_e_l
    #Presymptomatic children high risk : infection by presymptomatic, children, high risk : infection by ill, children, high risk : infection by asymptomatic, children, high risk : progression to symptoms, children, high risk :
    dP_c_h_mb = +nu_c_h*bP_c_h*S_c_h*P_c_h+nu_a_h*bP_a_h*S_c_h*P_a_h+nu_e_h*bP_e_h*S_c_h*P_e_h+nu_c_l*bP_c_l*S_c_h*P_c_l+nu_a_l*bP_a_l*S_c_h*P_a_l+nu_e_l*bP_e_l*S_c_h*P_e_l +nu_c_h*bA_c_h*S_c_h*A_c_h+nu_a_h*bA_a_h*S_c_h*A_a_h+nu_e_h*bA_e_h*S_c_h*A_e_h+nu_c_l*bA_c_l*S_c_h*A_c_l+nu_a_l*bA_a_l*S_c_h*A_a_l+nu_e_l*bA_e_l*S_c_h*A_e_l +nu_c_h*bI_c_h*S_c_h*I_c_h+nu_a_h*bI_a_h*S_c_h*I_a_h+nu_e_h*bI_e_h*S_c_h*I_e_h+nu_c_l*bI_c_l*S_c_h*I_c_l+nu_a_l*bI_a_l*S_c_h*I_a_l+nu_e_l*bI_e_l*S_c_h*I_e_l -sigma_c_h*P_c_h
    #Asymptomatic children high risk : infection by presymptomatic, children, high risk : infection by ill, children, high risk : infection by asymptomatic, children, high risk : recovery, children, high risk :
    dA_c_h_mb = +(1-nu_c_h)*bP_c_h*S_c_h*P_c_h+(1-nu_a_h)*bP_a_h*S_c_h*P_a_h+(1-nu_e_h)*bP_e_h*S_c_h*P_e_h+(1-nu_c_l)*bP_c_l*S_c_h*P_c_l+(1-nu_a_l)*bP_a_l*S_c_h*P_a_l+(1-nu_e_l)*bP_e_l*S_c_h*P_e_l +(1-nu_c_h)*bA_c_h*S_c_h*A_c_h+(1-nu_a_h)*bA_a_h*S_c_h*A_a_h+(1-nu_e_h)*bA_e_h*S_c_h*A_e_h+(1-nu_c_l)*bA_c_l*S_c_h*A_c_l+(1-nu_a_l)*bA_a_l*S_c_h*A_a_l+(1-nu_e_l)*bA_e_l*S_c_h*A_e_l +(1-nu_c_h)*bI_c_h*S_c_h*I_c_h+(1-nu_a_h)*bI_a_h*S_c_h*I_a_h+(1-nu_e_h)*bI_e_h*S_c_h*I_e_h+(1-nu_c_l)*bI_c_l*S_c_h*I_c_l+(1-nu_a_l)*bI_a_l*S_c_h*I_a_l+(1-nu_e_l)*bI_e_l*S_c_h*I_e_l -gammaA_c_h*A_c_h
    #Ill children high risk : progression to symptoms, children, high risk : progression to hospitalization, children, high risk : progression to recovery, children, high risk :
    dI_c_h_mb = +sigma_c_h*P_c_h -phi_c_h*gammaI_c_h*I_c_h -(1-phi_c_h)*gammaI_c_h*I_c_h
    #Hospitalized children high risk : progression to hospitalization, children, high risk : progression to death, children, high risk : progression to recovery, children, high risk :
    dH_c_h_mb = +phi_c_h*gammaI_c_h*I_c_h -rho_c_h*gammaH_c_h*H_c_h -(1-rho_c_h)*gammaH_c_h*H_c_h
    #Recovered children high risk : recovery of asymptomatics, children, high risk : recovery of ill, children, high risk : recovery of hospitalized, children, high risk :
    dR_c_h_mb = +gammaA_c_h*A_c_h +(1-phi_c_h)*gammaI_c_h*I_c_h +(1-rho_c_h)*gammaH_c_h*H_c_h
    #Deceased children high risk : death, children, high risk :
    dD_c_h_mb = +rho_c_h*gammaH_c_h*H_c_h
    #Susceptible adults high risk : infection by presymptomatic leading to symptomatic infections, adults, high risk : infection by presymptomatic leading to asymptomatic infections, adults, high risk : infection by asymptomatic leading to symptomatic infections, adults, high risk : infection by asymptomatic leading to asymptomatic infections, adults, high risk : infection by symptomatic leading to symptomatic infections, adults, high risk : infection by symptomatic leading to asymptomatic infections, adults, high risk :
    dS_a_h_mb = -nu_c_h*bP_c_h*S_a_h*P_c_h-nu_a_h*bP_a_h*S_a_h*P_a_h-nu_e_h*bP_e_h*S_a_h*P_e_h-nu_c_l*bP_c_l*S_a_h*P_c_l-nu_a_l*bP_a_l*S_a_h*P_a_l-nu_e_l*bP_e_l*S_a_h*P_e_l -(1-nu_c_h)*bP_c_h*S_a_h*P_c_h-(1-nu_a_h)*bP_a_h*S_a_h*P_a_h-(1-nu_e_h)*bP_e_h*S_a_h*P_e_h-(1-nu_c_l)*bP_c_l*S_a_h*P_c_l-(1-nu_a_l)*bP_a_l*S_a_h*P_a_l-(1-nu_e_l)*bP_e_l*S_a_h*P_e_l -nu_c_h*bA_c_h*S_a_h*A_c_h-nu_a_h*bA_a_h*S_a_h*A_a_h-nu_e_h*bA_e_h*S_a_h*A_e_h-nu_c_l*bA_c_l*S_a_h*A_c_l-nu_a_l*bA_a_l*S_a_h*A_a_l-nu_e_l*bA_e_l*S_a_h*A_e_l -(1-nu_c_h)*bA_c_h*S_a_h*A_c_h-(1-nu_a_h)*bA_a_h*S_a_h*A_a_h-(1-nu_e_h)*bA_e_h*S_a_h*A_e_h-(1-nu_c_l)*bA_c_l*S_a_h*A_c_l-(1-nu_a_l)*bA_a_l*S_a_h*A_a_l-(1-nu_e_l)*bA_e_l*S_a_h*A_e_l -nu_c_h*bI_c_h*S_a_h*I_c_h-nu_a_h*bI_a_h*S_a_h*I_a_h-nu_e_h*bI_e_h*S_a_h*I_e_h-nu_c_l*bI_c_l*S_a_h*I_c_l-nu_a_l*bI_a_l*S_a_h*I_a_l-nu_e_l*bI_e_l*S_a_h*I_e_l -(1-nu_c_h)*bI_c_h*S_a_h*I_c_h-(1-nu_a_h)*bI_a_h*S_a_h*I_a_h-(1-nu_e_h)*bI_e_h*S_a_h*I_e_h-(1-nu_c_l)*bI_c_l*S_a_h*I_c_l-(1-nu_a_l)*bI_a_l*S_a_h*I_a_l-(1-nu_e_l)*bI_e_l*S_a_h*I_e_l
    #Presymptomatic adults high risk : infection by presymptomatic, adults, high risk : infection by ill, adults, high risk : infection by asymptomatic, adults, high risk : progression to symptoms, adults, high risk :
    dP_a_h_mb = +nu_c_h*bP_c_h*S_a_h*P_c_h+nu_a_h*bP_a_h*S_a_h*P_a_h+nu_e_h*bP_e_h*S_a_h*P_e_h+nu_c_l*bP_c_l*S_a_h*P_c_l+nu_a_l*bP_a_l*S_a_h*P_a_l+nu_e_l*bP_e_l*S_a_h*P_e_l +nu_c_h*bA_c_h*S_a_h*A_c_h+nu_a_h*bA_a_h*S_a_h*A_a_h+nu_e_h*bA_e_h*S_a_h*A_e_h+nu_c_l*bA_c_l*S_a_h*A_c_l+nu_a_l*bA_a_l*S_a_h*A_a_l+nu_e_l*bA_e_l*S_a_h*A_e_l +nu_c_h*bI_c_h*S_a_h*I_c_h+nu_a_h*bI_a_h*S_a_h*I_a_h+nu_e_h*bI_e_h*S_a_h*I_e_h+nu_c_l*bI_c_l*S_a_h*I_c_l+nu_a_l*bI_a_l*S_a_h*I_a_l+nu_e_l*bI_e_l*S_a_h*I_e_l -sigma_a_h*P_a_h
    #Asymptomatic adults high risk : infection by presymptomatic, adults, high risk : infection by ill, adults, high risk : infection by asymptomatic, adults, high risk : recovery, adults, high risk :
    dA_a_h_mb = +(1-nu_c_h)*bP_c_h*S_a_h*P_c_h+(1-nu_a_h)*bP_a_h*S_a_h*P_a_h+(1-nu_e_h)*bP_e_h*S_a_h*P_e_h+(1-nu_c_l)*bP_c_l*S_a_h*P_c_l+(1-nu_a_l)*bP_a_l*S_a_h*P_a_l+(1-nu_e_l)*bP_e_l*S_a_h*P_e_l +(1-nu_c_h)*bA_c_h*S_a_h*A_c_h+(1-nu_a_h)*bA_a_h*S_a_h*A_a_h+(1-nu_e_h)*bA_e_h*S_a_h*A_e_h+(1-nu_c_l)*bA_c_l*S_a_h*A_c_l+(1-nu_a_l)*bA_a_l*S_a_h*A_a_l+(1-nu_e_l)*bA_e_l*S_a_h*A_e_l +(1-nu_c_h)*bI_c_h*S_a_h*I_c_h+(1-nu_a_h)*bI_a_h*S_a_h*I_a_h+(1-nu_e_h)*bI_e_h*S_a_h*I_e_h+(1-nu_c_l)*bI_c_l*S_a_h*I_c_l+(1-nu_a_l)*bI_a_l*S_a_h*I_a_l+(1-nu_e_l)*bI_e_l*S_a_h*I_e_l -gammaA_a_h*A_a_h
    #Ill adults high risk : progression to symptoms, adults, high risk : progression to hospitalization, adults, high risk : progression to recovery, adults, high risk :
    dI_a_h_mb = +sigma_a_h*P_a_h -phi_a_h*gammaI_a_h*I_a_h -(1-phi_a_h)*gammaI_a_h*I_a_h
    #Hospitalized adults high risk : progression to hospitalization, adults, high risk : progression to death, adults, high risk : progression to recovery, adults, high risk :
    dH_a_h_mb = +phi_a_h*gammaI_a_h*I_a_h -rho_a_h*gammaH_a_h*H_a_h -(1-rho_a_h)*gammaH_a_h*H_a_h
    #Recovered adults high risk : recovery of asymptomatics, adults, high risk : recovery of ill, adults, high risk : recovery of hospitalized, adults, high risk :
    dR_a_h_mb = +gammaA_a_h*A_a_h +(1-phi_a_h)*gammaI_a_h*I_a_h +(1-rho_a_h)*gammaH_a_h*H_a_h
    #Deceased adults high risk : death, adults, high risk :
    dD_a_h_mb = +rho_a_h*gammaH_a_h*H_a_h
    #Susceptible elderly high risk : infection by presymptomatic leading to symptomatic infections, elderly, high risk : infection by presymptomatic leading to asymptomatic infections, elderly, high risk : infection by asymptomatic leading to symptomatic infections, elderly, high risk : infection by asymptomatic leading to asymptomatic infections, elderly, high risk : infection by symptomatic leading to symptomatic infections, elderly, high risk : infection by symptomatic leading to asymptomatic infections, elderly, high risk :
    dS_e_h_mb = -nu_c_h*bP_c_h*S_e_h*P_c_h-nu_a_h*bP_a_h*S_e_h*P_a_h-nu_e_h*bP_e_h*S_e_h*P_e_h-nu_c_l*bP_c_l*S_e_h*P_c_l-nu_a_l*bP_a_l*S_e_h*P_a_l-nu_e_l*bP_e_l*S_e_h*P_e_l -(1-nu_c_h)*bP_c_h*S_e_h*P_c_h-(1-nu_a_h)*bP_a_h*S_e_h*P_a_h-(1-nu_e_h)*bP_e_h*S_e_h*P_e_h-(1-nu_c_l)*bP_c_l*S_e_h*P_c_l-(1-nu_a_l)*bP_a_l*S_e_h*P_a_l-(1-nu_e_l)*bP_e_l*S_e_h*P_e_l -nu_c_h*bA_c_h*S_e_h*A_c_h-nu_a_h*bA_a_h*S_e_h*A_a_h-nu_e_h*bA_e_h*S_e_h*A_e_h-nu_c_l*bA_c_l*S_e_h*A_c_l-nu_a_l*bA_a_l*S_e_h*A_a_l-nu_e_l*bA_e_l*S_e_h*A_e_l -(1-nu_c_h)*bA_c_h*S_e_h*A_c_h-(1-nu_a_h)*bA_a_h*S_e_h*A_a_h-(1-nu_e_h)*bA_e_h*S_e_h*A_e_h-(1-nu_c_l)*bA_c_l*S_e_h*A_c_l-(1-nu_a_l)*bA_a_l*S_e_h*A_a_l-(1-nu_e_l)*bA_e_l*S_e_h*A_e_l -nu_c_h*bI_c_h*S_e_h*I_c_h-nu_a_h*bI_a_h*S_e_h*I_a_h-nu_e_h*bI_e_h*S_e_h*I_e_h-nu_c_l*bI_c_l*S_e_h*I_c_l-nu_a_l*bI_a_l*S_e_h*I_a_l-nu_e_l*bI_e_l*S_e_h*I_e_l -(1-nu_c_h)*bI_c_h*S_e_h*I_c_h-(1-nu_a_h)*bI_a_h*S_e_h*I_a_h-(1-nu_e_h)*bI_e_h*S_e_h*I_e_h-(1-nu_c_l)*bI_c_l*S_e_h*I_c_l-(1-nu_a_l)*bI_a_l*S_e_h*I_a_l-(1-nu_e_l)*bI_e_l*S_e_h*I_e_l
    #Presymptomatic elderly high risk : infection by presymptomatic, elderly, high risk : infection by ill, elderly, high risk : infection by asymptomatic, elderly, high risk : progression to symptoms, elderly, high risk :
    dP_e_h_mb = +nu_c_h*bP_c_h*S_e_h*P_c_h+nu_a_h*bP_a_h*S_e_h*P_a_h+nu_e_h*bP_e_h*S_e_h*P_e_h+nu_c_l*bP_c_l*S_e_h*P_c_l+nu_a_l*bP_a_l*S_e_h*P_a_l+nu_e_l*bP_e_l*S_e_h*P_e_l +nu_c_h*bA_c_h*S_e_h*A_c_h+nu_a_h*bA_a_h*S_e_h*A_a_h+nu_e_h*bA_e_h*S_e_h*A_e_h+nu_c_l*bA_c_l*S_e_h*A_c_l+nu_a_l*bA_a_l*S_e_h*A_a_l+nu_e_l*bA_e_l*S_e_h*A_e_l +nu_c_h*bI_c_h*S_e_h*I_c_h+nu_a_h*bI_a_h*S_e_h*I_a_h+nu_e_h*bI_e_h*S_e_h*I_e_h+nu_c_l*bI_c_l*S_e_h*I_c_l+nu_a_l*bI_a_l*S_e_h*I_a_l+nu_e_l*bI_e_l*S_e_h*I_e_l -sigma_e_h*P_e_h
    #Asymptomatic elderly high risk : infection by presymptomatic, elderly, high risk : infection by ill, elderly, high risk : infection by asymptomatic, elderly, high risk : recovery, elderly, high risk :
    dA_e_h_mb = +(1-nu_c_h)*bP_c_h*S_e_h*P_c_h+(1-nu_a_h)*bP_a_h*S_e_h*P_a_h+(1-nu_e_h)*bP_e_h*S_e_h*P_e_h+(1-nu_c_l)*bP_c_l*S_e_h*P_c_l+(1-nu_a_l)*bP_a_l*S_e_h*P_a_l+(1-nu_e_l)*bP_e_l*S_e_h*P_e_l +(1-nu_c_h)*bA_c_h*S_e_h*A_c_h+(1-nu_a_h)*bA_a_h*S_e_h*A_a_h+(1-nu_e_h)*bA_e_h*S_e_h*A_e_h+(1-nu_c_l)*bA_c_l*S_e_h*A_c_l+(1-nu_a_l)*bA_a_l*S_e_h*A_a_l+(1-nu_e_l)*bA_e_l*S_e_h*A_e_l +(1-nu_c_h)*bI_c_h*S_e_h*I_c_h+(1-nu_a_h)*bI_a_h*S_e_h*I_a_h+(1-nu_e_h)*bI_e_h*S_e_h*I_e_h+(1-nu_c_l)*bI_c_l*S_e_h*I_c_l+(1-nu_a_l)*bI_a_l*S_e_h*I_a_l+(1-nu_e_l)*bI_e_l*S_e_h*I_e_l -gammaA_e_h*A_e_h
    #Ill elderly high risk : progression to symptoms, elderly, high risk : progression to hospitalization, elderly, high risk : progression to recovery, elderly, high risk :
    dI_e_h_mb = +sigma_e_h*P_e_h -phi_e_h*gammaI_e_h*I_e_h -(1-phi_e_h)*gammaI_e_h*I_e_h
    #Hospitalized elderly high risk : progression to hospitalization, elderly, high risk : progression to death, elderly, high risk : progression to recovery, elderly, high risk :
    dH_e_h_mb = +phi_e_h*gammaI_e_h*I_e_h -rho_e_h*gammaH_e_h*H_e_h -(1-rho_e_h)*gammaH_e_h*H_e_h
    #Recovered elderly high risk : recovery of asymptomatics, elderly, high risk : recovery of ill, elderly, high risk : recovery of hospitalized, elderly, high risk :
    dR_e_h_mb = +gammaA_e_h*A_e_h +(1-phi_e_h)*gammaI_e_h*I_e_h +(1-rho_e_h)*gammaH_e_h*H_e_h
    #Deceased elderly high risk : death, elderly, high risk :
    dD_e_h_mb = +rho_e_h*gammaH_e_h*H_e_h
    #Susceptible children low risk : infection by presymptomatic leading to symptomatic infections, children, low risk : infection by presymptomatic leading to asymptomatic infections, children, low risk : infection by asymptomatic leading to symptomatic infections, children, low risk : infection by asymptomatic leading to asymptomatic infections, children, low risk : infection by symptomatic leading to symptomatic infections, children, low risk : infection by symptomatic leading to asymptomatic infections, children, low risk :
    dS_c_l_mb = -nu_c_h*bP_c_h*S_c_l*P_c_h-nu_a_h*bP_a_h*S_c_l*P_a_h-nu_e_h*bP_e_h*S_c_l*P_e_h-nu_c_l*bP_c_l*S_c_l*P_c_l-nu_a_l*bP_a_l*S_c_l*P_a_l-nu_e_l*bP_e_l*S_c_l*P_e_l -(1-nu_c_h)*bP_c_h*S_c_l*P_c_h-(1-nu_a_h)*bP_a_h*S_c_l*P_a_h-(1-nu_e_h)*bP_e_h*S_c_l*P_e_h-(1-nu_c_l)*bP_c_l*S_c_l*P_c_l-(1-nu_a_l)*bP_a_l*S_c_l*P_a_l-(1-nu_e_l)*bP_e_l*S_c_l*P_e_l -nu_c_h*bA_c_h*S_c_l*A_c_h-nu_a_h*bA_a_h*S_c_l*A_a_h-nu_e_h*bA_e_h*S_c_l*A_e_h-nu_c_l*bA_c_l*S_c_l*A_c_l-nu_a_l*bA_a_l*S_c_l*A_a_l-nu_e_l*bA_e_l*S_c_l*A_e_l -(1-nu_c_h)*bA_c_h*S_c_l*A_c_h-(1-nu_a_h)*bA_a_h*S_c_l*A_a_h-(1-nu_e_h)*bA_e_h*S_c_l*A_e_h-(1-nu_c_l)*bA_c_l*S_c_l*A_c_l-(1-nu_a_l)*bA_a_l*S_c_l*A_a_l-(1-nu_e_l)*bA_e_l*S_c_l*A_e_l -nu_c_h*bI_c_h*S_c_l*I_c_h-nu_a_h*bI_a_h*S_c_l*I_a_h-nu_e_h*bI_e_h*S_c_l*I_e_h-nu_c_l*bI_c_l*S_c_l*I_c_l-nu_a_l*bI_a_l*S_c_l*I_a_l-nu_e_l*bI_e_l*S_c_l*I_e_l -(1-nu_c_h)*bI_c_h*S_c_l*I_c_h-(1-nu_a_h)*bI_a_h*S_c_l*I_a_h-(1-nu_e_h)*bI_e_h*S_c_l*I_e_h-(1-nu_c_l)*bI_c_l*S_c_l*I_c_l-(1-nu_a_l)*bI_a_l*S_c_l*I_a_l-(1-nu_e_l)*bI_e_l*S_c_l*I_e_l
    #Presymptomatic children low risk : infection by presymptomatic, children, low risk : infection by ill, children, low risk : infection by asymptomatic, children, low risk : progression to symptoms, children, low risk :
    dP_c_l_mb = +nu_c_h*bP_c_h*S_c_l*P_c_h+nu_a_h*bP_a_h*S_c_l*P_a_h+nu_e_h*bP_e_h*S_c_l*P_e_h+nu_c_l*bP_c_l*S_c_l*P_c_l+nu_a_l*bP_a_l*S_c_l*P_a_l+nu_e_l*bP_e_l*S_c_l*P_e_l +nu_c_h*bA_c_h*S_c_l*A_c_h+nu_a_h*bA_a_h*S_c_l*A_a_h+nu_e_h*bA_e_h*S_c_l*A_e_h+nu_c_l*bA_c_l*S_c_l*A_c_l+nu_a_l*bA_a_l*S_c_l*A_a_l+nu_e_l*bA_e_l*S_c_l*A_e_l +nu_c_h*bI_c_h*S_c_l*I_c_h+nu_a_h*bI_a_h*S_c_l*I_a_h+nu_e_h*bI_e_h*S_c_l*I_e_h+nu_c_l*bI_c_l*S_c_l*I_c_l+nu_a_l*bI_a_l*S_c_l*I_a_l+nu_e_l*bI_e_l*S_c_l*I_e_l -sigma_c_l*P_c_l
    #Asymptomatic children low risk : infection by presymptomatic, children, low risk : infection by ill, children, low risk : infection by asymptomatic, children, low risk : recovery, children, low risk :
    dA_c_l_mb = +(1-nu_c_h)*bP_c_h*S_c_l*P_c_h+(1-nu_a_h)*bP_a_h*S_c_l*P_a_h+(1-nu_e_h)*bP_e_h*S_c_l*P_e_h+(1-nu_c_l)*bP_c_l*S_c_l*P_c_l+(1-nu_a_l)*bP_a_l*S_c_l*P_a_l+(1-nu_e_l)*bP_e_l*S_c_l*P_e_l +(1-nu_c_h)*bA_c_h*S_c_l*A_c_h+(1-nu_a_h)*bA_a_h*S_c_l*A_a_h+(1-nu_e_h)*bA_e_h*S_c_l*A_e_h+(1-nu_c_l)*bA_c_l*S_c_l*A_c_l+(1-nu_a_l)*bA_a_l*S_c_l*A_a_l+(1-nu_e_l)*bA_e_l*S_c_l*A_e_l +(1-nu_c_h)*bI_c_h*S_c_l*I_c_h+(1-nu_a_h)*bI_a_h*S_c_l*I_a_h+(1-nu_e_h)*bI_e_h*S_c_l*I_e_h+(1-nu_c_l)*bI_c_l*S_c_l*I_c_l+(1-nu_a_l)*bI_a_l*S_c_l*I_a_l+(1-nu_e_l)*bI_e_l*S_c_l*I_e_l -gammaA_c_l*A_c_l
    #Ill children low risk : progression to symptoms, children, low risk : progression to hospitalization, children, low risk : progression to recovery, children, low risk :
    dI_c_l_mb = +sigma_c_l*P_c_l -phi_c_l*gammaI_c_l*I_c_l -(1-phi_c_l)*gammaI_c_l*I_c_l
    #Hospitalized children low risk : progression to hospitalization, children, low risk : progression to death, children, low risk : progression to recovery, children, low risk :
    dH_c_l_mb = +phi_c_l*gammaI_c_l*I_c_l -rho_c_l*gammaH_c_l*H_c_l -(1-rho_c_l)*gammaH_c_l*H_c_l
    #Recovered children low risk : recovery of asymptomatics, children, low risk : recovery of ill, children, low risk : recovery of hospitalized, children, low risk :
    dR_c_l_mb = +gammaA_c_l*A_c_l +(1-phi_c_l)*gammaI_c_l*I_c_l +(1-rho_c_l)*gammaH_c_l*H_c_l
    #Deceased children low risk : death, children, low risk :
    dD_c_l_mb = +rho_c_l*gammaH_c_l*H_c_l
    #Susceptible adults low risk : infection by presymptomatic leading to symptomatic infections, adults, low risk : infection by presymptomatic leading to asymptomatic infections, adults, low risk : infection by asymptomatic leading to symptomatic infections, adults, low risk : infection by asymptomatic leading to asymptomatic infections, adults, low risk : infection by symptomatic leading to symptomatic infections, adults, low risk : infection by symptomatic leading to asymptomatic infections, adults, low risk :
    dS_a_l_mb = -nu_c_h*bP_c_h*S_a_l*P_c_h-nu_a_h*bP_a_h*S_a_l*P_a_h-nu_e_h*bP_e_h*S_a_l*P_e_h-nu_c_l*bP_c_l*S_a_l*P_c_l-nu_a_l*bP_a_l*S_a_l*P_a_l-nu_e_l*bP_e_l*S_a_l*P_e_l -(1-nu_c_h)*bP_c_h*S_a_l*P_c_h-(1-nu_a_h)*bP_a_h*S_a_l*P_a_h-(1-nu_e_h)*bP_e_h*S_a_l*P_e_h-(1-nu_c_l)*bP_c_l*S_a_l*P_c_l-(1-nu_a_l)*bP_a_l*S_a_l*P_a_l-(1-nu_e_l)*bP_e_l*S_a_l*P_e_l -nu_c_h*bA_c_h*S_a_l*A_c_h-nu_a_h*bA_a_h*S_a_l*A_a_h-nu_e_h*bA_e_h*S_a_l*A_e_h-nu_c_l*bA_c_l*S_a_l*A_c_l-nu_a_l*bA_a_l*S_a_l*A_a_l-nu_e_l*bA_e_l*S_a_l*A_e_l -(1-nu_c_h)*bA_c_h*S_a_l*A_c_h-(1-nu_a_h)*bA_a_h*S_a_l*A_a_h-(1-nu_e_h)*bA_e_h*S_a_l*A_e_h-(1-nu_c_l)*bA_c_l*S_a_l*A_c_l-(1-nu_a_l)*bA_a_l*S_a_l*A_a_l-(1-nu_e_l)*bA_e_l*S_a_l*A_e_l -nu_c_h*bI_c_h*S_a_l*I_c_h-nu_a_h*bI_a_h*S_a_l*I_a_h-nu_e_h*bI_e_h*S_a_l*I_e_h-nu_c_l*bI_c_l*S_a_l*I_c_l-nu_a_l*bI_a_l*S_a_l*I_a_l-nu_e_l*bI_e_l*S_a_l*I_e_l -(1-nu_c_h)*bI_c_h*S_a_l*I_c_h-(1-nu_a_h)*bI_a_h*S_a_l*I_a_h-(1-nu_e_h)*bI_e_h*S_a_l*I_e_h-(1-nu_c_l)*bI_c_l*S_a_l*I_c_l-(1-nu_a_l)*bI_a_l*S_a_l*I_a_l-(1-nu_e_l)*bI_e_l*S_a_l*I_e_l
    #Presymptomatic adults low risk : infection by presymptomatic, adults, low risk : infection by ill, adults, low risk : infection by asymptomatic, adults, low risk : progression to symptoms, adults, low risk :
    dP_a_l_mb = +nu_c_h*bP_c_h*S_a_l*P_c_h+nu_a_h*bP_a_h*S_a_l*P_a_h+nu_e_h*bP_e_h*S_a_l*P_e_h+nu_c_l*bP_c_l*S_a_l*P_c_l+nu_a_l*bP_a_l*S_a_l*P_a_l+nu_e_l*bP_e_l*S_a_l*P_e_l +nu_c_h*bA_c_h*S_a_l*A_c_h+nu_a_h*bA_a_h*S_a_l*A_a_h+nu_e_h*bA_e_h*S_a_l*A_e_h+nu_c_l*bA_c_l*S_a_l*A_c_l+nu_a_l*bA_a_l*S_a_l*A_a_l+nu_e_l*bA_e_l*S_a_l*A_e_l +nu_c_h*bI_c_h*S_a_l*I_c_h+nu_a_h*bI_a_h*S_a_l*I_a_h+nu_e_h*bI_e_h*S_a_l*I_e_h+nu_c_l*bI_c_l*S_a_l*I_c_l+nu_a_l*bI_a_l*S_a_l*I_a_l+nu_e_l*bI_e_l*S_a_l*I_e_l -sigma_a_l*P_a_l
    #Asymptomatic adults low risk : infection by presymptomatic, adults, low risk : infection by ill, adults, low risk : infection by asymptomatic, adults, low risk : recovery, adults, low risk :
    dA_a_l_mb = +(1-nu_c_h)*bP_c_h*S_a_l*P_c_h+(1-nu_a_h)*bP_a_h*S_a_l*P_a_h+(1-nu_e_h)*bP_e_h*S_a_l*P_e_h+(1-nu_c_l)*bP_c_l*S_a_l*P_c_l+(1-nu_a_l)*bP_a_l*S_a_l*P_a_l+(1-nu_e_l)*bP_e_l*S_a_l*P_e_l +(1-nu_c_h)*bA_c_h*S_a_l*A_c_h+(1-nu_a_h)*bA_a_h*S_a_l*A_a_h+(1-nu_e_h)*bA_e_h*S_a_l*A_e_h+(1-nu_c_l)*bA_c_l*S_a_l*A_c_l+(1-nu_a_l)*bA_a_l*S_a_l*A_a_l+(1-nu_e_l)*bA_e_l*S_a_l*A_e_l +(1-nu_c_h)*bI_c_h*S_a_l*I_c_h+(1-nu_a_h)*bI_a_h*S_a_l*I_a_h+(1-nu_e_h)*bI_e_h*S_a_l*I_e_h+(1-nu_c_l)*bI_c_l*S_a_l*I_c_l+(1-nu_a_l)*bI_a_l*S_a_l*I_a_l+(1-nu_e_l)*bI_e_l*S_a_l*I_e_l -gammaA_a_l*A_a_l
    #Ill adults low risk : progression to symptoms, adults, low risk : progression to hospitalization, adults, low risk : progression to recovery, adults, low risk :
    dI_a_l_mb = +sigma_a_l*P_a_l -phi_a_l*gammaI_a_l*I_a_l -(1-phi_a_l)*gammaI_a_l*I_a_l
    #Hospitalized adults low risk : progression to hospitalization, adults, low risk : progression to death, adults, low risk : progression to recovery, adults, low risk :
    dH_a_l_mb = +phi_a_l*gammaI_a_l*I_a_l -rho_a_l*gammaH_a_l*H_a_l -(1-rho_a_l)*gammaH_a_l*H_a_l
    #Recovered adults low risk : recovery of asymptomatics, adults, low risk : recovery of ill, adults, low risk : recovery of hospitalized, adults, low risk :
    dR_a_l_mb = +gammaA_a_l*A_a_l +(1-phi_a_l)*gammaI_a_l*I_a_l +(1-rho_a_l)*gammaH_a_l*H_a_l
    #Deceased adults low risk : death, adults, low risk :
    dD_a_l_mb = +rho_a_l*gammaH_a_l*H_a_l
    #Susceptible elderly low risk : infection by presymptomatic leading to symptomatic infections, elderly, low risk : infection by presymptomatic leading to asymptomatic infections, elderly, low risk : infection by asymptomatic leading to symptomatic infections, elderly, low risk : infection by asymptomatic leading to asymptomatic infections, elderly, low risk : infection by symptomatic leading to symptomatic infections, elderly, low risk : infection by symptomatic leading to asymptomatic infections, elderly, low risk :
    dS_e_l_mb = -nu_c_h*bP_c_h*S_e_l*P_c_h-nu_a_h*bP_a_h*S_e_l*P_a_h-nu_e_h*bP_e_h*S_e_l*P_e_h-nu_c_l*bP_c_l*S_e_l*P_c_l-nu_a_l*bP_a_l*S_e_l*P_a_l-nu_e_l*bP_e_l*S_e_l*P_e_l -(1-nu_c_h)*bP_c_h*S_e_l*P_c_h-(1-nu_a_h)*bP_a_h*S_e_l*P_a_h-(1-nu_e_h)*bP_e_h*S_e_l*P_e_h-(1-nu_c_l)*bP_c_l*S_e_l*P_c_l-(1-nu_a_l)*bP_a_l*S_e_l*P_a_l-(1-nu_e_l)*bP_e_l*S_e_l*P_e_l -nu_c_h*bA_c_h*S_e_l*A_c_h-nu_a_h*bA_a_h*S_e_l*A_a_h-nu_e_h*bA_e_h*S_e_l*A_e_h-nu_c_l*bA_c_l*S_e_l*A_c_l-nu_a_l*bA_a_l*S_e_l*A_a_l-nu_e_l*bA_e_l*S_e_l*A_e_l -(1-nu_c_h)*bA_c_h*S_e_l*A_c_h-(1-nu_a_h)*bA_a_h*S_e_l*A_a_h-(1-nu_e_h)*bA_e_h*S_e_l*A_e_h-(1-nu_c_l)*bA_c_l*S_e_l*A_c_l-(1-nu_a_l)*bA_a_l*S_e_l*A_a_l-(1-nu_e_l)*bA_e_l*S_e_l*A_e_l -nu_c_h*bI_c_h*S_e_l*I_c_h-nu_a_h*bI_a_h*S_e_l*I_a_h-nu_e_h*bI_e_h*S_e_l*I_e_h-nu_c_l*bI_c_l*S_e_l*I_c_l-nu_a_l*bI_a_l*S_e_l*I_a_l-nu_e_l*bI_e_l*S_e_l*I_e_l -(1-nu_c_h)*bI_c_h*S_e_l*I_c_h-(1-nu_a_h)*bI_a_h*S_e_l*I_a_h-(1-nu_e_h)*bI_e_h*S_e_l*I_e_h-(1-nu_c_l)*bI_c_l*S_e_l*I_c_l-(1-nu_a_l)*bI_a_l*S_e_l*I_a_l-(1-nu_e_l)*bI_e_l*S_e_l*I_e_l
    #Presymptomatic elderly low risk : infection by presymptomatic, elderly, low risk : infection by ill, elderly, low risk : infection by asymptomatic, elderly, low risk : progression to symptoms, elderly, low risk :
    dP_e_l_mb = +nu_c_h*bP_c_h*S_e_l*P_c_h+nu_a_h*bP_a_h*S_e_l*P_a_h+nu_e_h*bP_e_h*S_e_l*P_e_h+nu_c_l*bP_c_l*S_e_l*P_c_l+nu_a_l*bP_a_l*S_e_l*P_a_l+nu_e_l*bP_e_l*S_e_l*P_e_l +nu_c_h*bA_c_h*S_e_l*A_c_h+nu_a_h*bA_a_h*S_e_l*A_a_h+nu_e_h*bA_e_h*S_e_l*A_e_h+nu_c_l*bA_c_l*S_e_l*A_c_l+nu_a_l*bA_a_l*S_e_l*A_a_l+nu_e_l*bA_e_l*S_e_l*A_e_l +nu_c_h*bI_c_h*S_e_l*I_c_h+nu_a_h*bI_a_h*S_e_l*I_a_h+nu_e_h*bI_e_h*S_e_l*I_e_h+nu_c_l*bI_c_l*S_e_l*I_c_l+nu_a_l*bI_a_l*S_e_l*I_a_l+nu_e_l*bI_e_l*S_e_l*I_e_l -sigma_e_l*P_e_l
    #Asymptomatic elderly low risk : infection by presymptomatic, elderly, low risk : infection by ill, elderly, low risk : infection by asymptomatic, elderly, low risk : recovery, elderly, low risk :
    dA_e_l_mb = +(1-nu_c_h)*bP_c_h*S_e_l*P_c_h+(1-nu_a_h)*bP_a_h*S_e_l*P_a_h+(1-nu_e_h)*bP_e_h*S_e_l*P_e_h+(1-nu_c_l)*bP_c_l*S_e_l*P_c_l+(1-nu_a_l)*bP_a_l*S_e_l*P_a_l+(1-nu_e_l)*bP_e_l*S_e_l*P_e_l +(1-nu_c_h)*bA_c_h*S_e_l*A_c_h+(1-nu_a_h)*bA_a_h*S_e_l*A_a_h+(1-nu_e_h)*bA_e_h*S_e_l*A_e_h+(1-nu_c_l)*bA_c_l*S_e_l*A_c_l+(1-nu_a_l)*bA_a_l*S_e_l*A_a_l+(1-nu_e_l)*bA_e_l*S_e_l*A_e_l +(1-nu_c_h)*bI_c_h*S_e_l*I_c_h+(1-nu_a_h)*bI_a_h*S_e_l*I_a_h+(1-nu_e_h)*bI_e_h*S_e_l*I_e_h+(1-nu_c_l)*bI_c_l*S_e_l*I_c_l+(1-nu_a_l)*bI_a_l*S_e_l*I_a_l+(1-nu_e_l)*bI_e_l*S_e_l*I_e_l -gammaA_e_l*A_e_l
    #Ill elderly low risk : progression to symptoms, elderly, low risk : progression to hospitalization, elderly, low risk : progression to recovery, elderly, low risk :
    dI_e_l_mb = +sigma_e_l*P_e_l -phi_e_l*gammaI_e_l*I_e_l -(1-phi_e_l)*gammaI_e_l*I_e_l
    #Hospitalized elderly low risk : progression to hospitalization, elderly, low risk : progression to death, elderly, low risk : progression to recovery, elderly, low risk :
    dH_e_l_mb = +phi_e_l*gammaI_e_l*I_e_l -rho_e_l*gammaH_e_l*H_e_l -(1-rho_e_l)*gammaH_e_l*H_e_l
    #Recovered elderly low risk : recovery of asymptomatics, elderly, low risk : recovery of ill, elderly, low risk : recovery of hospitalized, elderly, low risk :
    dR_e_l_mb = +gammaA_e_l*A_e_l +(1-phi_e_l)*gammaI_e_l*I_e_l +(1-rho_e_l)*gammaH_e_l*H_e_l
    #Deceased elderly low risk : death, elderly, low risk :
    dD_e_l_mb = +rho_e_l*gammaH_e_l*H_e_l
    #EndODES
    list(c(dS_c_h_mb,dP_c_h_mb,dA_c_h_mb,dI_c_h_mb,dH_c_h_mb,dR_c_h_mb,dD_c_h_mb,dS_a_h_mb,dP_a_h_mb,dA_a_h_mb,dI_a_h_mb,dH_a_h_mb,dR_a_h_mb,dD_a_h_mb,dS_e_h_mb,dP_e_h_mb,dA_e_h_mb,dI_e_h_mb,dH_e_h_mb,dR_e_h_mb,dD_e_h_mb,dS_c_l_mb,dP_c_l_mb,dA_c_l_mb,dI_c_l_mb,dH_c_l_mb,dR_c_l_mb,dD_c_l_mb,dS_a_l_mb,dP_a_l_mb,dA_a_l_mb,dI_a_l_mb,dH_a_l_mb,dR_a_l_mb,dD_a_l_mb,dS_e_l_mb,dP_e_l_mb,dA_e_l_mb,dI_e_l_mb,dH_e_l_mb,dR_e_l_mb,dD_e_l_mb)) 
  } ) } #close with statement, end ODE code block 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec_mb = c(S_c_h = S_c_h, P_c_h = P_c_h, A_c_h = A_c_h, I_c_h = I_c_h, H_c_h = H_c_h, R_c_h = R_c_h, D_c_h = D_c_h, S_a_h = S_a_h, P_a_h = P_a_h, A_a_h = A_a_h, I_a_h = I_a_h, H_a_h = H_a_h, R_a_h = R_a_h, D_a_h = D_a_h, S_e_h = S_e_h, P_e_h = P_e_h, A_e_h = A_e_h, I_e_h = I_e_h, H_e_h = H_e_h, R_e_h = R_e_h, D_e_h = D_e_h, S_c_l = S_c_l, P_c_l = P_c_l, A_c_l = A_c_l, I_c_l = I_c_l, H_c_l = H_c_l, R_c_l = R_c_l, D_c_l = D_c_l, S_a_l = S_a_l, P_a_l = P_a_l, A_a_l = A_a_l, I_a_l = I_a_l, H_a_l = H_a_l, R_a_l = R_a_l, D_a_l = D_a_l, S_e_l = S_e_l, P_e_l = P_e_l, A_e_l = A_e_l, I_e_l = I_e_l, H_e_l = H_e_l, R_e_l = R_e_l, D_e_l = D_e_l) 
  parvec_mb = c(bP_c_h = bP_c_h, bA_c_h = bA_c_h, bI_c_h = bI_c_h, nu_c_h = nu_c_h, sigma_c_h = sigma_c_h, gammaA_c_h = gammaA_c_h, gammaI_c_h = gammaI_c_h, gammaH_c_h = gammaH_c_h, phi_c_h = phi_c_h, rho_c_h = rho_c_h, bP_a_h = bP_a_h, bA_a_h = bA_a_h, bI_a_h = bI_a_h, nu_a_h = nu_a_h, sigma_a_h = sigma_a_h, gammaA_a_h = gammaA_a_h, gammaI_a_h = gammaI_a_h, gammaH_a_h = gammaH_a_h, phi_a_h = phi_a_h, rho_a_h = rho_a_h, bP_e_h = bP_e_h, bA_e_h = bA_e_h, bI_e_h = bI_e_h, nu_e_h = nu_e_h, sigma_e_h = sigma_e_h, gammaA_e_h = gammaA_e_h, gammaI_e_h = gammaI_e_h, gammaH_e_h = gammaH_e_h, phi_e_h = phi_e_h, rho_e_h = rho_e_h, bP_c_l = bP_c_l, bA_c_l = bA_c_l, bI_c_l = bI_c_l, nu_c_l = nu_c_l, sigma_c_l = sigma_c_l, gammaA_c_l = gammaA_c_l, gammaI_c_l = gammaI_c_l, gammaH_c_l = gammaH_c_l, phi_c_l = phi_c_l, rho_c_l = rho_c_l, bP_a_l = bP_a_l, bA_a_l = bA_a_l, bI_a_l = bI_a_l, nu_a_l = nu_a_l, sigma_a_l = sigma_a_l, gammaA_a_l = gammaA_a_l, gammaI_a_l = gammaI_a_l, gammaH_a_l = gammaH_a_l, phi_a_l = phi_a_l, rho_a_l = rho_a_l, bP_e_l = bP_e_l, bA_e_l = bA_e_l, bI_e_l = bI_e_l, nu_e_l = nu_e_l, sigma_e_l = sigma_e_l, gammaA_e_l = gammaA_e_l, gammaI_e_l = gammaI_e_l, gammaH_e_l = gammaH_e_l, phi_e_l = phi_e_l, rho_e_l = rho_e_l) 
  timevec_mb = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout = deSolve::ode(y = varvec_mb, parms = parvec_mb, times = timevec_mb,  func = Coronavirus_vaccine_model_v2_stratified_ode_fct, rtol = 1e-12, atol = 1e-12) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
} 
