#' SIR seasonal model
#' 
#' @description A basic seasonal SIR model with 3 compartments and infection and recovery processes
#' 
#' @details Add details.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of discrete time equations using a for loop. 
 
#' The following R packages need to be loaded for the function to work: none 
#' 
#' @param S : starting value for Susceptible population : numeric
#' @param I : starting value for Infected population : numeric
#' @param R : starting value for Recovered population : numeric
#' @param mu : birth and death rate : numeric
#' @param beta0 : baseline transmission rate : numeric
#' @param beta1 : seasonal transmission adjustment : numeric
#' @param omega : periodicity : numeric
#' @param gamma : recovery rate : numeric
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_SIR_seasonal_model_discrete() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_SIR_seasonal_model_discrete(S = 199998,I = 2,R = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel and Andrew Tredennick
#' @section Model creation date: 2023-05-08
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2023-05-08
#' @export 
 
simulate_SIR_seasonal_model_discrete <- function(S = 99999, I = 1, R = 0, mu = 2e-04, beta0 = 0.03, beta1 = 0.05, omega = 0.02, gamma = 0.01, tstart = 0, tfinal = 10000, dt = 1) 
{ 
  #Function that encodes simulation loop 
  SIR_seasonal_model_fct <- function(vars, pars, times) 
  {
    with( as.list(c(vars,pars)), {  
      ts = data.frame(cbind(times, matrix(0,nrow=length(times),ncol=length(vars)))) 
      colnames(ts) = c('time','S','I','R') 
      ct=1 #a counter to index array 
      for (t in times) 
      {
        ts[ct,] = c(t,S,I,R) 
        Sp = S + dt*(+mu*(S+I+R) -beta0*(1+beta1*sin(omega*t))*S*I/(S+I+R) -mu*S) 
        Ip = I + dt*(+beta0*(1+beta1*sin(omega*t))*S*I/(S+I+R) -gamma*I -mu*I) 
        Rp = R + dt*(+gamma*I -mu*R) 
        S = Sp 
        I = Ip 
        R = Rp 
        ct = ct + 1 
      } #finish loop 
      return(ts) 
    }) #close with statement 
 } #end function encoding loop 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec = c(S = S, I = I, R = R) 
  parvec = c(mu = mu, beta0 = beta0, beta1 = beta1, omega = omega, gamma = gamma) 
  timevec = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout <- SIR_seasonal_model_fct(vars = varvec, pars = parvec, times = timevec) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- simout 
  return(result) 
} 
