#' Cholera model
#' 
#' @description A Cholera model based on Codeco 2001 BMC ID
#' 
#' @details The model includes susceptible, infected, and environmental compartments. See reference for more details.
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of discrete time equations using a for loop. 
 
#' The following R packages need to be loaded for the function to work: none 
#' 
#' @param S : starting value for Susceptible : numeric
#' @param I : starting value for Infected : numeric
#' @param B : starting value for Bacteria : numeric
#' @param h : population size : numeric
#' @param n : birth rate : numeric
#' @param a : infection rate : numeric
#' @param k : 50% infection rate : numeric
#' @param r : recovery rate : numeric
#' @param nb : bacteria growth rate : numeric
#' @param mb : bacteria death rate : numeric
#' @param e : bacteria shedding rate : numeric
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Cholera_model_discrete() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Cholera_model_discrete(S = 20000,I = 2,B = 0) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'S'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of S: ',max(result$ts[,'S']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2023-05-08
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2023-05-08
#' @export 
 
simulate_Cholera_model_discrete <- function(S = 10000, I = 1, B = 0, h = 10000, n = 1e-04, a = 1, k = 1e+06, r = 0.2, nb = 1, mb = 1.33, e = 10, tstart = 0, tfinal = 500, dt = 0.1) 
{ 
  #Function that encodes simulation loop 
  Cholera_model_fct <- function(vars, pars, times) 
  {
    with( as.list(c(vars,pars)), {  
      ts = data.frame(cbind(times, matrix(0,nrow=length(times),ncol=length(vars)))) 
      colnames(ts) = c('time','S','I','B') 
      ct=1 #a counter to index array 
      for (t in times) 
      {
        ts[ct,] = c(t,S,I,B) 
        Sp = S + dt*(+n*h -n*S -a*B/(k+B)*S) 
        Ip = I + dt*(+a*B/(k+B)*S -r*I) 
        Bp = B + dt*(+nb*B -mb*B +e*I) 
        S = Sp 
        I = Ip 
        B = Bp 
        ct = ct + 1 
      } #finish loop 
      return(ts) 
    }) #close with statement 
 } #end function encoding loop 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec = c(S = S, I = I, B = B) 
  parvec = c(h = h, n = n, a = a, k = k, r = r, nb = nb, mb = mb, e = e) 
  timevec = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout <- Cholera_model_fct(vars = varvec, pars = parvec, times = timevec) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- simout 
  return(result) 
} 
