#' Influenza Antibody Model
#' 
#' @description Influenza Antibody Model
#' 
#' @details Model based on Zarnitsyna et al 2016 PLoS Pathogens
#' 
#' This code was generated by the modelbuilder R package.  
#' The model is implemented as a set of ordinary differential equations using the deSolve package. 
#' The following R packages need to be loaded for the function to work: deSolve. 
#' 
#' @param Hf : starting value for free antigen : numeric
#' @param Hb : starting value for bound antigen : numeric
#' @param B : starting value for B cells : numeric
#' @param A : starting value for antibodies : numeric
#' @param k : binding rate : numeric
#' @param df : free antigen decay rate : numeric
#' @param db : bound antigen decay rate : numeric
#' @param s : B cell generation rate : numeric
#' @param del : bound antibody strength : numeric
#' @param p : saturation level : numeric
#' @param a : FIM impact  : numeric
#' @param g : antibody production rate : numeric
#' @param dA : antibody decay rate : numeric
#' @param tstart : Start time of simulation : numeric
#' @param tfinal : Final time of simulation : numeric
#' @param dt : Time step : numeric
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Influenza_Antibody_Model_ode() 
#' # To choose values other than the standard one, specify them like this:  
#' result <- simulate_Influenza_Antibody_Model_ode(Hf = 20000,Hb = 0,B = 2,A = 2) 
#' # You can display or further process the result, like this:  
#' plot(result$ts[,'time'],result$ts[,'Hf'],xlab='Time',ylab='Numbers',type='l') 
#' print(paste('Max number of Hf: ',max(result$ts[,'Hf']))) 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2023-05-08
#' @section Code Author: generated by the \code{modelbuilder} R package 
#' @section Code creation date: 2023-05-08
#' @export 
 
simulate_Influenza_Antibody_Model_ode <- function(Hf = 10000, Hb = 0, B = 1, A = 1, k = 0.01, df = 0.5, db = 0.5, s = 1, del = 0, p = 0, a = 0, g = 0.1, dA = 0.1, tstart = 0, tfinal = 100, dt = 0.1) 
{ 
  ############################## 
  #Block of ODE equations for deSolve 
  ############################## 
  Influenza_Antibody_Model_ode_fct <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #free antigen : binding by antibodies : antibody decay :
    dHf_mb = -k*A*Hf -df*Hf
    #bound antigen : binding by antibodies : antibody removal :
    dHb_mb = +k*A*Hf -db*Hb
    #B cells : B cell activation :
    dB_mb = +s*B*(Hf+del*Hb)/(p+Hf+del*Hb)*(1/(1+a*Hb))
    #antibodies : generation : binding : decay :
    dA_mb = +g*B -k*A*Hf -dA*A
    #EndODES
    list(c(dHf_mb,dHb_mb,dB_mb,dA_mb)) 
  } ) } #close with statement, end ODE code block 
 
  ############################## 
  #Main function code block 
  ############################## 
  #Creating named vectors 
  varvec_mb = c(Hf = Hf, Hb = Hb, B = B, A = A) 
  parvec_mb = c(k = k, df = df, db = db, s = s, del = del, p = p, a = a, g = g, dA = dA) 
  timevec_mb = seq(tstart, tfinal,by = dt) 
  #Running the model 
  simout = deSolve::ode(y = varvec_mb, parms = parvec_mb, times = timevec_mb,  func = Influenza_Antibody_Model_ode_fct, rtol = 1e-12, atol = 1e-12) 
  #Setting up empty list and returning result as data frame called ts 
  result <- list() 
  result$ts <- as.data.frame(simout) 
  return(result) 
} 
