#' Cholera model
#' 
#' A Cholera model based on Codeco 2001 BMC ID
#' 
#' @details 
#' @param vars vector of starting conditions for model variables: 
#' \itemize{ 
#' \item S : starting value for Susceptible
#' \item I : starting value for Infected
#' \item B : starting value for Baceria
#' } 
#' @param pars vector of values for model parameters: 
#' \itemize{ 
#' \item h : population size
#' \item n : birth rate
#' \item a : infection rate
#' \item k : 50% infection rate
#' \item r : recovery rate
#' \item nbmb : effective bacteria growth rate
#' \item e : bacteria shedding rate
#' } 
#' @param times vector of values for model times: 
#' \itemize{ 
#' \item tstart : Start time of simulation
#' \item tfinal : Final time of simulation
#' \item dt : Time step
#' } 
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- Cholera_model_desolve() 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2018-09-05
#' @section Code Author: generated by the \code{convert_to_desolve} function 
#' @section Code creation date: 2018-09-11
#' @export 
 
Cholera_model_desolve <- function(vars = c(S = 10000, I = 1, B = 0), pars = c(h = 10000, n = 1e-04, a = 1, k = 1e+06, r = 0.2, nbmb = -0.33, e = 10), times = c(tstart = 0, tfinal = 500, dt = 0.1) ) 
{ 
  #Block of ODE equations for deSolve 
  Cholera_model_ode <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible : births : deaths : infection of susceptibles :
    dS = +n*h -n*S -a*B/(k+B)*S
    #Infected : infection of susceptibles : recovery of infected :
    dI = +a*B/(k+B)*S -r*I
    #Baceria : bacteria growth : bacteria decay : bacteria shedding :
    dB = +B*nbmb +e*I
    #EndODES
    list(c(dS,dI,dB)) 
  } ) } #close with statement, end ODE code block 
 
  #Main function code block 
  timevec=seq(times[1],times[2],by=times[3]) 
  odeout = deSolve::ode(y = vars, parms = pars, times = timevec,  func = Cholera_model_ode) 
  result <- list() 
  result$ts <- as.data.frame(odeout) 
  return(result) 
} 
