library(RxODE)


convert_to_rxode <- function(model)
{
  
  #if the model is passed in as an Rdata file name, load it
  #otherwise, it is assumed that 'model' is a list structure of the right type
  if(is.character(model)) {load(model)}
  
  #the name of the function produced by this script is  "model title" + "_RxODE.R"
  filename=paste0(gsub(" ","_",model$title),"_RxODE.R")
  nvars = length(model$var)  #number of variables/compartments in model
  npars = length(model$par)  #number of parameters in model
  ntime = length(model$time) #numer of parameters for time
  #text for model description
  #all this should be provided in the model sctructure
  sdesc=paste0("#' ",model$title,"\n#' \n")
  sdesc=paste0(sdesc,"#' ",model$description,"\n#' \n")
  sdesc=paste0(sdesc,"#' @description USER CAN ADD MORE DETAILS HERE \n")
  for (n in 1:nvars)
  {
    sdesc=paste0(sdesc,"#' @param ", model$var[[n]]$varname, ' starting value for ',model$var[[n]]$vartext, "\n")
  }
  for (n in 1:npars)
  {
    sdesc=paste0(sdesc,"#' @param ", model$par[[n]]$parname," ", model$par[[n]]$partext, "\n")
  }
  for (n in 1:ntime)
  {
    sdesc=paste0(sdesc,"#' @param ", model$time[[n]]$timename," ", model$time[[n]]$timetext, "\n")
  }
  sdesc=paste0(sdesc,"#' @return The function returns the output as a list. \n")
  sdesc=paste0(sdesc,"#' The time-series from the simulation is returned as a dataframe saved as list element ts. \n")
  sdesc=paste0(sdesc,"#' The ts dataframe has one column per compartment/variable. The first column is time.   \n")
  sdesc=paste0(sdesc,"#' @details USER CAN ADD MORE DETAILS HERE  \n")
  sdesc=paste0(sdesc,"#' @examples  \n")
  sdesc=paste0(sdesc,"#' # To run the simulation with default parameters just call the function:  \n")
  sdesc=paste0(sdesc,"#' result <- ",gsub(" ","_",model$title),"_desolve()", " \n")
  sdesc=paste0(sdesc,"#' @modelauthor ",model$author, "\n")
  sdesc=paste0(sdesc,"#' @modeldate ",model$date, "\n")
  sdesc=paste0(sdesc,"#' @functionauthor generated by convert_to_desolve function \n")
  sdesc=paste0(sdesc,"#' @fuctiondate ",Sys.Date(), "\n")
  sdesc=paste0(sdesc,"#' @export \n \n")
  
  ##############################################################################
  #the next block of commands produces the ODE function required by RxODE
  sode = "  #Block of ODE equations for RxODE \n"
  sode = paste0(sode,"  ", gsub(" ","_",model$title),'_ode <-  \n  "\n')
  
  #text for equations and final list
  seqs= "    #StartODES\n"
  
  for (n in 1:nvars)
  {
    seqs = paste0(seqs,"    #",model$var[[n]]$vartext,' : ', paste(model$var[[n]]$flownames, collapse = ' : '),' :\n')
    seqs = paste0(seqs,'    d/dt(',model$var[[n]]$varname, ')',' = ',paste(model$var[[n]]$flows, collapse = ' '), '\n' )

  }
  sode=paste0(sode,seqs)
  sode = paste0(sode,'    #EndODES \n', '" \n')
  #finish block that creates the ODE function
  ##############################################################################
  
  
  ##############################################################################
  #this creates the lines of code for the main function
  #text for main body of function
  varstring = "vars = c("
  for (n in 1:nvars)
  {
    varstring=paste0(varstring, model$var[[n]]$varname," = ", model$var[[n]]$varval,', ')
  }
  varstring = substr(varstring,1,nchar(varstring)-2)
  varstring = paste0(varstring,'), ') #close parantheses
  
  parstring = "pars = c("
  for (n in 1:npars)
  {
    parstring=paste0(parstring, model$par[[n]]$parname," = ", model$par[[n]]$parval,', ')
  }
  parstring = substr(parstring,1,nchar(parstring)-2)
  parstring = paste0(parstring,'), ') #close parantheses
  
  timestring = "time = c("
  
  for (n in 1:ntime)
  {
    timestring=paste0(timestring, model$time[[n]]$timename," = ", model$time[[n]]$timeval,', ')
  }
  
  timestring = substr(timestring,1,nchar(timestring)-2)
  timestring = paste0(timestring,') ') #close parantheses
  
  stitle = paste0(gsub(" ","_",model$title),"_RxODE <- function(",varstring, parstring, timestring,') \n{ \n')
  
  smain = "\n"
  
  smain = paste0(smain,'  times=seq(time[1],time[2],by=time[3]) \n')
  smain = paste0(smain,'  ev = eventTable() \n')
  smain = paste0(smain,'  ev$add.sampling(times) \n \n')
  smain = paste0(smain,'  inits = vars \n \n')
  smain = paste0(smain,'  mod = RxODE(model = SIR_model_ode, modName = "mod1") \n \n')
  smain = paste0(smain,'  odeout<- mod$run(pars, ev, inits=inits) \n \n')
  
  smain = paste0(smain,'  result <- list() \n \n');
  smain = paste0(smain,'  result$ts <- as.data.frame(odeout) \n \n')
  smain = paste0(smain,'  return(result) \n \n')
  smain = paste0(smain,'} \n')
  #finish block that creates main function part
  ##############################################################################
  
  ##############################################################################
  #write all text blocks to file
  sink(filename)
  cat(sdesc)
  cat(stitle)
  cat(sode)
  cat(smain)
  sink()
}
