#' SIR model
#' 
#' A basic SIR model with 3 compartments and infection and recovery processes
#' 
#' @details The model includes susceptible, infected, and recovered compartments. The two processes that are modeled are infection and recovery.
#' @param vars vector of starting conditions for model variables: 
#' \itemize{ 
#' \item S : starting value for Susceptible
#' \item I : starting value for Infected
#' \item R : starting value for Recovered
#' } 
#' @param pars vector of values for model parameters: 
#' \itemize{ 
#' \item b : infection rate
#' \item g : recovery rate
#' } 
#' @param times vector of values for model times: 
#' \itemize{ 
#' \item tstart : Start time of simulation
#' \item tfinal : Final time of simulation
#' \item dt : Time step
#' } 
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_SIR_model_discrete() 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2018-09-16
#' @section Code Author: generated by the \code{generate_discrete} function 
#' @section Code creation date: 2018-09-16
#' @export 
 
simulate_SIR_model_discrete <- function(vars = c(S = 1000, I = 1, R = 0), pars = c(b = 0.002, g = 1), times = c(tstart = 0, tfinal = 100, dt = 0.1) ) 
{ 
  #Main function code block 
  timevec=seq(times[1],times[2],by=times[3]) 
  nvars=length(vars) 
  ts = cbind(timevec, matrix(0,nrow=length(timevec)+1,ncol=nvars)) 
  ts = data.frame(ts)  
  colnames(ts) = c("time","S","I","R") 
  ct=1 #a counter to index array 
  V=rep(0,nvars)
  #Block of simulator code 
   with( as.list(c(vars,pars,times)), {  
   for (t in timevec) 
   { 
     V[1] = S + dt*(-b*S*I) 
     V[2] = I + dt*(+b*S*I -g*I) 
     V[3] = R + dt*(+g*I) 
     S= V[1] 
     I= V[2] 
     R= V[3] 
     ct = ct + 1 
     ts[ct,] = c(t[ct],V) 
  } #finish loop 
  }) #close with statement 
  result <- list() 
  result$ts <- ts 
  return(result) 
} 
