#' SIR model
#' 
#' A basic SIR model with 3 compartments and infection and recovery processes
#' 
#' @description USER CAN ADD MORE DETAILS HERE 
#' @param S starting value for Susceptible
#' @param I starting value for Infected
#' @param R starting value for Recovered
#' @param b infection rate
#' @param g recovery rate
#' @param tstart Start time of simulation
#' @param tfinal Final time of simulation
#' @param dt Time step
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element ts. 
#' The ts dataframe has one column per compartment/variable. The first column is time.   
#' @details USER CAN ADD MORE DETAILS HERE  
#' @examples  
#' # To run the simulation with default parameters just call the function:  
#' result <- SIR_model_() 
#' @modelauthor Andreas Handel
#' @modeldate 2018-09-02
#' @functionauthor generated by convert_to_desolve function 
#' @fuctiondate 2018-09-02
#' @export 
#' 
#' 

SIR_model_rxode <- function(vars = c(S = 1000, I = 1, R = 0), pars = c(b = 0.002, g = 1), time = c(tstart = 0, tfinal = 100, dt = 0.1) ) 
{ 
  SIR_model_ode <-
  "
      #StartODES
      #Susceptible : infection of susceptibles :
      d/dt(S) = -b*S*I;
      #Infected : infection of susceptibles : recovery of infected :
      d/dt(I) = +b*S*I -g*I;
      #Recovered : recovery of infected :
      d/dt(R) = +g*I;
      #EndODES
  "
  
  times=seq(time[1],time[2],by=time[3]) 
  ev = eventTable()
  ev$add.sampling(times)
  
  inits = vars
  
  mod <- RxODE(model = SIR_model_ode, modName = "mod1")
  
  odeout <- mod$run(pars, ev, inits=inits)
  
  result <- list()
  result$ts <- as.data.frame(odeout)
  
  return(result)
  
}
