#' Vector transmission model
#' 
#' A basic model with several compartments to model vector-borne transmission
#' 
#' @description USER CAN ADD MORE DETAILS HERE 
#' @param Sh starting value for Susceptible Humans
#' @param Ih starting value for Infected Humans
#' @param Rh starting value for Recovered Humans
#' @param Sv starting value for Susceptible Vectors
#' @param Iv starting value for Infected Vctors
#' @param b1 infection rate of hosts
#' @param b2 infection rate of vectors
#' @param g recovery rate of hosts
#' @param w wanning immunity rate
#' @param b vector birth rate
#' @param n vector death rate
#' @param t0 start time 
#' @param tf final time 
#' @param dt time steps 
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element ts. 
#' The ts dataframe has one column per compartment/variable. The first column is time.   
#' @details USER CAN ADD MORE DETAILS HERE  
#' @examples  
#' # To run the simulation with default parameters just call the function:  
#' result <- Vector_transmission_model_desolve() 
#' @modelauthor Andreas Handel
#' @modeldate 2018-08-31
#' @functionauthor generated by convert_to_desolve function 
#' @fuctiondate 2018-08-31
#' @export 
 
Vector_transmission_model_desolve <- function(vars = c(Sh = 1000, Ih = 1, Rh = 0, Sv = 1000, Iv = 1), pars = c(b1 = 0.002, b2 = 0.002, g = 1, w = 0.1, b = 100, n = 0.1), tvec = c(t0 = 0, tf = 100, dt = 0.1)) 
{ 
  #Block of ODE equations for deSolve 
  Vector_transmission_model_ode <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    dSh = -b1*Sh*Iv +w*Rh #Susceptible Humans
    dIh = +b1*Sh*Iv -g*Ih #Infected Humans
    dRh = +g*Ih -w*Rh #Recovered Humans
    dSv = +b -b2*Sv*Ih +n*Sv #Susceptible Vectors
    dIv = +b2*Sv*Ih -n*Iv #Infected Vctors
    list(c(dSh,dIh,dRh,dSv,dIv)) 
  } ) } #close with statement, end ODE function 
 
  #Main function code block 
  times=seq(tvec[1],tvec[2],by=tvec[3]) 
  odeout = deSolve::ode(y = vars, parms= pars, times = times,  func = Vector_transmission_model_ode) 
  result <- list() 
  result$ts <- as.data.frame(odeout) 
  return(result) 
} 
