#' Vector transmission model
#' 
#' A basic model with several compartments to model vector-borne transmission
#' 
#' @description USER CAN ADD MORE DETAILS HERE 
#' @param vars vector of starting conditions for these model variables: 
#' Sh : starting value for Susceptible Humans
#' Ih : starting value for Infected Humans
#' Rh : starting value for Recovered Humans
#' Sv : starting value for Susceptible Vectors
#' Iv : starting value for Infected Vctors
#' @param pars vector of values for these model parameters: 
#' b1 : infection rate of hosts
#' b2 : infection rate of vectors
#' g : recovery rate of hosts
#' w : wanning immunity rate
#' b : vector birth rate
#' n : vector death rate
#' @param times vector of values for these model times: 
#' tstart : Start time of simulation
#' tfinal : Final time of simulation
#' dt : Time step
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element ts. 
#' The ts dataframe has one column per compartment/variable. The first column is time.   
#' @details USER CAN ADD MORE DETAILS HERE  
#' @examples  
#' # To run the simulation with default parameters just call the function:  
#' result <- Vector_transmission_model_desolve() 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2018-09-02
#' @section Function Author: generated by convert_to_desolve function 
#' @section Function creation date: 2018-09-07
#' @export 
 
Vector_transmission_model_desolve <- function(vars = c(Sh = 1000, Ih = 1, Rh = 0, Sv = 1000, Iv = 1), pars = c(b1 = 0.002, b2 = 0.002, g = 1, w = 0.1, b = 100, n = 0.1), times = c(tstart = 0, tfinal = 100, dt = 0.1) ) 
{ 
  #Block of ODE equations for deSolve 
  Vector_transmission_model_ode <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible Humans : infection of susceptible hosts : waning immunity :
    dSh = -b1*Sh*Iv +w*Rh
    #Infected Humans : infection of susceptible hosts : recovery of infected :
    dIh = +b1*Sh*Iv -g*Ih
    #Recovered Humans : recovery of infected hosts : waning immunity :
    dRh = +g*Ih -w*Rh
    #Susceptible Vectors : vector births : infection of susceptible vectors : death of susceptible vectors :
    dSv = +b -b2*Sv*Ih +n*Sv
    #Infected Vctors : infection of susceptible vectors : death of infected vectors :
    dIv = +b2*Sv*Ih -n*Iv
    #EndODES
    list(c(dSh,dIh,dRh,dSv,dIv)) 
  } ) } #close with statement, end ODE code block 
 
  #Main function code block 
  timevec=seq(times[1],times[2],by=times[3]) 
  odeout = deSolve::ode(y = vars, parms = pars, times = timevec,  func = Vector_transmission_model_ode) 
  result <- list() 
  result$ts <- as.data.frame(odeout) 
  return(result) 
} 
